kubernetes-sigs/external-dns

.github/workflows/lint-test-chart.yaml
.github/workflows/release-chart.yaml
charts/external-dns/CHANGELOG.md
charts/external-dns/Chart.yaml

This PR updates the helm chart to use ExternalDNS `v0.12.2` and includes the merged PRs since the last release; it also includes updates to the GitHub actions used to release the chart which are locked down to specific commits so that a moved tag can't introduce different code.
Fixes #2916
**Checklist**

Updated Helm chart to use ExternalDNS v0.12.2

---

provider/infoblox/infoblox.go
provider/infoblox/infoblox_test.go

The ibclient.GetObject will return all the objects associated with the query. This is an issue when external-dns has identified 1 record to remove. The object being created retrieves many more records than expected and so external-dns will delete all the matching records.
This change adds one "name" filter to the query parameters so that only the expected record is removed from infoblox
**Checklist**

Infoblox - Correct GetObject query

---

docs/tutorials/aws.md

Example deployment manifest in AWS tutorial had a typo. It should be **Uncomment** not  **Uncommend**

Fixed a minor typo in aws tutorial

---

go.mod
go.sum

The GoVultr dependency is a few versions behind. There haven't been any breaking changes that would change the behavior of the vultr provider (low impact).
cc: @optik-aper 
No GH Issue
Fixes #ISSUE
**Checklist**

bump govultr from v2.14.1 to v2.17.2

---

go.mod
go.sum

- bumps github.com/IBM/networking-go-sdk
- bumps github.com/sirupsen/logrus
- bumps github.com/aws/aws-sdk-go
- github.com/ans-group/sdk-go
- cloud.google.com/go/compute
Closes https://github.com/kubernetes-sigs/external-dns/pull/2962 https://github.com/kubernetes-sigs/external-dns/pull/2963 https://github.com/kubernetes-sigs/external-dns/pull/2964 https://github.com/kubernetes-sigs/external-dns/pull/2966 https://github.com/kubernetes-sigs/external-dns/pull/2967
/cc @njuettner

More dependabot updates

---

source/ambassador_host.go
source/ambassador_host_test.go

If e.g the ambassador service annotation points to an nonexisting service, external-dns will not update any DNS records. This PR makes external-dns ignore the host and carry on instead.
Didn't provide any unit tests as this code didn't seem to have anything like a fake client that knows about ambassador hosts. Did however validate the logic in a live cluster.

Ignore ambassador-hosts with invalid annotations

---

docs/tutorials/gke.md
main.go

Google Cloud Logging (AKA Stackdriver Logs) interprets the default
logrus log format as "error" severity even when `level=info` is
present in the log output: ensure that the normal startup log
is not parsed as an error by setting the JSON formatter first.
**Checklist**
Signed-off-by: Nathan J Mehl <n@oden.io>

Set logformat before logging config

---

README.md
docs/tutorials/tencentcloud.md
go.mod
go.sum
main.go
pkg/apis/externaldns/types.go
pkg/apis/externaldns/types_test.go
provider/tencentcloud/cloudapi/api.go
provider/tencentcloud/cloudapi/clientset.go
provider/tencentcloud/cloudapi/mockapi.go
provider/tencentcloud/cloudapi/readonlyapi.go
provider/tencentcloud/cloudapi/tencentapi.go
provider/tencentcloud/dnspod.go
provider/tencentcloud/privatedns.go
provider/tencentcloud/tencent_cloud.go
provider/tencentcloud/tencent_cloud_test.go
provider/zone_id_filter.go

Signed-off-by: misakazhou <misakazhou@tencent.com>
Add the provider for tencent cloud.
PrivateDNS service provides intranet DNS resolution.
DNSPod service provides internet DNS resolution.
Unit tests and document is updated for the tencent cloud provider.
Any issue about the tencent cloud provider can ask @Hyzhou for help and upgrade. 
Fixes #ISSUE
**Checklist**

Add the provider for the Tencent Cloud.

---

go.mod
go.sum

- Bump github.com/Azure/azure-sdk-for-go from 61.5.0+incompatible to 66.0.0+incompatible - https://api.github.com/repos/kubernetes-sigs/external-dns/pulls/3025
- Bump github.com/linode/linodego from 0.32.2 to 1.9.1 - https://api.github.com/repos/kubernetes-sigs/external-dns/pulls/2985
- Bump github.com/akamai/AkamaiOPEN-edgegrid-golang from 1.1.1 to 1.2.1 - https://api.github.com/repos/kubernetes-sigs/external-dns/pulls/2970
- Bump github.com/maxatome/go-testdeep from 1.11.0 to 1.12.0 - https://api.github.com/repos/kubernetes-sigs/external-dns/pulls/2968

Bump dependencies for multiple packages

---

docs/tutorials/aws.md

Addressing typos in `aws.md`:
https://github.com/kubernetes-sigs/external-dns/blob/cc82c6b727bd38af64454470e0bd97602e7588e6/docs/tutorials/aws.md?plain=1#L127
https://github.com/kubernetes-sigs/external-dns/blob/cc82c6b727bd38af64454470e0bd97602e7588e6/docs/tutorials/aws.md?plain=1#L100
https://github.com/kubernetes-sigs/external-dns/blob/cc82c6b727bd38af64454470e0bd97602e7588e6/docs/tutorials/aws.md?plain=1#L115
https://github.com/kubernetes-sigs/external-dns/blob/cc82c6b727bd38af64454470e0bd97602e7588e6/docs/tutorials/aws.md?plain=1#L160
https://github.com/kubernetes-sigs/external-dns/blob/cc82c6b727bd38af64454470e0bd97602e7588e6/docs/tutorials/aws.md?plain=1#L197
https://github.com/kubernetes-sigs/external-dns/blob/cc82c6b727bd38af64454470e0bd97602e7588e6/docs/tutorials/ …

Documentation: Update aws.md

---

endpoint/endpoint.go
registry/txt.go
registry/txt_test.go

We should expect that 63 char labels works also with the txt registry. But as can be seen from https://github.com/kubernetes-sigs/external-dns/issues/2839 and others, this is not the case after introducing the new format.
This PR doesn't fix the underlying problem in any way, but it maintains backwards compatibility by ignoring the new format if it results in endpoint with too long name. This way, e.g route53 batch changes will keep working with the consequence of not migrating to the new format.
Note: This will also prevent subtle breakage in case e.g the service annotation contains invalid DNS labels.
**Checklist**

Don't create endpoint if attempting to create one with invalid dns name

---

README.md

With respect to them having a huge bug for the Infoblox provider. See https://github.com/kubernetes-sigs/external-dns/pull/2890

Add a warning about releases v0.12.0 - v0.12.2

---

kustomize/external-dns-deployment.yaml

Use  `registry.k8s.io` in `kustomize/external-dns-deployment.yaml` file
Fixes #2992
**Checklist**

Use registry.k8s.io in external-dns-deployment yml

---

endpoint/domain_filter.go
endpoint/domain_filter_test.go
provider/alibabacloud/alibaba_cloud.go
provider/google/google.go
provider/ibmcloud/ibmcloud.go
provider/oci/oci.go

This aims to fix regression #2821.
I've tweaked `endpoint.DomainFilter.IsConfigured()` to pass for filters that only express exclusion rules (either regular expression-based exclusion or an explicit exclusion list). I've also tweaked some of the initialization to handle empty strings in explicit filter lists less ambiguously.
Fixes #2821 
**Checklist**

Restore support for exclusion-only domain filters for AWS provider

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/release-chart.yaml
.github/workflows/trivy.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third …

GitHub Workflows security hardening

---

provider/godaddy/client.go

Remove leading space from https://api.ote-godaddy.com endpoint.
Fixes #3043

Remove leading space from https://api.ote-godaddy.com endpoint

---

provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_test.go

When an A or CNAME record must be changed, in the current state the provider attempts to create a record then delete the old record. The create fails due to there being an existing A/CNAME record with that name, and then the delete succeeds, leaving the name unresolvable until the next time the external-dns loop runs.
By doing the delete first, this issue is mitigated. While not as elegant as using UPDATE calls, it is a lot simpler.
Attempts to remediate https://github.com/kubernetes-sigs/external-dns/issues/2820 and (to some extent) https://github.com/kubernetes-sigs/external-dns/issues/2435
**Checklist**

reorder cloudflare updates to delete before create

---

source/istio_virtualservice.go

This PR fixes a bug where external-dns deletes all DNS records when they are created via VirtualServices and the Kubernetes API returns an error (#2858).
Before this change we saw the following in the external-dns logs:
```
2022-11-08T11:17:55.397663277Z stderr F {"file":"/sigs.k8s.io/external-dns/source/istio_virtualservice.go:207","func":"sigs.k8s.io/external-dns/source.(*virtualServiceSource).getGateway","level":"error","msg":"Failed retrieving gateway istio-system/istio-default-gateway referenced by VirtualService kobs/hub: Unauthorized","time":"2022-11-08T11:17:55Z"}
2022-11-08T11:17:55.397675627Z stderr F {"file":"/sigs.k8s.io/external-dns/source/istio_virtualservice.go:167","func":"sigs.k8s.io/external-dns/source.(*virtualServiceSource).Endpoints","level":"debug","ms …
```

Fix deletion of DNS Records for VirtualServices when an Error occures

---

plan/plan.go

The previous code version only iterates over current ProviderSpecific properties. This new version iterates over desired properties, including those that were just set.
[shouldUpdateProviderSpecific](https://github.com/kubernetes-sigs/external-dns/blob/master/plan/plan.go#L211) seems to be iterating over just the current properties that were previously set, not taking into consideration for planning changes when additional ProviderSpecific properties were just set. 
Fixes #2953 
**Checklist**

fix: New provider specific update

---

provider/rfc2136/rfc2136.go

Signed-off-by: Jack Henschel <jack.henschel@cern.ch>
This patch removes the deprecated `hmac-md5` TSIG algorithm from the supported list.
The `dns` library used by the RFC2136 provider no longer supports this algorithm: https://github.com/miekg/dns/pull/1187/files
Users are currently experiencing the following error message (at runtime!) when configuring external-dns with this algorithm:
```
failed to fetch records via AXFR: dns: bad key algorithm
```
**Checklist**

rfc2136: remove deprecated MD5 key algorithm

---

plan/plan.go

Reverts kubernetes-sigs/external-dns#3177. This PR has broken tests in master.

Revert "fix: New provider specific update"

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/docs.yml
.golangci.yml
Dockerfile
Dockerfile.mini
Makefile
docs/contributing/getting-started.md
go.mod
go.sum
internal/testutils/endpoint.go

This PR updates ExternalDNS to go 1.19. Replaces https://github.com/kubernetes-sigs/external-dns/pull/3131.

Upgrade ExternalDNS to go 1.19

---

docs/tutorials/azure-private-dns.md

I tested the tutorial with:
```
image: k8s.gcr.io/external-dns/external-dns:v0.13.1
```

Bump external-dns image tag to v0.13.1

---

.golangci.yml
internal/testutils/init.go
pkg/tlsutils/tlsconfig.go
provider/alibabacloud/alibaba_cloud.go
provider/azure/azure.go
provider/azure/azure_private_dns.go
provider/azure/config.go
provider/azure/config_test.go
provider/bluecat/gateway/api.go
provider/bluecat/gateway/api_test.go
provider/coredns/coredns.go
provider/designate/designate_test.go
provider/godaddy/client.go
provider/ibmcloud/ibmcloud.go
provider/oci/oci.go
provider/pihole/client.go
provider/provider_test.go
provider/rdns/rdns.go
provider/tencentcloud/cloudapi/tencentapi.go
provider/tencentcloud/tencent_cloud.go
source/crd_test.go
source/skipper_routegroup.go

This PR contains some linting fixes. I am ignoring changes to the azure provider as those require adjustment in code and I will be doing them in a separate PR. 
Basing on https://github.com/kubernetes-sigs/external-dns/actions/runs/3586738470/jobs/6036296019, I will do fixes in the codebase to address them. 
Fixed #3194

CI linting fixes

---

provider/aws/aws.go
provider/aws/aws_test.go

This PR allows Route53 record updates to change the routing policy to/from simple from/to other routing policies. These record modifications do not support UPSERT, but instead, require DELETE/CREATE to succeed.
The AWS provider function `createUpdateChanges` has been updated with another conditional to test if one of the old/new set identifiers is the empty string and the other is not.
The AWS Provider test `TestAWSApplyChanges` has been updated to validate the change.
While examining what should be changed, I identified that the AWS provider function `UpdateRecords` is unused, and may be a candidate for removal. If desired I can address that here as well.
Fixes #3141
**Checklist**

fix: Support conversion from/to simple to/from other routing policies for the AWS provider.

---

provider/aws/aws.go
provider/aws/aws_test.go

Reverts kubernetes-sigs/external-dns#3159 because it broke tests in the default branch. 
/cc @szuecs who approved the original PR.

Revert "fix: Support conversion from/to simple to/from other routing policies for the AWS provider."

---

provider/digitalocean/digital_ocean.go
provider/digitalocean/digital_ocean_test.go

This PR should fix the issue where the Digital Ocean provider unnecessarily tries to update records,
due to the TTL comparison that happens [here](https://github.com/kubernetes-sigs/external-dns/blob/master/plan/plan.go#L197).
```go
func shouldUpdateTTL(desired, current *endpoint.Endpoint) bool {
if !desired.RecordTTL.IsConfigured() {
return false
}
return desired.RecordTTL != current.RecordTTL
}
```
The changes makes sure the TTL field is used when creating records.
Fixes #2754
**Checklist**
Signed-off-by: Ismayil Mirzali <ismayilmirzeli@gmail.com>

bug: fix digital ocean provider not setting TTL

---

.github/workflows/lint.yaml

This project's CI is way too slow. There are many things that we can do, but the first trivial one is to split the lint phase from the normal go tests. 
👇  5 and 4 minutes in parallel instead of a total of 9, this is a 4 minutes speedup for tests 🎉

Split CI to speedup checks

---

README.md
docs/tutorials/aws-load-balancer-controller.md

The ALB Ingress Controller project has been renamed to AWS Load Balancer Controller. This PR fixes all references to the old name in the docs.
**Checklist**

docs: rename ALB ingress controller to AWS Load Balancer Controller

---

provider/designate/designate.go

I have noticed that the designate records are constantly created and deleted because the compared records contain labels like ```designate-recordset-id``` but the endpoints that are collected by the service does not contain such labels therefore they are always be created and deleted. 
Fixes #ISSUE
**Checklist**

designate: exclude internal labels

---

docs/tutorials/aws-load-balancer-controller.md

The ALB Ingress Controller project has been renamed to AWS Load Balancer Controller. This PR fixes some more references to the old name in the docs.
**Checklist**

docs: rename alb-ingress-controller to aws-load-balancer-controller

---

source/gateway_httproute.go
source/gateway_tcproute.go
source/gateway_tlsroute.go
source/gateway_udproute.go

The informers are not always setting the TypeMeta (APIVersion and Kind) on objects. It's unclear to me why this is. Perhaps the API Server omits it as a wire optimization on watches and the client doesn't put it back? Whatever the reason, the Gateway API code depends on it existing. This explicitly adds TypeMeta to objects coming from the informers.
Fixes #3068

gateway-api: patch route informer results with TypeMeta

---

registry/txt.go
registry/txt_test.go

The generateTXTRecord uses a subsequent call, assuming the return from NewEndpoint wont ever be null.
It happens that if the first name is bigger than 63 characters, it will be null and get a null pointer.
This PR fixes this specific part of the code.
**Checklist**

Fix null pointer on generateTxtRecord

---

go.mod
go.sum
provider/ovh/ovh.go

It looks like this import was supposed to be golang.org/x/sync instead of github.com/golang/sync.

provider/ovh: Fix import

---

provider/aws/aws.go
provider/aws/aws_test.go
provider/ovh/ovh.go

Signed-off-by:  @jessegonzalez 
This PR allows Route53 record updates to change the routing policy to/from simple from/to other routing policies. These record modifications do not support UPSERT, but instead, require DELETE/CREATE to succeed.
The AWS provider function createUpdateChanges has been updated with another conditional to test if one of the old/new set identifiers is the empty string and the other is not.
The AWS Provider test TestAWSApplyChanges has been updated to validate the change, and validated before PR submission. 
Original PR: #3159 did not include stashed changes.
<details>
<summary>Local test output</summary>
```
❯ make test
go test -race -coverprofile=profile.cov ./...
?       sigs.k8s.io/external-dns        [no test files]
ok …
```

Allow AWS Route53 routing policy change to/from simple to others.

---

docs/tutorials/azure-private-dns.md
docs/tutorials/azure.md

**Improves the Azure Tutorials**
* Bump container images to v0.13.1
* Add example with kubernetes service and `external-dns.alpha.kubernetes.io/hostname` annotation
* Add example with `external-dns.alpha.kubernetes.io/internal-hostname`
* Add example used in combination with `service.beta.kubernetes.io/azure-load-balancer-internal`

Improve Azure tutorials

---

endpoint/labels.go
internal/testutils/endpoint.go
provider/aws/aws.go
provider/aws/aws_test.go
registry/txt.go
registry/txt_test.go

If a single change fails during the retry, it will be added to a queue.
In the next iteration, changes from this queue will be submitted after
all other changes.
When submitting single changes, they are always submitted as batches of
changes with the same DNS name to avoid inconsistency between the record
created and the TXT records.
This closes #421.

Route53: retry single changes in a batch if the batch fails

---

.github/workflows/gh-workflow-approve.yaml

This PR adds a GH workflow to automatically approve running GH actions for first time contributors once the `ok-to-test` label has been added. This should significantly reduce the pressure on the maintainers with repo ownership. I've tested the logic works correctly but I've not used it as a GH action yet.
**IMPORTANT** - This has no impact on any repo code so can be merged without fixing flaking jobs.
**Checklist**

Added automation to run GH actions on PRs with ok-to-test

---

provider/awssd/aws_sd.go
provider/awssd/aws_sd_test.go

Fix for https://github.com/kubernetes-sigs/external-dns/issues/2706 using HasPrefix to check for owner ship.
Fixes #2706
**Checklist**

Use HasPrefix to check for ownerID

---

provider/aws/aws.go
provider/aws/aws_test.go

Add Osaka (ap-northeast-3) Hosted Zone ID for AWS Network Load Balancers based on the documentation: https://docs.aws.amazon.com/general/latest/gr/elb.html
Fixes #ISSUE
There is no issue opened on this topic.
**Checklist**

Add Osaka (ap-northeast-3) Hosted Zone ID for AWS Network Load Balancers

---

.github/workflows/release-chart.yaml
charts/external-dns/CHANGELOG.md
charts/external-dns/Chart.yaml

This PR updates the chart to use the latest version of ExternalDNS (`v0.13.2`).
Fixes #3324
**Checklist**

feat[chart]: Updated to v0.13.2

---

.github/workflows/gh-workflow-approve-test.yaml

This PR fixes the GH Workflow approval action which I previously added. I have debugged why this was working correctly on my CLI but not in the action and I have run it in a test repo to prove that it functioning correctly without errors.
**Checklist**

chore: Fixed GH action workflow approval

---

Dockerfile

Fixes https://github.com/kubernetes-sigs/external-dns/issues/3385 by forcing updating `libcrypto3` and `libssl3`. There are patch versions released for alpine, but no new image tagged that contains those fixes. This change will force CI to update those, resolving the vulnerabilities.

Force updating libcrypto3 and libssl3 in docker image

---

docs/tutorials/aws.md

Fix a minor typo in AWS tutorial: "commerical" -> "commercial"

Fix a minor typo in AWS tutorial

---

.github/workflows/staging-image-tester.yml
Dockerfile
Makefile

This introduces docker buildx so that we can more properly build multiarch images. Until today, we relied on a hack and that caused the builds to be slow and to stop building once that we had the requirement to actually have at least a `RUN` instruction in the Dockerfile. 
It also introduces a new github action that actually builds the images in CI without needing to merge so that we can test if images are building all time time.
Possible risks: we have no way to try this against kubernetes' CI other than merging, so we have to try and merge this and in the worst case iterate on it incrementally.

docker buildx and tester

---

Dockerfile

In order to do a clean release, I want to have no known vulnerabilities (other than those who don't apply). To do so, this PR forces newer version of libcrypto and libssl.

Bump libcrypto and libssl

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/json-yaml-validate.yml
.github/workflows/lint.yaml
.github/workflows/staging-image-tester.yml

This pull request does the following:
- Updates `actions/setup-go` and `actions/setup-python` to `v4` tags
- Adds a new Actions workflow to validate json and yaml files in the repository
I recently developed a new [GitHub Action](https://github.com/GrantBirki/json-yaml-validate) to validate json and yaml files. It runs in under [5 seconds for this repository](https://github.com/GrantBirki/external-dns/actions/runs/4525392545/jobs/7969850803) and it is a native JS Action. I noticed that @Raffo (who I work with at @github) contributes to this repository in my feed so I took a look at this repo. I saw there were a handful of `*.yaml` files in this repo and figured it would be helpful if they got validated on pull requests through GitHub actions so maintainers can know if they are valid or …

Actions Updates - yaml & json validation

---

pkg/apis/externaldns/types.go

When passed as a comma separated list `managed-record-types` ends up being an array with a single element.
Instead it should be passed multiple times to include more than one record, same as in: 
https://github.com/kubernetes-sigs/external-dns/blob/cfdc4b42ae144747479daa944e329603d0dc8192/pkg/apis/externaldns/types_test.go#L374

Fix docs for `--managed-record-types`

---

charts/external-dns/CHANGELOG.md
charts/external-dns/templates/clusterrole.yaml

Add RBAC to be able to handle F5 VirtualServer `Source`. Support for F5 VirtualServers were added here: https://github.com/kubernetes-sigs/external-dns/pull/3162.
**Checklist**

Add RBAC to be able to handle F5 VirtualServer source

---

provider/designate/designate.go
provider/designate/designate_test.go

Allow multiple records per A record. Therefore update the Delete and Create order so, we don't delete a single old record value.
Before this patch, external-dns alternated between two IPs as record values if upgraded from a single record to two A records.
Fetch labels from existing TXT records to fix https://github.com/kubernetes-sigs/external-dns/issues/
Fixes #603
**Checklist**

Allow multiple records per A record in OpenStack Designate Provider

---

README.md

Updated link for external-dns.png in README.md as if was breaking in https://kubernetes-sigs.github.io/external-dns/v0.13.3/
copy_docs.sh copy README.md to docs/index.md so relative link should be corresponding to new location 
Fixes #3475 
**Checklist**

updated relative link for external-dns logo

---

main.go
source/crd.go
source/crd_test.go
source/store.go

When the `--events` flag is passed at startup, `Source.AddEventHandler()` is called
on each configured source.  Most sources provide `AddEventHandler()`
implementations that invoke the reconciliation loop when the configured source
changes, but the CRD source had a no-op implementation.  I.e. when a custom
resource was created, updated, or deleted, external-dns remained unware, and the
reconciliation loop would not fire until the configured interval had passed.
This change adds an informer (on the CRD specified by `--crd-source-apiversion`
and `--crd-source-kind=DNSEndpoint`), and a `Source.AddEventHandler()`
implementation that calls `Informer.AddEventHandler()`.  Now when a custom
resource is created, updated, or deleted, the reconciliation loop is invoked.
I ran …

CRD source: add event-handler support

---

docs/tutorials/oracle.md

The recently-added support for Oracle's OCI IAM instance principal authentication included an incorrect arg name in the change to the Oracle tutorial.  This changes the tutorial to specify the correct arg name.  Thanks to joe.rosinski@oracle.com for spotting the problem.
Fixes https://github.com/kubernetes-sigs/external-dns/issues/3545
**Checklist**

Fix incorrect arg in Oracle OCI tutorial

---

go.mod
go.sum
provider/oci/oci.go
provider/oci/oci_test.go

Bumps [github.com/oracle/oci-go-sdk](https://github.com/oracle/oci-go-sdk) from 24.3.0 to 65.35.0.
**Testing**
Deployed the sample service from the OCI Tutorial doc  
redacted results below  
`INFO[0000] Instantiating new Kubernetes client`
`INFO[0000] Using kubeConfig`
`INFO[0000] Created Kubernetes client https://X.X.X.X:XX`   
`INFO[0010] All records are already up to date`    
`INFO[0066] All records are already up to date`      
`INFO[0133] Change zone: "ocid1.dns-zone.oc1..162fffffffffffffffffffffffee1cabf"`   
`INFO[0133] { Domain=nginx.jrosinsk.developer.redacted.com RecordHash=<nil> IsProtected=<nil> Rdata=x.x.x.x`   `RrsetVersion=<nil> Rtype=A Ttl=300 Operation=ADD }`     
`INFO[0133] { Domain=nginx.jrosinsk.developer.redacted.com RecordHash=<nil> …

OCI provider: bump oci-go-sdk from 24.3.0 to 65.35.0

---

charts/external-dns/README.md
charts/external-dns/templates/deployment.yaml
charts/external-dns/values.yaml
main.go
pkg/apis/externaldns/types.go
source/service.go
source/service_test.go
source/store.go

This PR adds an optional feature (turned off by default).
On EKS for example, the LoadBalancer-type Service object will not have external IP addresses but external hostnames. In this case, external-dns will always create an `Endpoint` (an external-dns concept, see its go [struct](https://pkg.go.dev/sigs.k8s.io/external-dns/endpoint#Endpoint)) whose `RecordType` is `CNAME`. But the user might want to create `A` or `AAAA` records instead, and perhaps on a different DNS provider (e.g. Cloudflare) than the cluster provider (e.g. AWS). 
This PR adds an optional feature that allows external-dns to resolve the LB hostname into IP addresses before creating the `Endpoint` struct.
Fixes #ISSUE
**Checklist**

feat: resolve LB-type Service hostname to create A/AAAA instead of CNAME

---

docs/tutorials/cloudflare.md
provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_test.go

Currently, the Cloudflare provider in external-dns can only read the Cloudflare API token from an environment variable named `$CF_API_TOKEN`. Users could populate `$CF_API_TOKEN` with a Kubernetes Secret. But a more flexible way is to read the Cloudflare API token from file. For example, if the user stores the secret (Cloudflare API token) in HashiCorp Vault, and uses [vault agent sidecar](https://developer.hashicorp.com/vault/docs/platform/k8s/injector) to provide the secret to external-dns container through a shared volume backed by memory, allowing the Cloudflare provider in external-dns to read this secret file would be superb.
**Checklist**

cloudflare: support reading API token from file

---

charts/external-dns/README.md
charts/external-dns/templates/deployment.yaml
charts/external-dns/values.yaml

This PR reverts the changes made to the Helm chart in #3554 as we don't try to duplicate the binary args as structure chart values and instead recommend the use of `extraArgs`.
**Checklist**

chore(chart): Reverted chart changes to args

---

controller/controller.go

~Related to #3008, when external-dns is configured with multiple sources and one of them fails, all other sources are skipped as well. This PR logs and continues rather than aborting completely and log.~
If an error propagates all the way out to the control loop, log and exit rather than log and carry on.

If an error propagates all the way out, bail execution

---

docs/contributing/crd-source/dnsendpoint-example.yaml

This adds an example for provider specific configuration with the CRD source.
I read through the source code to find out why my annotations were not working, so I thought I'd spare the next person that time.
**Checklist**

docs: add example for provider specific config

---

docs/tutorials/nodes.md
source/compatibility.go
source/node.go
source/node_test.go
source/pod.go
source/pod_test.go
source/service.go
source/service_test.go
source/shared_test.go
source/source.go

IPv6 clusters do not a NATed private-use network; IPv6 node addresses are allocated from the global unicast address space and are accessible from the internet if firewalls allow. IPv6 node addresses are always reported as type `NodeInternalIP` despite being usable both internally and externally.
This PR causes the sources that use node IP addresses to treat `NodeInternalIP` addresses that parse as IPv6 as being both internal and external.
It also fixes the node, pod, and dns-controller sources to set the record type to `AAAA` for node addresses that have IPv6 syntax.
This roughly corresponds to kubernetes/kops#12608.
Fixes #1875
**Checklist**

IPv6 internal node IPs are usable externally

---

README.md
docs/tutorials/mx-record.md
endpoint/endpoint.go
provider/aws/aws.go
provider/aws/aws_test.go
provider/azure/azure.go
provider/azure/azure_private_dns.go
provider/azure/azure_privatedns_test.go
provider/azure/azure_test.go
provider/azure/common.go
provider/azure/common_test.go
provider/google/google.go
provider/google/google_test.go

Add support for `MX` record types in Azure, GCP and AWS. This still needs to be explicitly enabled by specifying a CLI flag `--managed-record-types=MX`.
Tested on all 3 cloud providers with a CRD source:
```
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
name: test-mxrecord
spec:
endpoints:
- dnsName: example.com
recordTTL: 180
recordType: MX
targets:
- 10 mail.example.com
- 30 mail.foo.com
```
**Checklist**

Add support for MX records in Azure, GCP and AWS

---

provider/aws/aws_test.go

Refactors the Route53 provider unit tests to be more precise in their specification of initial and expected state.
These are the first two commits of #3605, separated out to allow earlier merging.
**Checklist**

Refactor route53 tests

---

source/pod.go
source/pod_test.go
source/source.go

This PR allows multiple record names separated by commas in the internal-hostname annotation of pods, as is available for services.
**Checklist**

Allow multiple hostnames in internal annotation for pods

---

provider/azure/azure.go
provider/azure/azure_private_dns.go
provider/azure/azure_privatedns_test.go
provider/azure/azure_test.go

The underlying SDK uses `recordSetsClient.CreateOrUpdate()` [doc](https://docs.microsoft.com/en-us/rest/api/dns/record-sets/create-or-update) which allows us to exclusively rely on UpdateNew for record set updates. As a result, we're no longer running the risk of zone update failures causing outages as outlined in #2918
Fix https://github.com/kubernetes-sigs/external-dns/issues/2918
Supersedes https://github.com/kubernetes-sigs/external-dns/pull/3285
**Checklist**

Remove UpdateOld changeset for Azure

---

provider/gandi/gandi.go
provider/gandi/gandi_test.go

Gandi return all TXT records grouped by domain... So if you have multiple TXT (as SPF, various domain verifications, etc...) [this line](https://github.com/kubernetes-sigs/external-dns/blob/master/provider/gandi/gandi.go#L123) throw an error. 
This fix is simple, as all `rrset_values` returned from the gandi livedns api is an array, i simply add a for_each loop on each of these values.
Fixes #2451
**Checklist**

fix(gandi): allow grandi provider to support multiple TXT rsetvalues

---

Dockerfile

Previous PR was the last PR and solved some CVEs.
- https://github.com/kubernetes-sigs/external-dns/pull/3500
This should resolve CVE-2023-1255 and CVE-2023-0465 by bumping libcrypto3 and libssl3 to 3.0.8-r4
```
~ docker run -u root -it --rm --entrypoint sh registry.k8s.io/external-dns/external-dns:v0.13.4 -c \
'apk update && apk add "libcrypto3>=3.0.8-r4" "libssl3>=3.0.8-r4" && apk info libcrypto3'
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/aarch64/APKINDEX.tar.gz
v3.17.3-202-gc3b7872ff80 [https://dl-cdn.alpinelinux.org/alpine/v3.17/main]
v3.17.3-195-gc5298d215ef [https://dl-cdn.alpinelinux.org/alpine/v3.17/community]
OK: 17694 distinct packages available
(1/2) Upgrading …
```

chore(deps): bump libcrypto3 and libssl3 3.0.8-r4

---

docs/tutorials/civo.md
docs/tutorials/gandi.md
docs/tutorials/hostport.md
docs/tutorials/public-private-route53.md

Was working on R53 today for a test setup and some of the manifests for AWS R53 were outdated. Here's a tiny PR to fix them.
- update rbac.authorization apiVersion from `rbac.authorization.k8s.io/v1beta1` to `rbac.authorization.k8s.io/v1` as it was [deprecated in k8s 1.22](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#rbac-resources-v122)
- update deployment and statefulset apiVersion from `apps/v1beta` to `apps/v1` as it was [deprecated in k8s 1.16](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#deployment-v116)
**Checklist**

docs: Update deprecated apiVersions

---

charts/external-dns/CHANGELOG.md
charts/external-dns/Chart.yaml

This PR updates the Helm chart to use the latest ExternalDNS version ([v0.13.5](https://github.com/kubernetes-sigs/external-dns/releases/tag/v0.13.5)) and includes all the other improvements since the last release (see CHANGELOG).
Followed the same format as https://github.com/kubernetes-sigs/external-dns/pull/3516.
Fixes https://github.com/kubernetes-sigs/external-dns/issues/3644
@stevehipwell 😃 
**Checklist**

feat(chart): updated chart to ExternalDNS v0.13.5

---

docs/contributing/crd-source.md

The current example of CRD source is missing the `Labels` type
definition.  It also does not have the JSON tag for the `Name` and
`Value` fields of the `ProviderSpecificProperty` type.  As such,
creating a CRD from these types will result in errors.
This change fixes the two issues highlighted above.
Fixes #3455
**Checklist**

 Define Labels type and JSON tags for ProviderSpecific fields 

---

endpoint/domain_filter.go
endpoint/target_filter.go
endpoint/target_filter_test.go
provider/akamai/akamai.go
provider/pihole/client.go
provider/tencentcloud/privatedns.go
provider/zone_id_filter.go

Refactor the two filtering interfaces to reduce complexity.
**Checklist**

Simplify filter interfaces

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/docs.yml
.github/workflows/lint.yaml
.golangci.yml
Dockerfile
Dockerfile.mini
docs/contributing/getting-started.md
go.mod
provider/coredns/coredns.go
provider/rdns/rdns.go
provider/tencentcloud/cloudapi/mockapi.go
source/fake.go

This PR
- update ExternalDNS to go 1.20
- Replace #3357,
- Inspired by #3152
- update golangci-lint to v1.53.2 
- Remove unconfigured depguard
- Move to new way of using seed, cf [go 1.20 release notes](https://tip.golang.org/doc/go1.20)
**Checklist**

Upgrade ExternalDNS to go 1.20

---

.github/dependabot.yml

This PR enables dependabot grouped updates. This is a new alpha feature of dependabot that is exclusively enabled for this project and that should create grouped PRs to help ship the dependabot PRs.

Enable dependabot grouped updates

---

.github/workflows/gh-workflow-approve.yaml

This PR fixes the _Approve GH Workflows_ GitHub Workflow which was broken by an update to the `actions/github-script` which makes the input variable types strict.
Fixes #ISSUE
**Checklist**

chore: Fixed gh workflow approve

---

provider/godaddy/client.go
provider/godaddy/godaddy.go

(I'm not Go dev so sorry if I do it too wrong)
Fix handling of second-level domains like `example.com`
Handle it in an obvious way because the old check was not supposed for that.
GoDaddy API used in the right way: https://developer.godaddy.com/doc/endpoint/domains
Check changes and only apply what actually changed.
Use PUT for record replacement (API doesn't allow partial updates or deletes).
Additionally:
* some simple rate limit handling (I have much more than 60 domains, and just realize that while debugging).
* Fix misleading `Discard` message, because as an end-user I several times got bald
* Tested on my environments, docker image: `public.ecr.aws/xflow-ltd/external-dns:0.13.5`
Old log, with lost of TXT records and broken dns
```
time="2021-12-08T12:32:44Z" …
```

Provider GoDaddy fix domain update

---

.github/workflows/lint-test-chart.yaml
.github/workflows/release-chart.yaml

Resolve  #3696 
Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yaml
echo "::set-output name=changed::true"
```
**TO-BE**
```yaml
echo "changed=true" >> $GITHUB_OUTPUT
```
**Checklist**

Replace deprecated command with environment file

---

charts/external-dns/CHANGELOG.md
charts/external-dns/ci/ci-values.yaml
charts/external-dns/values.yaml

feat(chart): comply with Pod Security Standards

---

endpoint/endpoint.go
provider/aws/aws.go
provider/aws/aws_test.go
provider/provider.go
provider/scaleway/scaleway.go

Fixes the Route53 provider so that it will reconcile changes to the configuration of target health checks on alias records.
Fixes the canonicalization of the `alias` provider-specific property so that the planner will not schedule unnecessary changes.
Prepares the Route53 provider for subsequent removal of the `provider.PropertyValuesEqual()` interface method.
**Checklist**

Route53 update configuration of target health checks

---

provider/scaleway/scaleway.go

Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>
Two small fixes for the Scaleway provider:
- defaults to a bigger page size for listing when there is a lot of domains
- avoid sending an empty update zone request

minor fixes to the scaleway provider

---

provider/pdns/pdns.go
provider/pdns/pdns_test.go

DNS cannot work with cname whose target is another domain.
**Example** (This cname does not work.):
`ads.localhost in google.com CNAME`
But PowerDNS can create [ALIAS](https://doc.powerdns.com/authoritative/guides/alias.html)
This PR changes the pdns provider to create aliases for such entries. This is required when k8s uses alb/nld on AWS etc.
**Checklist**

create an alias when record in a zone another than the target

---

provider/cloudflare/cloudflare.go

Many providers including aws and google is logging "All records are already up to date" when there is no change. For cloudflare this PR is adding it. I.e when there is no such a log in external-dns with cloudflare provider and there is in external-dns with aws provider, it is a bit confusing for the end users who use them both.
**Checklist**

Add no-change info log for cloudflare provider

---

source/service.go

Simplifies some code in the Service source.
**Checklist**

Refactor some Service code

---

docs/tutorials/scaleway.md

My recently added commit was in fact erroneous: https://github.com/kubernetes-sigs/external-dns/commit/ec2ad730ce9af3bf92df0904bf1cb903fbf16492
The SCW_DEFAULT_ORGANIZATION_ID is not to be added, but, in fact, to be removed as stated in this previous commit that removed it: https://github.com/kubernetes-sigs/external-dns/commit/bc5232d02c5f7adef4f1e699f5649f0a4934083c
**Checklist**

fix: scaleway documentation, remove SCW_DEFAULT_ORGANIZATION_ID

---

charts/external-dns/CHANGELOG.md
charts/external-dns/templates/clusterrole.yaml

As a follow-up to #3055, as suggested by @stevehipwell.
Only merge this once #3055 is merged onto the master.

Added traefik-proxy rules to helm chart

---

provider/aws/aws.go
provider/aws/aws_test.go

When using CNAME record with a TTL != 0, external-dns will continuously keep`UPSERTING` the record due to a difference in TTL. As per https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-choosing-alias-non-alias.html TTL for alias records is always set to the default value of 300s and can not be modified.
Steps to reproduce:
1. Create a CRD
```yaml
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
name: test-example
spec:
endpoints:
- dnsName: test.example.com
recordTTL: 60
recordType: CNAME
targets:
- <ELB_TARGET>
```
2. Wait for the record to be created
3. Restart `external-dns` to invalidate caches.
4. `Desired change: UPSERT test.example.com`
**Checklist**

[AWS] Adjust TTL for alias records

---

.github/dependabot.yml

Dependabot appears to be attempting to downgrade these dependencies to non-working versions.
**Checklist**

Suppress dependabot updates for OpenShift

---

pkg/apis/externaldns/types.go
source/multisource.go
source/multisource_test.go

add support to allow to add cnames and aaaa records to default-targets, similar to `external-dns.alpha.kubernetes.io/target` annotation.
#2244 
**Checklist**

support cnames and aaaa for default-targets

---

Makefile
scripts/releaser.sh
scripts/run-trivy.sh

`git describe` uses the wrong tag for the container images.
**Checklist**

use only tags with prefix v for version determination

---

controller/controller.go
controller/controller_test.go
provider/aws/aws.go
provider/aws/aws_test.go
provider/provider.go
registry/aws_sd_registry.go
registry/noop.go
registry/registry.go
registry/txt.go

Refactors the `Provider` interface to require a concrete `DomainFilter` instead of just any `DomainFilterInterface`. The purpose of this is to allow the upcoming Webhook provider to implement `GetDomainFilter` by having the negotiation phase return information needed to construct a copy of the target Provider's DomainFilter.
**Checklist**

Refactor Provider to require DomainFilter

---

registry/dynamodb.go

Currently the build for ExternalDNS is broken, this change fixes it. I think this was related to ordering of PRs merged.

Fix domain filter to fix build

---

.github/workflows/lint.yaml
.github/workflows/staging-image-tester.yml
Makefile

There are currently multiple issues in the CI system:
1. Go version used for `build All Images` is still go 1.19, it was missed in #3673
2. `pull-external-dns-lint` is launched on each PR and cannot succeed
3. `Build all images` is taking too much space on disk and fails on many PRs
This PR fixes this.

chore(ci): fix storage use, go version and lint job

---

provider/rfc2136/rfc2136.go

This PR removes the existing logic to use UDP or TCP for sending RFC2136 update queries, instead always using TCP.
The motivation behind this is to fix #3836. The DNS library used defers appending the TSIG signature until final serialization is complete (I used it as a reference implementation before, so am quite familiar). This results in the length check not using the proper packet length, but the pre-TSIG-length for determining TCP or UDP. Sending a UDP packet > 512 bytes for DNS is invalid (even if the network supports it), resulting in DNS servers discarding the packet as corrupt.
Rationale for completely removing UDP support here, is that the preceding AXFR uses TCP anyway (required by DNS protocol), and any performance gain from using UDP instead of TCP here is …

always use tcp for rfc2136

---

Dockerfile

alpine uses /var/cache/apk, not apt
Haven't opened an issue, the problem is obvious and fix is trivial. Correctly cleaning up APKINDEX saves ~1.8M from the built alpine image.
Alternative solution, which is less verbose, would be to just use
`apk add --no-cache "libcrypto3>=3.0.8-r4" "libssl3>=3.0.8-r4"`
**Checklist**

fix clean apk cache directory

---

provider/pdns/pdns.go

fix: pdns logging

---

pkg/apis/externaldns/types.go

Tagget parameter TXTEncryptAESKey as "secure" to avoid it being logged upon application startup.
Fixes #3790
**Checklist**

Tagget parameter TXTEncryptAESKey as secure

---

Dockerfile

Our Aquasec tool reported below High Vulnarability in libssl3:3.1.0-r4 and libcrypto3:3.1.0-r4. CVE's -
CVE-2023-2650
Fixes #ISSUE
This is fixed in 3.1.1-r0 so anything greater than this version is fine, thats why updating this to latest.
**Checklist**

Update Dockerfile for libssl3 and libcrypto3 CVE's

---

docs/tutorials/traefik-proxy.md

Adds example of traefik IngressRoute in the tutorial documentation.
Fixes #3852
**Checklist**

doc: Add example of setting up traefik IngressRoute with externalDNS annotations

---

registry/txt.go
registry/txt_test.go

The current implementation of the `toEndpoint` function is unable to handle records generated by the `toNewTXTName` function. As a result, domains created with a prefix such as `%{record_type}foo.` are not deleted after the associated CRD is removed.
This PR addresses this issue by improving the handling of records produced by the `toNewTXTName` function in the `toEndpoint` function. Additionally, it covers edge cases related to dashes or dots in the affix. A new test, `TestToEndpointNameNewTXT`, has been added to ensure the proper conversion between the output of `toNewTXTName` and its input using the `toEndpoint` function.
Additionally, this PR fixes the `testTXTRegistryRecordsPrefixed` test, which previously operated under the incorrect assumption that the output of `toNewTXTName` with …

[TXT Registry] Fix handling of records produced by `toNewTXTName` in `toEndpoint`

---

controller/controller.go
plan/plan.go
plan/plan_test.go
provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_test.go
provider/designate/designate.go
provider/ibmcloud/ibmcloud.go
provider/ibmcloud/ibmcloud_test.go
provider/plural/plural.go
provider/provider.go
provider/provider_test.go
registry/aws_sd_registry.go
registry/dynamodb.go
registry/noop.go
registry/registry.go
registry/txt.go

This is prep work for the webhook provider. Removes the frequently-called `PropertyValuesEqual` method from the `Provider` and `Registry` interfaces, requiring providers to normalize provider-specific properties in their `AdjustEndpoints` method.
**Checklist**

Remove PropertyValuesEqual method from Provider interface

---

docs/registry/dynamodb.md
main.go
registry/dynamodb.go
registry/dynamodb_test.go

Migrates the registry metadata from the TXT registry to the DynamoDB registry when the latter is enabled.
One annoyance is that the TXT ownership records don't get deleted unless TXT is added to the set of managed record types. It's not in the default set.
**Checklist**

Migrate metadata from TXT to DynamoDB registries

---

plan/plan.go
plan/plan_test.go

Fix reconciliation of provider-specific properties
Fixes #3801 
The planner would incorrectly fail to schedule an update when it needed to add a provider-specific property or when there were multiple properties and the first-found one matched.
**Checklist**

Fix reconciliation of provider-specific properties

---

docs/tutorials/ovh.md
go.mod
provider/ovh/ovh.go
provider/ovh/ovh_test.go

Hello external-dns maintainers, OVHcloud API team here :wave: 
This pull-request patches the 'ovh' provider to add a small local cache of the fetched DNS records.
Context: we detected that numerous of our customers use your external-dns software to manage their DNS records, sending waves of API queries to our APIs. As these records are retrieved one by one, it generates a high amount of requests on our backend.
As we would like to keep allowing our customers using external-dns with the best experience, we leveraged the usage of the DNS zone SOA Serial to detect if the zone records might have changed since the last time we generated the cache.
This way, we spare all the calls to retrieve the records that have been kept in cache, and serve them directly, since the SOA Serial …

feat(ovh): add cache based on DNS zone SOA value

---

Makefile

golangci-lint has been timing out frequently when run in Prow. Increase the timeout to fix this.
**Checklist**

Bump the timeout for golangci-lint

---

provider/aws/aws.go

- Adds mappings for API gateway regional endpoints to Route 53 Hosted Zone IDs.
- API gateway edge-optimized endpoints are served using CloudFront which has an existing mapping. ([Ref](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-basic-concept.html#apigateway-definition-edge-optimized-api-endpoint))
Fixes #3609 
**Checklist**

Add AWS API gateway endpoint zoneId mappings

---

docs/tutorials/istio.md
source/istio_gateway.go
source/istio_gateway_test.go
source/istio_virtualservice.go
source/istio_virtualservice_test.go

This adds support for a new annotation on an Istio Gateway to allow getting a target from an ingress object in place of a LoadBalancer service type. 
This is particularly useful for GCP's Anthos Service Mesh as they [guide](https://cloud.google.com/architecture/exposing-service-mesh-apps-through-gke-ingress/deployment) users to setup their gateways using a ClusterIP service type with an Ingress routing all traffic to the Gateway.
I don't see other annotation implementations for Source's and I'm looking for some guidance here on where this annotation should live (or if some other signal should be used in place of the annotation)
Fixes #2911
**Checklist**

feat: add support for ingress backed istio gateways

---

provider/alibabacloud/alibaba_cloud.go
provider/alibabacloud/alibaba_cloud_test.go

loop through all domains to match the domain record
instead of matching domain records with filter query, the idea is to first match the record with the hosted zones. If there is no match, splitDNS method then proceeds to split the domain to it's respective rr and Domain Name
Fixes https://github.com/kubernetes-sigs/external-dns/issues/3625
**Checklist**

loop through all hosted zones to match the domain record

---

go.mod
go.sum
main.go

It was removed in #3697 by last update on go modules.
It fixes #2348.
See PR #2361.

fix: remove useless warning log messages for instrumented_http.Transport

---

docs/tutorials/azure.md
provider/azure/config.go

In [Release 2022-10-10](https://github.com/Azure/AKS/blob/master/CHANGELOG.md#release-2022-10-10), AKS has brought support for [Workload Identity Federation](https://learn.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation) as a replacement for Pod-Managed Identities. The latter now is considered [deprecated](https://github.com/Azure/aad-pod-identity) and is about to reach its end of life.
This PR adds support for Workload Identity using azidentity (which replaced adal in #3040).
Fixes #2724 
**NOTE:** This PR comes to replace #3111 where I implemented workload identity using adal in a bit hacky way.
**Checklist**

feat(azure): add support for workload identity using azidentity

---

.github/workflows/lint-test-chart.yaml
.github/workflows/release-chart.yaml
charts/external-dns/CHANGELOG.md
charts/external-dns/Chart.yaml

This PR release the helm chart for `v0.13.6`.
Fixes #3891
**Checklist**

feat(helm-chart): Released chart for v0.13.6

---

provider/linode/linode.go
provider/linode/linode_test.go

A bug in the Linode provider can result in an unbounded explosion of TXT records being created. For example, if external-dns attempts to create a CNAME in a zone that has a conflicting A record, it will fail but will still create 2 new TXT records every single time.
Instead, we can just skip creating records that already exist since they should only ever be in the list of updates.
Fixes #3045
**Checklist**

fix(linode): don't try to create existing records

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/docs.yml
.github/workflows/lint.yaml
.github/workflows/staging-image-tester.yml
cloudbuild.yaml
docs/contributing/getting-started.md
go.mod
go.sum
provider/dnsimple/dnsimple_test.go

This update external dns to go 1.21.
Inspired by https://github.com/kubernetes-sigs/external-dns/pull/3673
**Checklist**

feat: upgrade ExternalDNS to go 1.21

---

source/service.go
source/service_test.go

External-dns handles nodePort differently to Service endpoints - Ignore pod status
Implement logic to check pod status and publish only ready & running pods instead of all.
Fixes #2704 
Additionally:
* Tested on my environments, docker image: `public.ecr.aws/xflow-ltd/external-dns:0.13.5`
**Checklist**

fix: nodePort #2704 - publish ready endpoints

---

provider/google/google.go
provider/google/google_test.go

Filters peering zones from the list of zones considered for creation of records by the google provider. This is needed because peering zones do not allow the creation of records, so if a peering zone matches a domain filter, external-dns tries to create records in it, causing the entire changeset to fail and no records to be created (even in other, valid zones).
Fixes #2947
**Checklist**
**Notes**
Changes to end user docs were not necessary.

fix: filter peering zones in google provider

---

docs/annotations/annotations.md
source/gateway.go
source/gateway_httproute_test.go

This allows the `external-dns.alpha.kubernetes.io/target` annotation to work for gateway api resources
Fixes #ISSUE
**Checklist**

Allow annotation target override on gateway

---

controller/controller.go
endpoint/endpoint.go
endpoint/endpoint_test.go
plan/conflict.go
plan/conflict_test.go
plan/plan.go
plan/plan_test.go
registry/aws_sd_registry.go
registry/dynamodb.go
registry/noop.go
registry/registry.go
registry/txt.go
registry/txt_test.go

When AAAA multi-target / dual stack support was
added via #2461 it broke ownership of domains across different clusters with different ingress records types.
For example if 2 clusters manage the same zone,
1 cluster uses A records and the other uses CNAME
records, when each record type is treated as a separate planning record, it will cause ownership to bounce back and forth and records to be constantly created and deleted.
This change updates the planner to keep track of multiple
current records for a domain. This allows for A and AAAA
records to exist for a domain while allowing record type
changes.
The planner will ignore desired records for a domain that
represent conflicting record types allowed by RFC 1034 3.6.2.
For example if the desired records for a domain …

Fix planning for multi-cluster dual stack record types

---

controller/controller.go
provider/aws/aws.go
provider/aws/aws_test.go
provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_test.go
provider/ibmcloud/ibmcloud.go
provider/ibmcloud/ibmcloud_test.go
provider/infoblox/infoblox.go
provider/plural/plural.go
provider/provider.go
provider/scaleway/scaleway.go
provider/scaleway/scaleway_test.go
registry/aws_sd_registry.go
registry/dynamodb.go
registry/noop.go
registry/registry.go
registry/txt.go

Allows the `AdjustEndpoints` method of `Provider` to return an `error`. This is needed for the Webhook provider, as calls can fail for transient network issues.
**Checklist**
/cc @Raffo

chore(providers): allow AdjustEndpoints to return error

---

registry/txt.go
registry/txt_test.go

There's an issue in `Records()` function in `TXT Registry`. When using templated affix, `recordType` will be passed in lowercase in:
https://github.com/kubernetes-sigs/external-dns/blob/6a53959385267e313675fd0024d91662ca4b69cf/registry/txt.go#L140-L144
This will then fail to match against the computed key with uppercase recordType in:
https://github.com/kubernetes-sigs/external-dns/blob/6a53959385267e313675fd0024d91662ca4b69cf/registry/txt.go#L159-L175
Surprisingly it wasn't caught by any of the existing tests. I've added few cases should capture that in the future.
**Checklist**

[TXT Registry] Fix `Records()` case handling

---

provider/godaddy/client.go
provider/godaddy/godaddy.go
provider/godaddy/godaddy_test.go

The problem in issue #3888 is that GoDaddy marks domains that aren't registered by GoDaddy itself with the status "PENDING_DNS_ACTIVE" instead of "ACTIVE". External-DNS filters these domains and only selects domains with the status "ACTIVE", using the statuses request parameter. To solve this issue, I'm including results with both statuses.
**Checklist**

Support GoDaddy domains with PENDING_DNS_ACTIVE status

---

provider/azure/azure.go
provider/azure/azure_private_dns.go
provider/azure/azure_privatedns_test.go
provider/azure/azure_test.go

This PR aims to add IPv6 AAAA support on Azure DNS providers (both public and private DNS zones).
**Checklist**

feat(azure): add AAAA records support

---

docs/sources/ingress.md
docs/sources/service.md
docs/sources/sources.md
mkdocs.yml
source/service.go

Adds reference documentation for the service source.
**Checklist**

Document the Service source

---

provider/gandi/gandi.go
provider/gandi/gandi_test.go

This refactors the gandi provider tests to make them more robust, easier to extend, and hopefully more readable
This also includes two minor fixes : 
- the conversion of an endpoint DNSName to `@` for apex domains is not robust (as pointed out [here](https://github.com/kubernetes-sigs/external-dns/pull/3855#discussion_r1291912657) - a test case was added to cover this)
- the TTL field is not filled when fetching endpoints (discovered when rewriting the tests)
This relates to #3855 - I am trying to make changes to the Gandi provider more reliable and reduce noise on improvement/feature PRs
**Checklist**

Gandi provider: refactor tests to be more readable, robusts, and extensible; and minor fixes

---

provider/aws/aws.go
provider/aws/aws_test.go
provider/inmemory/inmemory.go
registry/txt.go
registry/txt_test.go

Causes AWS Alias records to be represented in the planner as records of type A.
This resolves a conflicting interaction between #3747 (which resolves conflicts between CNAME records and records of any other type with the same domain) and #3605 (which gives the planner both CNAME and AAAA records for AWS aliases). 
**Checklist**

Represent AWS Alias records as record type A

---

docs/sources/gateway.md
docs/sources/sources.md
mkdocs.yml

Documents the various Gateway API sources.
**Checklist**

Document the Gateway sources

---

controller/controller.go
main.go
pkg/apis/externaldns/types.go
plan/plan.go
plan/plan_test.go
registry/dynamodb.go
registry/dynamodb_test.go
registry/txt.go
registry/txt_test.go

Adds an `--exclude-record-types` flag. This allows for easier removal from the default `--manage-record-types` set.
**Checklist**

Add --exclude-record-types flag

---

go.mod
go.sum
pkg/rfc2317/arpa.go
pkg/rfc2317/arpa_test.go
provider/infoblox/infoblox.go

Eliminate the dependency on dnscontrol.  The infoblox provider imports dnscontrol solely to use one function.  go.mod lists a version of dnscontrol that was recalled.  
Fixes #3887
**Checklist**

Remove dependency on dnscontrol

---

docs/annotations/annotations.md
docs/sources/service.md
source/service.go
source/service_test.go

If a domain name comes from a `external-dns.alpha.kubernetes.io/internal-hostname` annotation on a non-headless ClusterIP Service, publish the Service's ClusterIP.
**Checklist**

Use ServiceIP for ClusterIP Services with internal-hostname annotation

---

docs/tutorials/webhook-provider.md
main.go
pkg/apis/externaldns/types.go

Adds a `--webhook-server` flag for running an arbitrary provider as a webhook. This will be helpful in testing
Helm chart support for webhooks and the webhook provider itself.
**Checklist**

Add --webhook-server flag for running as a webhook server

---

source/ambassador_host.go
source/contour_httpproxy.go
source/f5_virtualserver.go
source/gateway.go
source/gloo_proxy.go
source/ingress.go
source/istio_gateway.go
source/istio_virtualservice.go
source/kong_tcpingress.go
source/node.go
source/openshift_route.go
source/service.go
source/skipper_routegroup.go
source/source.go
source/source_test.go
source/traefik_proxy.go

Refactors getTTLFromAnnotations() to not return an error. The only correct thing to do is to log the parsing failure and continue with a default TTL.
**Checklist**

Refactor getTTLFromAnnotations() to not return error

---

docs/tutorials/azure.md

Documentation for granting permissions suggests there are three ways configure the access but lists four, fix that to prevent any confusion.
Also some minor typo fixes.
Fixes to Azure setup documentation
No related issues (seemed too trivial)
**Checklist**

document there are four ways of configuring access

---

provider/azure/azure.go
provider/azure/azure_private_dns.go
provider/azure/config.go

The old implementation allowed use of alternative Azure Clouds (Azure China, Azure Gov etc.)
With the changes to the new SDK, the other clouds were partially implemented : the authentication to the other clouds was working but the calls to the management endpoints to create/delete records was only targeting public Azure Cloud.
This PR aims to fix this bug.
To test it, an access to an sovereign cloud is required. The requestor who filled the issue has access to one and validated the fix.
Fixes #3927
**Checklist**

fix(azure): sovereign cloud support

---

main.go
pkg/apis/externaldns/types.go

Remove no-longer-needed testing mode.
**Checklist**

Remove the --run-aws-provider-as-webhook flag

---

provider/linode/linode.go
provider/linode/linode_test.go

Adds support for NS records in the Linode provider
**Checklist**

Add support for NS records in the Linode provider

---

endpoint/crypto.go
endpoint/labels.go
registry/txt.go
registry/txt_test.go

This PR addresses the issue of the current behavior being incompatible with Route53 when using TXT registry with encryption enabled. AWS requires the `Delete` change request to be called with the exact same record set that is currently present in Route53. However, this is not happening due to the following reasons:
1. The [generateTXTRecord](https://github.com/kubernetes-sigs/external-dns/blob/bd8658e89a1fe3e255621103091717b20f8312b8/registry/txt.go#L196) function generates both old and new format TXT records, each encrypted with a new random nonce.
2. The [Records()](https://github.com/kubernetes-sigs/external-dns/blob/bd8658e89a1fe3e255621103091717b20f8312b8/registry/txt.go#L146C22-L146C22) function stores only one of these records in the `labelsMap` when iterating through the TXT …

[TXT Registry] Make the nonce stable when generating delete records

---

OWNERS

This PR adds `mloiseleur` to the reviewer group.
/cc @szuecs for approval

Add mloiseleur to reviewer group

---

docs/tutorials/scaleway.md
provider/scaleway/scaleway.go
provider/scaleway/scaleway_test.go

Update Scaleway provider to support supplying the credentials through config files. A config file can be read from a Secret mounted as a Volume inside the Pod.
**Checklist**

Update Scaleway provider to support config files

---

source/ambassador_host.go

Hello!
I would like to submit a PR to add support for external IPs in Ambassador Host resources.
Most of the code has been shamelessly copied from the `Service` source implementation (https://github.com/kubernetes-sigs/external-dns/blob/master/source/service.go#L591).
I couldn't add any tests as the ones I currently see for Ambassador are rather basic (e.g. making sure the annotation format is correct) while in my case I would need to mock the Kubernetes API and I'm not sure how to do it -- happy to give it a try if somebody can guide me a bit.
Note this fixes #3733.
Let me know if anything is missing or if you have improvement ideas.
Thanks,
Fred

feat: add support for external IP in ambassador host source

---

README.md

Document webhook providers in the README.
**Checklist**

docs: Inform the situation on webhook provider

---

README.md

Adds the reference to https://github.com/muhlba91/external-dns-provider-adguard to support [AdguardHome](https://github.com/AdguardTeam/AdGuardHome).
**Checklist**

docs: add reference to adguard webhook provider

---

Makefile

Add the label `org.opencontainers.image.source="https://github.com/kubernetes-sigs/external-dns"` to the container image. 
This helps for example Renovate to add Release Notes to PRs that update the container image.
https://docs.renovatebot.com/modules/datasource/docker/
Fixes #ISSUE (No issue created)
**Checklist**

Add org.opencontainers.image.source label to container image

---

docs/tutorials/rfc2136.md
pkg/apis/externaldns/types.go
provider/rfc2136/rfc2136.go
provider/rfc2136/rfc2136_test.go

Allow to set multiple zones for RFC2136 provider
Fixes #1865
**Checklist**

RFC2136: Allow multiple zones

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/docs.yml
.github/workflows/json-yaml-validate.yml
.github/workflows/lint-test-chart.yaml
.github/workflows/lint.yaml
.github/workflows/release-chart.yaml
.github/workflows/staging-image-tester.yml

This PR updated the Helm chart GitHub workflows to fix an issue with a sub-component action. It also sets an explicit SHA for all checkout actions as if this isn't done it breaks the Helm chart actions when Dependabot runs.
**Checklist**

chore(chart): Updated GH workflows

---

registry/dynamodb.go
registry/dynamodb_test.go

In the DynamoDB Registry, fix the `chunk` variable when the number of statements is over 25.
The test is a bit verbose, but I figured that keeping the logic of a loop out the test case was better than a shorter test. 
Fixes #3921
**Checklist**

fix: dynamodb registry when statements over 25

---

go.mod
go.sum
pkg/apis/externaldns/types.go

Small bump to /v2 format, so dependabot recognizes the next releases.
**Checklist**

chore: Bump kingpin/v2 dep

---

docs/annotations/annotations.md
source/kong_tcpingress.go
source/kong_tcpingress_test.go
source/store.go
source/traefik_proxy.go
source/traefik_proxy_test.go

Makes the `--ignore-hostname-annotation` flag more consistent by making it affect the Kong and Traefik sources as well.
The Pod source then becomes the only source that isn't affected by the flag. This is because the Pod source has  no other source of hostnames.
**Checklist**

Make --ignore-hostname-annotation flag more consistent

---

provider/google/google.go
source/crd_test.go

This PR fixes the google provider to add a trailing dot to SRV records, as required by their documentation (https://cloud.google.com/dns/docs/reference/json-record)
**Checklist**

fix(google): ensure trailing dot for SRV records

---

source/contour_httpproxy.go
source/contour_httpproxy_test.go

According to the contour design docs: [conflict](https://github.com/projectcontour/contour/blob/main/design/httpproxy-conflict.md), [status](https://github.com/projectcontour/contour/blob/main/design/httpproxy-status-conditions.md)
The status field can be invalid in many different situations, even not directly related to the httpProxy definition.
Also, most of them are not fatal and contour will try to serve traffic by other rules, even if one of the routing paths is broken.
As an example we currently working on defining an API gateway based on HTTPProxy, and a situation can happen when the service underlines gateway, can be deleted or renamed accidentally (that situation will lead to downtime because of external-dns filter out "invalid" definitions and drop our DNS record …

fix(httpProxy): drop status==valid filter

---

docs/tutorials/infoblox.md

The `--infoblox-view=` argument was missing in Infoblox's documentation page. As others have noted displaying this option would be helpful to the community.
Relates to #831  
**Checklist**

doc: added --infoblox-view argument to Infoblox documentation

---

provider/scaleway/scaleway.go
provider/scaleway/scaleway_test.go

fix issue [#4032](https://github.com/kubernetes-sigs/external-dns/issues/4038) and regression of PR https://github.com/kubernetes-sigs/external-dns/pull/4002

fix: regression on scaleway provider in 0.14.0

---

provider/webhook/httpapi.go
provider/webhook/httpapi_test.go

Make webhook HTTPApi usable outside of the package. 
Right now the only option to use this is to call StartHTTPApi, which unfortunately does a bit too much for an external use.
It would be convenient to have access to the handlers and the provider key in the webhookserver object, so one can set it up on their own.
Reusing this in webhook plugins would also allow to spot issues during upgrade (or not even be affected at all if it's endpoint specific as the API is maintained within external-dns)
**Checklist**

feat: make webhook httpapi reusable

---

source/skipper_routegroup.go

On IPv6 based clusters the `InClusterConfig` (from client-go) will correctly produce a valid URL for an IPv6 IP address [with the required `[]` surrounding the IPv6 address](https://github.com/kubernetes/client-go/blob/84a6fe7e4032ae1b8bc03b5208e771c5f7103549/rest/config.go#L536).
However, in the routegroup client the host is parsed via `url.Parse` and the `url.Hostname()` method returns the IPv6 Address _without_ the `[]` leading to the following error:
```
Get \"https://fd6d:ef2a:acf6::1/apis/zalando.org/v1/routegroups\": dial tcp: lookup fd6d:ef2a:acf6:: no such host"
```
To work around this, we use `u.Host` and trim away the already known port `:443`.
Fixes #ISSUE
**Checklist**

Make routegroup client IPv6 compatible

---

README.md

doc: fix link to ionos webhook provider

---

main.go
provider/webhook/api/httpapi.go
provider/webhook/api/httpapi_test.go
provider/webhook/webhook.go
provider/webhook/webhook_test.go

This moves the webhook httpapi into its own package to improve reusability.
Main reason to do that is to avoid side effects from webhook.go which includes an init() func that will be called package-wide.
**Checklist**

webhook: Move httpapi into own package

---

README.md

Adds a link to a [netcup webhook provider](https://github.com/mrueg/external-dns-netcup-webhook) 
**Checklist**

doc: Add netcup webhook provider

---

provider/aws/aws.go

include il-central-1 referenced https://docs.aws.amazon.com/general/latest/gr/elb.html in `canonicalHostedZones`
Fixes #4064
**Checklist**

update to add il-central-1

---

charts/external-dns/CHANGELOG.md
charts/external-dns/templates/deployment.yaml

This PR changes the the input of the config checksum which triggers the reload.
On master branch, the whole configmap/secret checksum is included as checksum input. The configmap contains labels which includes the helm chart version. Each new helm chart version forces a pod restart which is not always necessary. 
By define a finer input for the pod annotation checksum, unnecessary pod restarts can be avoided. 
**Checklist**

helm: Avoid unnecessary pod restart on each helm chart version

---

provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_test.go

Collect zone errors when submitting changes in the Cloudflare provider so that they are included in Prometheus metrics. I copied the approach used in the AWS provider.
I opted *not* to capture "failed to find previous record" errors as they aren't exactly registry errors.
Fixes #4081
**Checklist**

fix: include cloudflare error in metrics and logs

---

source/gateway.go
source/gateway_grpcroute_test.go
source/gateway_httproute_test.go
source/gateway_tcproute_test.go
source/gateway_test.go
source/gateway_tlsroute_test.go
source/gateway_udproute_test.go

This tidies up some loose ends from the Gateway API upgrade from v0.7.1 to v1.0.0 and brings the wildcard matching into compliance with the spec. Originally, the spec was like TLS certificates where a wildcard would only match a single subdomain level. It changed in v0.5.0 to be a multi-level matcher.
https://github.com/kubernetes-sigs/gateway-api/pull/1173
**Checklist**

gateway-api: fix wildcard matching

---

docs/tutorials/traefik-proxy.md
main.go
pkg/apis/externaldns/types.go
source/store.go
source/traefik_proxy.go
source/traefik_proxy_test.go

Traefik 3.0 removes the legacy API group traefik.containo.us and earlier versions may be installed without the legacy API group setup.
This PR adds two flags, one to disable the legacy API group and one to disable the new API group. The default behavior of the traefik-proxy source is not changed.
Fixes #4075
**Checklist**

Fix timeout for traefik-proxy source

---

plan/plan.go
provider/aws/aws_test.go

CompareBoolean() is no more used now
cf: 5affab056180762e2045a7b96f335e254d14d3d7
escapeAWSRecords() is no more used
cf: a7992331251983e9566c0dcc817b75822a80dfab
Remove dead code
**Checklist**

fix: remove useless functions

---

source/ambassador_host.go

Following PR https://github.com/kubernetes-sigs/external-dns/pull/3734, external-dns is now able to use Ambassador service external IPs when creating DNS records.
However, it is configured to resolve LB hostnames by default, which was not the case before.
Purpose of this PR is to restore the previous behavior - and create CNAME to LB hostname instead.

fix(ambassador): don't resolve LB hostname

---

docs/tutorials/azure.md

Adding userAssignedIdentityID with clientId of the kubelet identity in azure.json solves the problem with multiple parallel node pool identities - issue #4132
Documentation update: Adding userAssignedIdentityID with clientId of the kubelet identity in azure.json
Fixes #4132
**Checklist**

doc(azure): shows how to use userAssignedIdentityID with clientId in azure.json

---

docs/faq.md
provider/webhook/webhook.go

This adds requests metrics and renames the metric names to fit best practices.
**Checklist**

webhook: Fix metric name and add request gauges

---

docs/tutorials/istio.md
source/istio_gateway.go
source/istio_gateway_test.go
source/istio_virtualservice.go
source/istio_virtualservice_test.go

✨ Add support for ExternalIPs in Istio Gateway and VirtualService 
ℹ️ This commit extends Istio Gateway and VirtualService resources to support ExternalIPs. 
The changes include:
- Checking if service has ExternalIPs defined
- If yes, adding them to the list of targets
- If not, continuing with the existing process
👌 Now you can have your Istio resources use `externalIPs` too! 🎉
Not to be `ip`-percritical, but don't we all love an `ip`grade! 🎈
Fixes #1718 
Fixes https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3490
Reason being is that aws load balancer controller does not support creating ALBs on service type resources and if provisioned using e.g. terraform, will also *not* add any status fields to the service.
To still be able to point to targets …

fix(istio): support for ExternalIPs in Istio resources

---

provider/exoscale/exoscale.go
provider/exoscale/exoscale_test.go

This PR removes some redundant API calls from exoscale provider implementation.
**Checklist**

Exoscale provider optimization

---

provider/godaddy/client.go

One line fix of wrong rate limiter configuration.
I added this in the previous implementation:
https://github.com/kubernetes-sigs/external-dns/pull/3427
And sometime after adding new domains and ingresses, we hit some strange issues, with missing updates.
go playground: https://go.dev/play/p/CcqziJQsor5
**Checklist**

fix: godaddy - rate limiter add one token every second

---

charts/external-dns/CHANGELOG.md
charts/external-dns/README.md
charts/external-dns/values.schema.json
charts/external-dns/values.yaml
docs/tutorials/azure.md

This PR deprecates the `secretConfiguration` Helm chart value.
**Checklist**

chore(chart): Deprecated secretConfiguration

---

charts/external-dns/CHANGELOG.md
charts/external-dns/Chart.yaml
charts/external-dns/README.md

This PR release the helm chart for `v0.14.0`.
Fixes #4072
**Checklist**

feat(helm-chart): Released chart for v0.14.0

---

charts/external-dns/CHANGELOG.md
charts/external-dns/Chart.yaml

This PR fixes the missing `v` prefix from the CHANGELOG entry breaking the `v1.14.0` Helm chart release from #4073.
**Checklist**

chore(chart): Fixed chart changelog

---

provider/pdns/pdns.go
provider/pdns/pdns_test.go

Fixes: https://github.com/kubernetes-sigs/external-dns/issues/3970
The PR https://github.com/kubernetes-sigs/external-dns/pull/3338 introduces a broken behavior, where a CNAME is converted to an ALIAS if the **target** doesn't match its zone, which doesn't make sense in terms of DNS. The scenario that @epollia describes, is about the limitation of DNS, that limits the use of CNAMEs to subdomains only. Only A and AAAA are allowed for the apex (simply speaking). For this reason, pdns supports the custom ALIAS record type, which resolves the target on the server instead of the client. 
This change ensures the auto-conversion of CNAME to ALIAS on the domain apex, and removes the superflous target dependant conversion.
**Checklist**

fix(pdns): provider implicitly changes CNAME to ALIAS

---

charts/external-dns/CHANGELOG.md
charts/external-dns/Chart.yaml
charts/external-dns/README.md
charts/external-dns/templates/deployment.yaml

v1.14.0 added the ability to deploy a webhook container, but it fails to install due to a character limit. Relevant install log:
```
Helm upgrade failed for release adguard-home/adguard-home-external-dns with chart external-dns@1.14.0: cannot patch "adguard-home-external-dns" with kind Deployment: Deployment.apps "adguard-home-external-dns" is invalid: spec.template.spec.containers[1].ports[1].name: Invalid value: "http-webhook-metrics": must be no more than 15 characters
```
This PR renames `http-webhook-metrics` to `webhook-metrics` to fix this error.
Fixes #4174 
**Checklist**

fix(chart): Fix webhook install failure

---

controller/controller.go
provider/aws/aws.go
provider/provider.go

fix: provide possibility to have a soft error mode
fixes #4067 
closes https://github.com/kubernetes-sigs/external-dns/pull/4147

fix: provide possibility to have a soft error mode

---

charts/external-dns/CHANGELOG.md
charts/external-dns/Chart.yaml
charts/external-dns/README.md
charts/external-dns/templates/deployment.yaml

Regression introduced in https://github.com/kubernetes-sigs/external-dns/commit/e67a0a1e604773f27014bafded45c4e601f67fe8#diff-6ad1b3106470e68ead8d0102e9c4db266f63a9ff374104ddfc5c284f7a1945eb
Fixes #ISSUE
**Checklist**

[helm] Allow tpl in provider again

---

charts/external-dns/CHANGELOG.md
charts/external-dns/Chart.yaml
charts/external-dns/README.md
charts/external-dns/templates/deployment.yaml
charts/external-dns/templates/serviceaccount.yaml

This PR releases the Helm chart with a fix for an issue with the service account automount token implementation, it also releases the changes made in the following PRs.
- #4202
- #4205
**Checklist**

chore: Released chart v1.14.3

---

provider/oci/oci.go

With the addition of #3009. Upgrading to external-dns 0.14.0 can lead to excessive pod restarts and eventually an unrecoverable state of throttling.  
#4166 provides the ability to restore previous functionality by introducing the concept of SoftError to avoid potential throttling from routine network interruptions.
This PR applies the concept of SoftError to the OCI Provider.
**Checklist**

Update the OCI Provider to incorporate SoftError to avoid CrashLoopBackoff

---

charts/external-dns/CHANGELOG.md
charts/external-dns/README.md
charts/external-dns/templates/deployment.yaml
charts/external-dns/values.yaml

Helm supports setting dnsPolicy, but there was no way to set dnsConfig, thus making it impossible to set custom nameserver for the pod.
**Checklist**

feat: allow setting dnsConfig

---

docs/tutorials/rfc2136.md
main.go
pkg/apis/externaldns/types.go
provider/rfc2136/rfc2136.go
provider/rfc2136/rfc2136_test.go

*  Reuse the existing TLS options.
*  Add two new flags, one to enable DNS-over-TLS, and the second to disable cert checks for DNS-over-TLS.
*  Factor out the connection code so that it can be shared between the zone transfer and the updates. If TLS was requested, it will be used for both.
*  RFC9013 requires TLS 1.3 or later, and an ALPN negotiation of "dot".
RFC2136: Add support for DNS-over-TLS
*  Reuse the existing TLS options.
*  Add two new flags, one to enable DNS-over-TLS, and the second to disable cert checks for DNS-over-TLS.
*  Factor out the connection code so that it can be shared between the zone transfer and the updates. If TLS was requested, it will be used for both.
*  RFC9013 requires TLS 1.3 or later, and an ALPN negotiation of "dot".
**Checklist**

RFC2136: Add support for DNS-over-TLS

---

provider/aws/aws.go
provider/aws/aws_test.go

This PR attempts to fix https://github.com/kubernetes-sigs/external-dns/issues/4026 where creating AWS alias records fail on v0.14.0. My first time looking at external-dns source code. I think the failure only occurs when `external-dns.alpha.kubernetes.io/alias: 'true' ` 
The AdjustEndpoints method currently removes the alias property from records that aren't of type A. Although https://github.com/kubernetes-sigs/external-dns/pull/3910/files changes Alias records to be represented as A records, at the point the alias deletion occurs the endpoint is still a CNAME, and the alias property is deleted. A non-Alias record A is then attempted to be created and fails at the Route53 API with `error: InvalidChangeBatch: [Invalid Resource Record: 'FATAL problem: …

fix(aws): allow alias records to be created when using the alias annotation

---

source/ingress_test.go
source/service.go
source/service_test.go
source/source.go

From Services, don't try to create records for invalid endpoints, e.g. when they contain a label that's too long (ref: #3017)
Add a test to make sure Ingresses behave as expected, too.
**Checklist**

 fix(service): omit nil endpoints and prefer endpointsForHostname()

---

OWNERS

Update maintainers
1. Move @njuettner to emeritus_approvers. Recent review activity has been extremely low.
2. Move @mloiseleur to approvers.
**Checklist**
Linked PRs:
- https://github.com/kubernetes/k8s.io/pull/6541
- https://github.com/kubernetes/test-infra/pull/32191

chore: update maintainers

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/docs.yml
.github/workflows/lint.yaml
.github/workflows/staging-image-tester.yml
cloudbuild.yaml
docs/contributing/getting-started.md
go.mod
go.sum

This update external dns to go 1.22.
Inspired by #3922 
It also upgrade `github.com/exoscale/egoscale` to `v0.102.3`, since current version has a checksum issue on `go mod tidy`.
**Checklist**

chore: upgrade ExternalDNS to go 1.22

---

charts/external-dns/CHANGELOG.md
charts/external-dns/crds/dnsendpoint.yaml

Taken from https://github.com/kubernetes-sigs/external-dns/tree/master/docs/contributing/crd-source
Fixes: https://github.com/kubernetes-sigs/external-dns/issues/2640
**Checklist**

Add `dnsendpoint` CRD to Helm chart

---

charts/external-dns/CHANGELOG.md
charts/external-dns/Chart.yaml
charts/external-dns/README.md

This PR updates the Helm chart to use ExternalDNS [0.14.1](https://github.com/kubernetes-sigs/external-dns/releases/tag/v0.14.1).
This release also includes the following changes.
- #4265
- #4322
Fixes #4333
**Checklist**

chore(chart): Released chart for v0.14.1

---

README.md

Inform on the current plan for providers in main README page.
Part of #4347
cc @Raffo @szuecs

doc: advertise current plan on providers

---

endpoint/endpoint.go
endpoint/endpoint_test.go

Fixes #4326 
Support Short and Long IPv6 addresses to be recognized as the same.
**Checklist**

Fix(ipv6):  support ipv6 shortener and expander equal

---

provider/webhook/webhook.go
provider/webhook/webhook_test.go

#4166 introduced the `SoftError` as a way for providers to signal that an error is transient and should not lead to the controller bailing out of execution, to somewhat mitigate the changes made in #3009.
For some in-tree providers (AWS, Azure, and Oracle Cloud Infrastructure), `SoftError` support has already been implemented. This PR lets the `WebhookProvider` return `SoftError`s for any HTTP Response with a status code >= 500  returned by webhook providers, in order to implement this for out-of-tree providers as well.
As 5xx status codes indicate a temporary problem on the provider side, it seems fitting to me that any response with such a code should be handled as a `SoftError`. This is in line with the definition of the `SoftError`, which "is meant for error …

feat(WebhookProvider): Let WebhookProvider return `SoftError` on response status codes >= 500

---

provider/webhook/webhook.go

As requested in #4319, I extracted this fix from the change set there.
The wrong endpoint gauge is used in the webhook provider once in the `AdjustEndpoints()` function. Seems to come from a copy-paste mistake, and messes up the metrics a little.
Opening this PR now for completeness, however depending on which PR gets merged first, the other one needs to be rebased, I guess.
**Checklist**
- ~~Unit tests updated~~ not needed
- ~~End user documentation updated~~ not needed

Webhook provider: Use correct error gauge in `AdjustEndpoints()` func

---

charts/external-dns/CHANGELOG.md
charts/external-dns/README.md
charts/external-dns/templates/deployment.yaml
charts/external-dns/values.yaml

This Pull Request adds the excludeDomains argument into the template to enable the ability to easily exclude domains without passing additional extra arguments and a more readable list consistent with the domain filtering list that can be set in the values for the chart. 
**Checklist**

Add exclude domains value in Chart

---

docs/tutorials/aws.md

Fixes the documentation for the [aws](https://kubernetes-sigs.github.io/external-dns/v0.14.1/tutorials/aws) tutorial.
Adding the `ACCESS_KEY_ID` env when creating static credentials, to reference it later in the  cleanup section. 
I've also renamed the NODE_ID to ZONE_ID when deleting the hosted zone, to reflect the var name used during the creation of the hosted zone.
**Checklist**

docs(aws): fix typo and upgrade cleanup flow

---

docs/tutorials/gke.md

Updating the GKE workload identity page as per #4362, as the way it works has changed in the past 2 weeks
I have also made the decision to move the workload identity section higher up in the documentation and below is my logic
* Google _strongly_ recommend users do not use the default service account, or node service accounts
* Google has[ published a flow chart on this](https://cloud.google.com/docs/authentication#auth-decision-tree) where they recommend they (users) use Workload identity
Fixes #4362 
**Checklist**
---
Commits signed, and I should have an existing CLA with the CNCF

docs(gke): detail how to configure workload identity

---

.github/workflows/ci.yaml
.github/workflows/codeql-analysis.yaml
.github/workflows/docs.yaml
.github/workflows/lint.yaml
.github/workflows/staging-image-tester.yaml
cloudbuild.yaml
go.mod

Upgrade go lang from 1.22 to 1.22.2
It's fixing some CVEs and required by latest version of IBM sdk:
```shell
go: github.com/IBM/networking-go-sdk@v0.46.1 requires go >= 1.22.2; switching to go1.22.2
```
=> It will fix dependabot PR like [this one](https://github.com/kubernetes-sigs/external-dns/pull/4413).

chore: upgrade ExternalDNS to go 1.22.2

---

docs/tutorials/dnsimple.md
provider/dnsimple/dnsimple.go
provider/dnsimple/dnsimple_test.go

This _Pull Request_ introduces the following environment variables for overriding data retrieved from the DNSimple API. This is needed when using _User API_ DNSimple tokens (as opposed to _Account API_ DNSimple tokens) as this data cannot be accessed with a _User API_ token:
- `DNSIMPLE_ACCOUNT_ID`: The DNSimple account which owns the DNS records to be updated
- `DNSIMPLE_ZONES`: A comma separated list of DNS Zones in DNSimple which External-DNS will be allowed to manipulate
Fixes #4273
**Checklist**

feat(DNSimple): User API tokens

---

plan/plan_test.go

add test case for #4059
It does not reproduce no idea why

test: detect no change necessary with provider specific config

---

charts/external-dns/README.md
charts/external-dns/README.md.gotmpl
docs/tutorials/akamai-edgedns.md
docs/tutorials/aws.md
docs/tutorials/cloudflare.md
docs/tutorials/digitalocean.md
docs/tutorials/godaddy.md
docs/tutorials/ns1.md
docs/tutorials/plural.md
docs/tutorials/vultr.md

Updates the Helm chart documentation for ExternalDNS to include a detailed example of how to configure ExternalDNS with the CloudFlare provider. 
Fixes #4396 
**Checklist**

docs: add setup example with helm chart on some providers

---

controller/controller_test.go

test: controller run() should do somthing and successfully shutdown

test: controller run() and successfully shutdown

---

docs/tutorials/cloudflare.md

Fix syntax on the creation of secret and updating keys 
Fixes #ISSUE
**Checklist**

fix syntax on cloudflare externalDNS

---

charts/external-dns/CHANGELOG.md
charts/external-dns/README.md
charts/external-dns/templates/deployment.yaml
charts/external-dns/templates/service.yaml
charts/external-dns/values.yaml

Introduced an option to either create the Service resource or not, with the default behavior set to create. 
Added the capability to include extra containers in the deployment.
Fixes #4280 
**Checklist**

chore(chart): Adding extra containers 

---

provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_test.go

Updates the cloudflare provider to raise SoftErrors when rate limits are breached interacting with the Cloudflare API
Fixes #4434 
**Checklist**

fix: soft error on cloudflare rate limits

---

docs/tutorials/rfc2136.md

Fixed headings around "Secure Updates" .
Also fixed a couple of whitespace issues.
Fixes #ISSUE
**Checklist**

Fix headings, whitespace

---

provider/webhook/webhook.go

This PR changes a logline that was merged at the time in which we implemented the webhook functionality. This was originally called "plugin" and it looks like a logline mentioning the old name is still in the codebase. This PR renames that to webhook.
**Checklist**

fix logline mentioning plugin api

---

docs/tutorials/gke.md

Fix markdown errors and make terraform config more secure by allowing to opt it external dns per zone and not grant project level admin
Fixes #ISSUE
**Checklist**

docs: lint gke docs + make terraform config more secure

---

docs/tutorials/cloudflare.md

I have added more documentation of how to use c´the cloudflare provider, with api tokens.
**Checklist**

changed documentation to include more details description when using API Tokens

---

endpoint/endpoint_test.go

Based on the conversation during #4296 this is an addition to clarify that A records cannot live with CNAME records with the same hostnames. Since the function that was developed is not expected to validate the type of records, this unit test was splitted into 2 different Record types to avoid any type of possible confusion in the future.
Fixes #4339
**Checklist**

fix: add clarification to endpoint unit tests

---

docs/tutorials/webhook-provider.md
provider/webhook/webhook_test.go
source/source.go

Fixes https://github.com/kubernetes-sigs/external-dns/issues/4367
This PR allows to forward specific implementations to webhook implementations so that they can make use of them. 
@hans-m-song is this what you expected?
**Checklist**

feat(webhooks): pass webhook-* annotations to webhook providers

---

source/traefik_proxy.go

Fixed a nil pointer exception if using traefik v3.
The legacy CRDs are no longer shipped.
Starting external-dns with legacy enabled -> timeout
Starting external-dns with legacy disabled -> Nil pointer exception. Fixed by this PR.
error message without:
```
time="2024-05-25T09:06:10Z" level=info msg="config: {APIServerURL: KubeConfig: RequestTimeout:30s DefaultTargets:] GlooNamespaces:[gloo-system] SkipperRouteGroupVersion:zalando.org/v1 Sources:[service ingress traefik-proxy] Namespace: AnnotationFilter: LabelFilter: IngressClassNames:] FQDNTemplate: CombineFQDNAndAnnotation:false IgnoreHostnameAnnotation:false IgnoreIngressTLSSpec:false IgnoreIngressRulesSpec:false GatewayNamespace: GatewayLabelFilter: Compatibility: PublishInternal:false PublishHostIP:false …
```

fix(traefik): Nil pointer exception if legacy traefik is disabled

---

pkg/apis/externaldns/types.go

This PR drops the experimental notice in the webhook CLI flags as they are these days widely used.
Fixes #ISSUE
**Checklist**

Drop experimental notice in webhook flags

---

docs/tutorials/coredns.md
provider/coredns/coredns.go
provider/coredns/coredns_test.go

Currently, the CoreDNS provider only work with no etcd authentication.
This PR adds etcd user/password authentication for CoreDNS provider by exposing `ETCD_USERNAME` and `ETCD_PASSWORD` environment variables.
Fixes #2616
**Checklist**

feat(coredns): etcd authentication

---

README.md

This add external-dns-infoblox-webhook implementation to the list of webhook providers
**Checklist**

Add Infoblox webhook provider

---

.github/workflows/ci.yaml
.github/workflows/codeql-analysis.yaml
.github/workflows/docs.yaml
.github/workflows/lint.yaml
.github/workflows/staging-image-tester.yaml
cloudbuild.yaml
go.mod

This PR upgrades the project to Go 1.22.4. This is needed to be able to update one of the dependencies (IBM provider) that requires go 1.22.3 at the minimum.
**Checklist**

Update to Go 1.22.4

---

docs/tutorials/coredns.md

As reported in #4537, HTTPS is supported for connections to the ETCD cluster, but it is not documented.
I have added a small sentence in order to let others know that it is already there, and what variables to use to configure it.
Fixes #4537 
**Checklist**

Add documentation about etcd HTTPS for CoreDNS provider

---

charts/external-dns/CHANGELOG.md
charts/external-dns/Chart.yaml
charts/external-dns/README.md
charts/external-dns/README.md.gotmpl
charts/external-dns/crds/dnsendpoint.yaml
charts/external-dns/templates/deployment.yaml
charts/external-dns/templates/servicemonitor.yaml

This PR releases the Helm chart for [`v0.14.2`](https://github.com/kubernetes-sigs/external-dns/releases/tag/v0.14.2).
Fixes #4482
**Checklist**

chore(chart): Released chart for v0.14.2

---

provider/cloudflare/cloudflare.go

This change cleans the Cloudflare API Token that was read from file. This is useful if the file contains spaces or newlines.
**Checklist**
(both aspects not needed)

fix(cloudflare): trimSpace on token read from file

---

source/gateway_grpcroute.go
source/gateway_grpcroute_test.go

Updates GRPCRoute client to use v1 stable (as GRPCRoute has graduated to stable)
**Checklist**
**Notes**
We have dog-fooded this change and it works as expected.

feat!: update GRPCRoute client from v1alpha2 to stable v1

---

docs/annotations/annotations.md

Setting multiple hostnames through this annotation has been possible since #256, but this behavior has not been sufficiently documented before.
**Checklist**
- ~Unit tests updated~ (N/A)

docs(annotations): note how to set multiple hostnames

---

docs/tutorials/gateway-api.md
source/gateway.go
source/gateway_grpcroute_test.go
source/gateway_httproute.go
source/gateway_httproute_test.go
source/gateway_tcproute_test.go
source/gateway_tlsroute_test.go
source/gateway_udproute_test.go

This reverts Kubernetes API interactions for Gateway and HTTPRoute objects from APIVersion v1 to v1beta1.
Fixes #4366
**Checklist**

Gateway API: Revert Gateway and HTTPRoute objects from v1 to v1beta1

---

docs/tutorials/azure-private-dns.md

annotations should be inside the metadata object.

azure-private-dns: Fix LoadBalancer example

---

docs/tutorials/aws.md

The Helm section includes templates files that aren't needed as those values can all be generated from the values.yaml file. It seems that the current documentation also missed the role arn annotation so it was added as well.
**Checklist**

AWS: Change documentation to use Helm values

---

controller/controller.go
controller/controller_test.go
docs/tutorials/aws.md

In the command line arguments, we see `min-event-sync-interval` as "The minimum interval between two consecutive synchronizations triggered from kubernetes events"
In the code, it actually acts a different way.
It imposes a certain delay between syncs.
In particular, when multiple calls to ScheduleOnce are done, it will systematically push back the next run by the min interval delay.
While this is compliant with the "minimum delay between 2 consecutive synchronizations", it has side-effects that may introduce large delays.
In particular, when trying to fine-tune external-dns to match the provider rate-limits.
In this case, it may be interesting to restrict the rate of reconciling actions happening by having a high `min-event-sync-interval`, while keeping a low latency for …

Improve MinEventInterval compliance with docs

---

controller/controller.go
controller/controller_test.go
docs/rate-limits.md
docs/tutorials/aws.md
endpoint/domain_filter.go
main.go
mkdocs.yml
pkg/apis/externaldns/types.go
provider/aws/aws.go
provider/aws/aws_test.go
provider/cached_provider.go
provider/cached_provider_test.go
provider/inmemory/inmemory.go
provider/provider.go
provider/webhook/api/httpapi_test.go
provider/webhook/webhook.go
registry/aws_sd_registry.go
registry/dynamodb.go
registry/noop.go
registry/registry.go
registry/txt.go

In the current implementation, DNS providers are called to list all records on every loop. This is expensive in terms of number of requests to the provider and may result in being rate limited, as reported in 1293 and 3397.
In our case, we have approximately 20,000 records in our AWS Hosted Zone. The ListResourceRecordSets API call allows a maximum of 300 items per call. That requires 67 API calls per external-dns deployment during every sync period
With this, we introduce an optional generic caching mechanism at the provider level, that re-uses the latest known list of records for a given time.
This prevents from expensive Provider calls to list all records for each object modification that does not change the actual record (annotations, statuses, ingress routing, ...) …

Add provider cache

---

charts/external-dns/CHANGELOG.md
charts/external-dns/templates/deployment.yaml

The resource limits set by the user when leveraging the webhook sidecar should be respected and implemented when they are passed via helm values. This change alters the deployment template to use those limits if they are set in the values. I believe this was intended to work when it was first implemented but never had the supporting logic added to the deployment template.
I didn't see and issue for this (surprisingly).
**Checklist**

fix(helm): make use of resource values for webhook

---

docs/tutorials/aws-sd.md

As-is, following the docs results in the following error:
```
json: cannot unmarshal number into Go struct field ObjectMeta.metadata.annotations of type string
```
Related to #4640 while going through the AWS Cloud Map API docs to validate the migration to aws-sdk-go-v2
**Checklist**

Fix AWS Cloud Map docs: annotation key/value pairs must be strings

---

charts/external-dns/CHANGELOG.md
charts/external-dns/README.md
charts/external-dns/templates/deployment.yaml
charts/external-dns/templates/service.yaml
charts/external-dns/templates/servicemonitor.yaml
charts/external-dns/values.yaml

Description
Fix mismatching values in the chart relating to the webhook provider
- ~~Add webhook resources values to deployment~~ #4560
- Add webhook metrics port to service
- Correct webhook metric port in servicemonitor
- Use correct imagePullPolicy value for webhook container
~~This PR also contains #4681, if #4681 is rejected then this PR need to be rebased~~

Webhook provider helm chart fixes

---

docs/rate-limits.md
docs/registry/dynamodb.md
docs/tutorials/aws.md

The existing docs described how to configure the DynamoDB registry, but didn't have a tutorial for someone to walk through.
Related to #4640 while going through the DynamoDB registry docs to validate the migration to aws-sdk-go-v2
**Checklist**

Add tutorial to DynamoDB registry docs

---

.github/workflows/ci.yaml
.github/workflows/codeql-analysis.yaml
.github/workflows/docs.yaml
.github/workflows/lint.yaml
.github/workflows/staging-image-tester.yaml
Makefile
cloudbuild.yaml
docs/contributing/getting-started.md
go.mod
provider/tencentcloud/cloudapi/mockapi.go
provider/tencentcloud/cloudapi/tencentapi.go
provider/tencentcloud/dnspod.go
provider/tencentcloud/privatedns.go
provider/vinyldns/vinyldns.go

This update external dns to go 1.23.
Inspired by #4318
It also upgrade linter to latest version, v1.60.1.
**Checklist**

chore: upgrade ExternalDNS to go 1.23

---

README.md

Adds the [RouterOS Provider](https://github.com/benfiola/external-dns-routeros-provider.git) I've written to the 'webhook providers' section of the README.  
(Also, despite having recently rewritten everything in golang - my initial [python implementation](https://github.com/benfiola/external-dns-routeros-provider/tree/python) could also serve as an example of how one could provide a non-golang python external-dns webhook provider).
**Checklist**

Add RouterOS provider to README.md

---

docs/sources/gateway.md
source/gateway.go
source/gateway_test.go

Allows for dualstack support in GatewayAPI route resources (follows existing ingress/service design paradigm)
Fixes https://github.com/kubernetes-sigs/external-dns/issues/4468
**Checklist**

feat: support dual stack for gateway api

---

docs/nat64.md
main.go
mkdocs.yml
pkg/apis/externaldns/types.go
source/nat64source.go
source/nat64source_test.go

We run an IPv6 only Kubernetes cluster environment and designated a /96 IPv6 network to map to an IPv4 address space in a casual NAT64 setup. Therefore, we need to create an A record for each AAAA record within this address room.
We added an additional source wrapper, similar to `DedupSource` and added a config value for the NAT64 prefixes. The source wrapper looks at all AAAA records and translates them - if applicable - into A records.
We also added unit tests for that.
Note: I did not add any enduser documentation, because I was not sure where to put this part specifically. If you can give me a pointer, I would be happy to add this.
**Checklist**

feat: NAT64 network source

---

charts/external-dns/CHANGELOG.md
charts/external-dns/README.md
charts/external-dns/templates/deployment.yaml
charts/external-dns/templates/service.yaml
charts/external-dns/templates/servicemonitor.yaml
charts/external-dns/values.yaml
docs/tutorials/webhook-provider.md

The current doc for the webhook provider expect the k8s probe to call localhost but the normal Kubernetes behavior is to call the pods IP so the current doc doesn't work.
Some implementers work around this by expecting users to override the `livenessProbe` and `readinessProbe` (see example [external-dns-ionos-webhook](https://github.com/ionos-cloud/external-dns-ionos-webhook/blob/6d6a95f787f1bd2594ecb44c36a9e6d8840a226f/README.md?plain=1#L49-L62)) but this might as well be upstreamed
**Checklist**

Do not risk exposing unauthenticated webhook port on container

---

charts/external-dns/CHANGELOG.md
charts/external-dns/Chart.yaml
charts/external-dns/README.md

This PR releases the Helm chart for the `v0.15.0` release of ExternalDNS.
Fixes #4730
**Checklist**

feat(chart): Updated image to v0.15.0

---

provider/google/google.go
provider/google/google_test.go

Add soft errors to google provider where it is possible to retry or recover.
Leverages #4166 by adding soft errors to the google provider
**Checklist**

adds soft error for google provider

---

README.md
docs/sources/mx-record.md
docs/sources/txt-record.md
provider/digitalocean/digital_ocean.go
provider/digitalocean/digital_ocean_test.go

Add support for MX and TXT records creation for DigitalOcean provider via CRD Source.
**Checklist**

feat(digitalocean): add mx and txt records support

---

docs/tutorials/pdns.md
provider/pdns/pdns.go
provider/pdns/pdns_test.go

This PR enables MX and SRV record support for PowerDNS provider in ExternalDNS. Especially for PowerDNS API, it requires explicit trailing dot for records having FQDN such as CNAME, MX, SRV, etc.. For CNAME record, its already covered here https://github.com/kubernetes-sigs/external-dns/blob/master/provider/pdns/pdns.go#L317-L318 so I added trailing dot for MX and SRV records now.
**Errors Fixed**
Error from PDNS API for SRV record creation
```
level=debug msg="PDNS API response:
level=fatal msg="Failed to do run once: Status: 422 Unprocessable Entity, Body: {\"error\": \"Record _service._tls.example.com./SRV '100 1 443 service.example.com': Not in expected format (parsed as '100 1 443 service.example.com.')\"}"
```
Error from PDNS API for MX record creation
``` …
```

Add support for MX and SRV records in pdns provider

---

pkg/apis/externaldns/types.go
provider/aws/config.go

This change conceals the AWS `ExternalId` from application logs to mitigate security risks, as exposing this identifier could enable attackers to exploit it for unauthorized cross-account access or privilege escalation.
Fixes https://github.com/kubernetes-sigs/external-dns/issues/4277
**Checklist**

Do not expose the AWS role external id in the logs

---

docs/sources/nodes.md
source/node.go
source/node_test.go

Skip unschedulable nodes to avoid adding nodes to a DNS round robin entry.
Added in source/node.go a simple test regarding Node.Spec.Unschedulable.
Fixes [#ISSUE](https://github.com/kubernetes-sigs/external-dns/issues/1112)
**Checklist**

source node: Skip unschedulable nodes

---

docs/tutorials/azure-private-dns.md
docs/tutorials/azure.md
main.go
pkg/apis/externaldns/types.go
provider/azure/azure.go
provider/azure/azure_private_dns.go
provider/azure/azure_privatedns_test.go
provider/azure/azure_test.go
provider/azure/cache.go
provider/azure/cache_test.go

zoneListCache is introduced for Azure so that the azure ratelimiting can be countered with for this particular call. Although the ratelimit is higher for this particular call but in Azure there are some ratelimiters which are shared between various services for example this particular one comes in microsoft.network API provider. This has resulted in some API ratelimiting for this particular call for me even with a relatively lesser number of external DNS running(8). This particular call need not run on all the external DNS reconciliation anyways, it will improve the speed of the reconciliation as well.
Error is mentioned below:
```
Failed to do run once: GET https://management.azure.com/subscriptions/9a42948e-6087-47d2-bdb8-b530d558db22/resourceGroups/glbdemo01-global/provi …
```

feat: add azure zone list cache

---

docs/tutorials/aws-sd.md
provider/awssd/aws_sd.go
provider/awssd/aws_sd_test.go

As reported in the issue, the AWS-SD provider did not support the `AWS_INSTANCE_IPV6` attribute type: https://docs.aws.amazon.com/cloud-map/latest/api/API_RegisterInstance.html
Fixes #4713
**Checklist**

Add AWS_INSTANCE_IPV6 support to the AWS-SD provider

---

provider/awssd/aws_sd_test.go

This PR fixes the flaky test on AWS SD. The test is wrong because the order of iterations on maps in Go is not deterministic so the wrong assertion was used. This also switches to `require` which is a stronger guarantee than `assert` and will fail the test immediately if the assertion is not met.
Fixes #4825
**Checklist**

fix flaky aws sd test

---

provider/pdns/pdns.go
provider/pdns/pdns_test.go

Add soft errors to pdns provider where it is possible to retry or recover.
Leverages #4166 by adding soft errors to the pdns provider
**Checklist**

feat: add soft errors to pdns provider

---

go.mod

Fixes https://github.com/kubernetes-sigs/external-dns/security/advisories/GHSA-29wh-v7vm-3479
**Checklist**

chore(deps): update go to v1.23.3 for CVE-2024-34156

---

provider/google/google.go
provider/google/google_test.go

NS records added in Google Cloud DNS must have a trailing dot. Otherwise the API throws the following error:
```
time="2024-11-04T10:34:20Z" level=error msg="googleapi: Error 400: Invalid value for 'entity.change.additions[cloud.k8gb.io.][NS].rrdata[0]': 'gslb-ns-eu-cloud.k8gb.io', invalid"
```
This is similar to CNAME, MX and SRV records.
---
This change was tested with the a DNSEndpoint CRD containing the following endpoints:
```
endpoints:
- dnsName: cloud.k8gb.io
recordTTL: 5
recordType: NS
targets:
- gslb-ns-eu-cloud.k8gb.io
- gslb-ns-us-cloud.k8gb.io
- dnsName: gslb-ns-eu-cloud.k8gb.io
```
And the record was successfully created
```
gcloud dns record-sets list --zone="k8gb" --type=NS --name "cloud.k8gb.io."
NAME            TYPE  TTL  DATA
cloud.k8gb.io.  NS    5 …
```

fix(Google DNS): ensure trailing dot on NS records

---

provider/aws/aws.go
provider/aws/aws_test.go

It's basically https://github.com/kubernetes-sigs/external-dns/pull/4741 with tests added as per requested
Fixes #4067
**Checklist**

fix(aws): add soft error

---

charts/external-dns/CHANGELOG.md
charts/external-dns/README.md
charts/external-dns/ci/ci-values.yaml
charts/external-dns/templates/deployment.yaml
charts/external-dns/values.yaml

By promoting this options to dedicated values they no longer have to be configured via `extraArgs`.
**Motivation**
In the [K8GB project](https://github.com/k8gb-io/k8gb), a DNS based load balancer, we use external-dns as a chart dependency. We would like to configure all values specific to the controller in the default values of our Chart, and leave to the users the provider configuration. This provider configuration usually includes `extraArgs`. Since `extraArgs` is a list that would be overwritten we would like to keep it empty, otherwise users will have to copy paste our base configuration.
**Checklist**

Add options `labelFilter` and `managedRecordTypes` in Helm Chart

---

docs/tutorials/azure.md

Fixes incorrect property name in the Azure DNS tutorial documentation and updates the description for this property.
Note that the workload identity configuration uses `aadClientId` while the managed identity workload configuration uses `userAssignedIdentityID` when retrieving the client ID from the azure.json file. This was incorrectly documented as using the `userAssignedIdentityID` for both configuration extensions.
Fixes [#4898](https://github.com/kubernetes-sigs/external-dns/issues/4898)
**Checklist**
- N/A - documentation changes only.

docs(Azure DNS): fix tutorial about Azure identity variables

---

registry/txt.go
registry/txt_test.go

This PR fix issue when suffix is used and the domain has no dot
Fixes #1668
**Checklist**
- [N/A] End user documentation updated

fix(txt-suffix): avoid crash on domain without dot

---

.github/workflows/lint.yaml
.spectral.yaml
Makefile
api/webhook.yaml
docs/tutorials/webhook-provider.md
provider/webhook/webhook_test.go

This PR is based on #4148.
**Checklist**

feat(webhook): initial OpenAPI spec

---

charts/external-dns/CHANGELOG.md
charts/external-dns/ci/ci-values.yaml
charts/external-dns/templates/_helpers.tpl
charts/external-dns/templates/deployment.yaml

The labelSelector is used to track the pods that are used for the topologySpreadConstraints calculation. matchLabelKeys is used to only use the pods in the current version of the deployments replicaset.
I believe the following message isn't true before this PR.
https://github.com/kubernetes-sigs/external-dns/blob/1ceaf798ae830b9ba9d76dfbb9ee11d6273d3637/charts/external-dns/values.yaml#L155-L156
More details about matchLabelKeys can be found here:
- https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/
- https://kubernetes.io/blog/2023/04/17/fine-grained-pod-topology-spread-features-beta/#kep-3243-respect-pod-topology-spread-after-rolling-upgrades
- https://pauldally.medium.com/the-most-common-reason-your-topologyspreadconstraint-isnt-working-f …

Include labelSelector for affinity and topologySpreadConstraints

---

provider/azure/azure.go
provider/azure/azure_privatedns_test.go
provider/azure/azure_test.go

Azure supports NS records on public DNS zones: https://learn.microsoft.com/en-us/rest/api/dns/record-sets/create-or-update?view=rest-dns-2018-05-01&tabs=HTTP#create-ns-recordset This PR adds this support to external dns. The implementation is similar to the other records.
Besides the unit tests this PR was also tested by creating a DNSEndpoint with the following spec:
```
endpoints:
- dnsName: cloud.k8gb.io
recordTTL: 5
recordType: NS
targets:
- gslb-ns-eu-cloud.k8gb.io
- gslb-ns-us-cloud.k8gb.io
```
The creation of the NS record in Azure was successful:
```
az network dns record-set ns list --resource-group rg-k8gb  --zone-name "$EDGE_DNS_ZONE" --output json
[
{...},
{
"NSRecords": [
{
"nsdname": "gslb-ns-eu-cloud.k8gb.io"
},
{
"nsdname": "gslb-ns-us-cloud.k8gb.io"
}
], …
```

feat(Azure DNS): add NS record support

---

.ko.yaml
scripts/install-ko.sh

This PR update to the latest KO version. The current version that we are using is defaulting to an old debian image which has an unrated vulnerability with tzdata, picked up by my scanner.
This seems to work. Had to also switch to debian 12. 
Fixes #ISSUE
**Checklist**

update to latest ko version

---

docs/sources/service.md
docs/tutorials/cloudflare.md

1. Documentation references ServiceIP as a field inside of spec, but this field does not exist and it's actually meant to reference to ClusterIP
2. Fixes indentation issue in cloudflare tutorial
Fixes https://github.com/kubernetes-sigs/external-dns/issues/4868
Supersedes #4869
Supersedes #4803
**Checklist**

docs: fix typos in tutorials

---

main.go

Don't discard klog logs at the higest logging levels (debug and trace), as they are necessary to be able to troubleshoot various underlying connectivity / authorization issues.
Fixes #4960
**Checklist**

feat: don't discard klog logs at the highest log levels (debug and trace)

---

source/source.go
source/source_test.go

Updates `suitableType` to allow _all_ valid IPv6 addresses, including IPv4-mapped IPv6 addresses.
https://pkg.go.dev/net/netip#Addr.Is6
Fixes #4942
**Checklist**

fix(source): allow ipv4-mapped ipv6 addresses

---

charts/external-dns/CHANGELOG.md
charts/external-dns/README.md
charts/external-dns/ci/ci-values.yaml
charts/external-dns/templates/serviceaccount.yaml
charts/external-dns/values.yaml

The basic use-case is to add dynamic environmental metadata to external-dns KSA so we can take advantage of advanced cloud IAM features such as IRSA or Workload Identity. We already provide the necessary metadata through values so we could DRY those values and render them in values files. For instance:
```yaml
serviceAccount:
annotations:
iam.gke.io/gcp-service-account: "external-dns@{{ .Values.metadata.gcpProject }}.iam.gserviceaccount"
```
This change doesn't break any previous behavior.

feat(chart): allow to run tpl on `ServiceAccount` annotations

---

provider/ovh/ovh.go
provider/ovh/ovh_test.go

- Cache was not updated when a change occurred which resulted in a change to be redone at each loop
- OVH DNS can have multiple times the exact same entry. Make sure we process all the IDs (instead of picking indefinitely the first one and trying to delete it multiple times resulting in 404).
- Using soft errors instead of hard errors
This PR Fixes all that and make the provider more resilient (all the errors were not soft resulting in the binary to exit).
This also makes #4844  irrelevant as this bug was produced by :
- the cache not being refreshed after changes.
- the list of duplicates not being processed correctly.
**Checklist**

fix(ovh): cache refresh and duplicates processing

---

.github/workflows/lint.yaml
Makefile
endpoint/domain_filter_test.go
endpoint/endpoint.go
go.mod
internal/testutils/endpoint.go
source/nat64source.go
source/service_test.go

1. Fix failing test on TestServiceSource/Endpoints with _example.com_
2. Update go version to 1.23.5
3. Update linter version to 1.63.4
Latest security fixes and working CI.

chore(ci): fix failing test, upgrade to go 1.23.5 and linter to v1.63

---

provider/oci/oci_test.go

It removes a specific test on OCI provider init.
This specific test can only work reliably in the OCI cloud infrastructure.
External-dns is not here to test OCI SDK, especially when it requires internal OCI endpoint.
With this test:
```sh
ok  	sigs.k8s.io/external-dns/provider/oci	361.274s
```
Without this test:
```sh
go test -timeout 600s -run "^TestNewOCIProvider\$"
ok  	sigs.k8s.io/external-dns/provider/oci	0.007s
```

chore(ci): remove too slow test

---

provider/godaddy/client.go
provider/godaddy/client_test.go

Based on some testing, it seems GoDaddy has an undocumented, per-endpoint quota.
During startup, the client calls the endpoint `https://api.godaddy.com/v1/domains?statuses=ACTIVE,PENDING_DNS_ACTIVE1` to test and validate that the credentials are working. Calling that endpoint with the same API key manually, I was able to reproduce the `429` response the API sends, which did not include the `Retry-After` header and thus caused the panic on startup.
However, I was able to call other endpoints, ex: `https://api.godaddy.com/v1/domains/<domain>/records`, leading me to believe there is an undocumented, per-endpoint quota.
With this in mind, I updated the request handler to gracefully fail without panicing when the header is missing, so that other requests can still be attempted. …

fix(godaddy): Handle missing Retry-After header gracefully

---

provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_test.go

Updates the Cloudflare provider to raise SoftError on 5xx status code while interacting with Cloudflare API 
Fixes #4315
**Checklist**

fix(cloudflare): use softerror on internal server error with api

---

docs/tutorials/rfc2136.md

- List secure updates first
- Remove the confusing "(Insecure Updates)" part from the main headline
- Mention zone transfers to other domains
- Mention creating a user for secure updates
**Checklist**

docs(Microsoft DNS): improve instructions

---

docs/registry/txt.md
endpoint/crypto_test.go
endpoint/labels.go
endpoint/labels_test.go
registry/dynamodb.go
registry/dynamodb_test.go
registry/txt.go
registry/txt_encryption_test.go
registry/txt_test.go

Fixes #4975
Fixes #3992
> The primary change in behavior is that the service will now successfully start when an AES key is provided as outlined in the documentation (text or base64 form). The core business logic related to encryption remains unchanged.
- added tests to cover missing branches for endpoint.{labels,crypto}
- added tests to cover logic when AES keys is base64 form
- added tests to cover current label encryption logic for records
- updated/rephrased documentation
While was working on a fix, found a bug, where Dynamodb not encrypting labels https://github.com/kubernetes-sigs/external-dns/blob/e964a66153763860670283bbaf02d0e3348c4d7e/registry/dynamodb.go#L239
Trying to keep the scope of this pull request small. And could tweak DynamoDB encryption in follow up if …

fix(aes-encryption): support plain txt and url safe base64 strings

---

.github/workflows/lint-test-chart.yaml
.github/workflows/release-chart.yaml
charts/external-dns/CHANGELOG.md
charts/external-dns/Chart.yaml
charts/external-dns/README.md
charts/external-dns/templates/clusterrole.yaml

This PR updates the Helm chart to use the latest [v0.15.1](https://github.com/kubernetes-sigs/external-dns/releases/tag/v0.15.1) version and includes all of the other chart changes since the last release. It also includes the code from #4845 as that PR hasn't been able to be merged.
Fixes #4967
Closes #4845
**Checklist**

Release Helm chart for `v0.15.1`

---

docs/tutorials/aws.md

Fixes broken internal markdown links in AWS tutorial. These links were accidentally broken in https://github.com/kubernetes-sigs/external-dns/pull/4577 when some headings were renamed.
**Checklist**

fix(docs): aws tutorial broken internal markdown links

---

docs/tutorials/aws.md
provider/aws/aws.go
provider/aws/aws_test.go
provider/provider.go

Fixes #5012
> Version 0.15.1 is currently experiencing reliability issues for users who rely on zone tags. 
```
--aws-zone-tags=
...
```
- Fixed incorrect behaviour for ListTagsForResource. AWS SDK for Go v2 backwards compatibility issue
- Added `provider.NewSoftErrorf` method
- Refresh/update documentation for domain filtering strategies. Is not full, just few filters that I recently validated working
For follow-up what worth to consider:
- support --aws-zone-tags can specify multiple or separate values with commas: key1=val1,key2=val2
- support --aws-zone-tags can specify exclusion with `!`: !key1=val1,key2=val2
- instead of ListTagsForResource do batching ListTagsForResources
The interface for go-aws-sdk-v2 https://github.com/aws/aws-sdk-go-v2/blob/ed8a3caa0df9ce36a5b60a …

fix(aws-provider): ListTagsForResource incorrect zone-id handling

---

provider/aws/aws.go
provider/aws/aws_test.go

No issue to date.
Just a small improvements  to how canonicalHostedZone handled.
Current number of known canonical hosted zones is 130+ and is increasing, in worth case scenario current logic does 130+ iteration to validate where or not the record is a canonical hosted zone. 
```
results for canonical
before
BenchmarkTestAWSCanonicalHostedZone-16    	    7012	    171223 ns/op
now
BenchmarkTestAWSCanonicalHostedZone-16    	   16812	     68977 ns/op
results for long non-canonical hosted zone
before
enchmarkTestAWSNonCanonicalHostedZone-16    	    4869	    225384 ns/op
with new algo
BenchmarkTestAWSNonCanonicalHostedZone-16    	  277828	      4135 ns/op
```
Comparison
- Algorithm: `canonicalHostedZoneNew uses a more targeted approach by first filtering hostnames based on …

chore(provider-aws): improve canonicalHostedZone handling

---

api/webhook.yaml

Webhook OpenAPI spec misspelled "negotiation." This PR fixes that.
**Checklist**

Fix spelling in webhook OpenAPI spec

---

docs/deprecation.md
docs/proposal/design-template.md
mkdocs.yml

It worth to add `deprecation` policy, as currently not clear how to deal with behaviors that not works as expected or capabilities that should behave differently.
Motivation
- Project is part of kubernetes-sigs, worth to somewhere follow or at least have a deprecation policy 
- Confusion around certain features, and lack of guidance how to deprecate/remove/revert of flip the flag for them https://github.com/kubernetes-sigs/external-dns/pull/4574
**Checklist**

docs: add deprecation policy

---

README.md
docs/release.md

Quite often there is an ask when new release is planned. Not sure if we could answer that, but at least there a staging image available, sounds like a right decision to share this information publicly
**Checklist**

docs: add staging images to release process

---

provider/oci/oci.go
provider/oci/oci_test.go

The OCI provider currently does not support creating DNS records with multiple IP addresses.  Below is example output from the current master branch code showing the failure.  
```
Error returned by Dns Service. Http Status Code: 400. Error Code: InvalidParameter. Opc request id: xxxxxxx. Message: Error returned by PatchForwardedZoneRecords operation in Dns service.(400, InvalidParameter, false) Record (my-local-nginx-lhr.jrosinsk.developers.oracledx.com, A) contained invalid rdata (10.244.0.138 10.244.0.15)
```
This fix handles the case where multiple IP's are part of the operation request by breaking them apart into individual newRecordOperations and  adjusts the endpoints so the records can be rectified accordingly.  
Also adds a warning message, since OCI DNS does not …

fix(oci): records with multiple IP addresses

---

README.md

Add link to webhook provider for [ClouDNS](https://www.cloudns.net/) to README.
The provider is based on PR #3262 implemented as a webhook based on the [Hetzner provider](https://github.com/mconfalonieri/external-dns-hetzner-webhook).
Fixes #3132 
**Checklist**

docs(provider): add ClouDNS to README

---

charts/external-dns/CHANGELOG.md
charts/external-dns/ci/ci-values.yaml
charts/external-dns/templates/serviceaccount.yaml

Added toYaml to convert non string types rendered by `tpl` back to string. For ex: "true".
This change restores the previous behavior to allow boolean/numeric annotations through strings.
Fixes #5039 
**Checklist**

fix(chart): non-string types on svcaccount annotations

---

charts/external-dns/CHANGELOG.md
charts/external-dns/templates/clusterrole.yaml

Updating RBAC to be able to handle F5 TransportServer Source that was added in this PR: https://github.com/kubernetes-sigs/external-dns/pull/4944.
**Checklist**

fix(chart): update rbac for F5 transportserver source

---

.gitignore
docs/contributing/design.md
docs/contributing/dev-guide.md
docs/contributing/index.md
docs/contributing/sources-and-providers.md
docs/flags.md
pkg/apis/externaldns/types.go

No issue. Added documentation with developer guide on minikube, how to generate docs and etc.
Slightly tweaked description of a flag. Slack discussion https://kubernetes.slack.com/archives/C771MKDKQ/p1738846183673949
**Checklist**

docs: update and refactor contribution part

---

endpoint/domain_filter_test.go

Relates #3718 
The work relates to a bug in domain filter logic. I've added a test that focuses only on MATCH behaviour for a domain filters with include and exclude values, and validate against provided domains. This does not fix anything. The filters itself looks like works correctly. 
There is a slight design problem. We instantiate filters in main.go https://github.com/kubernetes-sigs/external-dns/blob/eb1949784e496edd13fac46c898479a0af739e23/main.go#L183, this could not be tested, hence the bug could be there. I keep digging.
Probably an option to consider is to create a composition filter or something. Move if/else filter creation logic away from main.go file. Any preferences, ideas?
**Checklist**

test(domain-filter): simple filters on domain exclusion

---

charts/external-dns/templates/deployment.yaml

Allow affinity.nodeAffinity to be passed through from values.yaml.
Fixes #5037

fix(chart): regression with affinity.nodeAffinity getting ignored

---

source/istio_virtualservice.go
source/istio_virtualservice_test.go

This PR changes to use an informer instead of direct api calls to read the gateway config. This solves a API ratelimit error on our setup and removes stress on the Kubernetes API
Following this change the tests needed to be updated:
* An informer needs a Namespaces, thats why it is set
* An informer never returns an error during the get call except for NotExisting. So this test is removed.
**Checklist**

fix: use informer for istio gateways

---

docs/registry/txt.md

The documentation is wrong here, comma seperated does not work. This also brings txt.md into consistency with all other documents.
This is a documentation only change.
**Checklist**

docs(registry): fix managed-record-type argument

---

source/gateway.go
source/gateway_httproute_test.go

This code referenced the endpoints variable which was updated with each resource leading to confusing debug messages - this sets up a new array each iteration to log just the records from the relevant Gateway resource.

fix(source): debug log on gateway target detection

---

Makefile

not sure how many of us using coverage from local, the up-to-date practice does not require any external toolings to be installed 
Result is the same
current tool used, was a hack that is 10 years old))
**Checklist**

chore(makefile): simplify coverage script

---

.github/workflows/lint.yaml
Makefile
cloudbuild.yaml
docs/contributing/dev-guide.md
go.mod
provider/azure/cache_test.go

This update external dns to go 1.24.
Inspired by #4698
It also upgrade linter to latest version, v1.64.5.
**Checklist**

chore: upgrade ExternalDNS to go 1.24

---

README.md

This adds the webhook provider for OpenStack Designate (https://github.com/inovex/external-dns-openstack-webhook) created by the people @inovex.
While our webhook does have it's own documentation on setting it up, I gladly also update the tutorial for designate (https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/designate.md) within the external-dns repo.

Add OpenStack Designate webook provider to readme

---

README.md

resolves a 404 in the readme pointed to https://github.com/kubernetes-sigs/external-dns/blob/master/docs/contributing/getting-started.md

docs(README): fix link to dev guide

---

docs/sources/gateway.md
docs/tutorials/aws-load-balancer-controller.md
docs/tutorials/aws.md
docs/tutorials/kube-ingress-aws.md
endpoint/labels.go
provider/aws/aws.go
provider/aws/aws_test.go
source/gateway.go
source/gateway_test.go
source/ingress.go
source/ingress_test.go
source/kong_tcpingress.go
source/skipper_routegroup.go
source/skipper_routegroup_test.go
source/traefik_proxy.go

This change creates AAAA and A records for AWS Route53. It is heavily based on this pull request that seems to have sadly been abandoned: https://github.com/kubernetes-sigs/external-dns/pull/3605
This is now based on the current master branch. I've tried to add some more thorough test cases so that when I let this loose in a Kubernetes cluster hopefully not too many bad things will happen.
Fixes: https://github.com/kubernetes-sigs/external-dns/issues/3707
Fixes: https://github.com/kubernetes-sigs/external-dns/issues/4509
All credits to @johngmyers for the vast majority of the leg work.
**Checklist**
**Checklist to drop WIP**

feat(aws): always create AAAA alias records in route53

---

.github/workflows/lint-test-chart.yaml
Makefile
charts/external-dns/.helmignore
charts/external-dns/CHANGELOG.md
charts/external-dns/tests/common-metadata_test.yaml
charts/external-dns/tests/deployment-config_test.yaml
charts/external-dns/tests/deployment-flags_test.yaml
charts/external-dns/tests/deployment-scheduling_test.yaml
charts/external-dns/tests/notes_test.yaml
charts/external-dns/tests/rbac_test.yaml
charts/external-dns/tests/secret_test.yaml
charts/external-dns/tests/serviceaccount_test.yaml
charts/external-dns/values.schema.json
charts/external-dns/values.yaml
docs/contributing/dev-guide.md
scripts/helm-tools.sh

Fixes #4989
Fixes #3960
Fixes #4997
> Note; this is not a silver bullet for all chart/helm related issues
Where helm unit-testing excel
- there are miriads of combinations of value fields supported, with helm-unittest we could snapshot the behaviour
- no need to do `helm template`
- great with preventing regressions, example 
- https://github.com/kubernetes-sigs/external-dns/issues/5039
- https://github.com/kubernetes-sigs/external-dns/issues/5037
- another source of documentation for helm configurations
Cons:
- One to know how to write test for helm templates
- Require a decent coverage, and workflow when new changes added to helm chart
If approach is acceptable, in follow up I'll add more coverage
**Checklist**

feat(chart): add helm-unittest framework

---

provider/awssd/aws_sd.go
provider/awssd/aws_sd_test.go

This improves how registration and deregistration of targets is performed, which incidentally fixes an occasional race condition with the AWS API in this process.
This is a resubmission of this fix, now as a bug fix. Bug was discovered as upgrading from a patched version containing this fix to 0.15.1 was unsuccessful. Old PR is here: https://github.com/kubernetes-sigs/external-dns/pull/3123
Fixes #5134
**Checklist**
- [ x ] Unit tests updated
- [ x ] End user documentation updated

fix(aws-sd): service instances registration and deregistration

---

registry/txt.go
registry/txt_test.go

Fixes #5129 
Context: `TXT` record with routing policy on GCP has no direct single target, as a result, the direct index access to first element fails. (Such routing policy based records not necessarily be part of the external dns management area, it could be created or updated manually that can cause this issue.)
How to test manually:
Let the external-dns run as is , the google DNS zone you are using , create a TXT record with weighted routing policy.
Current version should crash with the error in the issue.
in the PR changes will make sure it gets passed by, with a error line like below
```
ERRO[0002] TXT record <DNS> has no targets
```
**Checklist**

fix(registry): handle empty targets in TXT records logging an error

---

OWNERS

based on https://www.kubernetes.dev/docs/guide/owners/ add automatically labels for "provider" and "source". Some providers have already their own labels so I added these specifically and rest is just "provider" label

add: auto label source and providers

---

docs/flags.md
docs/sources/gateway-api.md
docs/sources/gateway.md
pkg/apis/externaldns/types.go
source/gateway.go
source/gateway_httproute_test.go
source/store.go

Adds a new flag `--gateway-name` to filter by Gateway names, much like the current `--gateway-namespace` and `--gateway-labels`
**Checklist**

feat(source): fitler by gateway name

---

docs/tutorials/cloudflare.md
provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_test.go

…number of custom hostnames more than 50
Fixes #ISSUE
**Checklist**

fix(cloudflare): infinite loop with more than 50 custom hostnames

---

charts/external-dns/CHANGELOG.md
charts/external-dns/Chart.yaml
charts/external-dns/README.md

This PR updates the Helm chart for the latest release version (`0.16.1`).
Fixes #5185 
**Checklist**

feat(chart): Update image to v0.16.1

---

provider/zonefinder.go
provider/zonefinder_test.go

Normalise domain names before looking them up in the zone ID mapping.
Fixes #5090 
**Checklist**

feat: IDNA awareness in the zone finder

---

docs/tutorials/aws.md

I spotted a typo in the route53 IAM while trying to set it up in my environment. This updates the docs to use the plural `route53:ListTagsForResources`
**Checklist**

fix(aws): typo on route53 IAM

---

charts/external-dns/CHANGELOG.md
charts/external-dns/README.md
charts/external-dns/tests/deployment-config_test.yaml
charts/external-dns/tests/serviceaccount_test.yaml
charts/external-dns/values.schema.json
charts/external-dns/values.yaml

Its not possible to use latest helm chart if customisation is required for some properties like 
fullnameOverride, serviceAccount name, priorityClassName etc due to the fact that schema allows only null values. This change adds additional allowed value types.
```bash
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
external-dns:
- serviceAccount.name: Invalid type. Expected: null, given: string
- priorityClassName: Invalid type. Expected: null, given: string
```
Fixes #5206 #5209 #5212 #5230
**Checklist**

fix(chart): add missing types for empty values

---

source/node.go
source/node_test.go

Relates https://github.com/kubernetes-sigs/external-dns/pull/5192
Relates https://github.com/kubernetes-sigs/external-dns/pull/5207#issuecomment-2758574147
I actually did e-2-e test but not on final solution. 
Moved log.Warning to actual code, as we have no warnings anymore
**Checklist**

fix(node): logger test fixed

---

docs/sources/gateway.md

Fix a typo in the "Gateway sources" page. Two characters were twisted, saying `gateway-grcproute` instead of `gateway-grpcroute`.
**Checklist**
- *n/a*

docs(typo): grcp → grpc

---

.github/workflows/lint.yaml
.golangci.yml
Makefile
internal/gen/docs/flags/main.go
pkg/rfc2317/arpa.go
provider/akamai/akamai.go
provider/alibabacloud/alibaba_cloud.go
provider/cloudflare/cloudflare.go
provider/gandi/gandi.go
provider/ovh/ovh.go
provider/plural/plural.go
provider/provider.go
provider/tencentcloud/cloudapi/tencentapi.go
provider/ultradns/ultradns.go
source/compatibility.go
source/crd.go
source/pod.go
source/service.go
source/skipper_routegroup.go
source/source.go

Update golangci-lint to v2.0.2
See https://ldez.github.io/blog/2025/03/23/golangci-lint-v2/

chore(ci): update linter to v2.0.2

---

source/node_test.go

Fix Data Race on source test like [this one](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_external-dns/5241/pull-external-dns-unit-test/1909782199490580480):
It should unblock the other PRs.
**Checklist**

chore(ci): fix random data race failure on source/node test

---

source/gateway.go
source/gateway_grpcroute.go
source/gateway_grpcroute_test.go
source/gateway_httproute.go
source/gateway_httproute_test.go
source/gateway_tcproute.go
source/gateway_tcproute_test.go
source/gateway_test.go
source/gateway_tlsroute.go
source/gateway_tlsroute_test.go
source/gateway_udproute.go
source/gateway_udproute_test.go

This PR updates the `gwRouteIsAccepted` function to ensure that route acceptance is only considered valid when the observed generation matches the current generation. This change prevents stale route statuses from being considered valid and ensures that the route's acceptance status is up-to-date with its current state.
- Added generation comparison logic to prevent stale route statuses
- Updated function to return false if generation mismatch is detected
The previous implementation only checked for the presence of an accepted condition with a true status, but didn't verify if the condition was stale. This could lead to:
- Routes being considered accepted even after significant changes
- Potential misrouting of traffic based on outdated status
- Inconsistent behavior with …

fix(Gateway API): ensure generation match

---

charts/external-dns/CHANGELOG.md
charts/external-dns/Chart.yaml
charts/external-dns/README.md

This PR releases the `v1.16.1` Helm chart version to fix issues with the schema.
Fixes #5260
Fixes #5256
Fixes #5235
Fixes #5212
Fixes #5209
**Checklist**

chore: Release Helm chart v1.16.1

---

provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_test.go
source/source.go
source/source_test.go

Implements the creation & deletion of Cloudflare regional hostnames for A, AAAA & CNAME records when `--cloudflare-region-key` is set or `external-dns.alpha.kubernetes.io/cloudflare-region-key` annotation is set.
Fixes #5174
**Checklist**

fix(cloudflare): regional hostnames

---

internal/testutils/log.go
source/gateway_httproute_test.go
source/node_test.go

Resolves issues like this one https://github.com/kubernetes-sigs/external-dns/pull/5268
Capturing both logs that behave differently not a great idea as it looks. At the moment we not testing klogs logs, so not loosing much.
If the problem persist, I debug more. Example next step to try similar stuff https://github.com/sirupsen/logrus/blob/master/internal/testutils/testutils.go, why we not using it, it's in internal package
**Checklist**

test(log): fix random race detection

---

provider/zonefinder.go
provider/zonefinder_test.go

Hello :wave: 
This PR updates the `FindZone` method in `zonefinder.go` to gracefully handle DNS labels that contain underscores (`_`). Previously, the method attempted to convert the entire hostname to Unicode using `idna.Lookup.ToUnicode`, which fails when labels include underscores — a character that, while disallowed in IDNA, is valid in DNS records like TXT and SRV. 
This caused zone discovery to fail for hostnames such as `cname._metadata.example.com`, that can used in TXT records for metadata verification.
The new logic processes each label in the hostname individually, skipping IDNA conversion for labels containing underscores, thus preserving compatibility with such use cases. This change prevents the function from failing and ensures zone matching continues as …

fix(zonefinder): handle underscores in dns records

---

go.mod

Build external-dns with latest release of go.
It fixes security issues and is [required](https://github.com/kubernetes-sigs/external-dns/actions/runs/14484351586/job/40627130676?pr=5302) by latest version of [gqlgenc](github.com/Yamashou/gqlgenc). 
**Checklist**

chore(deps): build with go 1.24.2

---

charts/external-dns/CHANGELOG.md
charts/external-dns/README.md
charts/external-dns/tests/json-schema_test.yaml
charts/external-dns/values.schema.json
charts/external-dns/values.yaml

Description
Add helm schema changes so liveness and readiness can be int's or strings again.
Fixes https://github.com/kubernetes-sigs/external-dns/issues/5295

fix(helm): update helm schema

---

.golangci.yml
plan/conflict.go
provider/akamai/akamai.go
provider/alibabacloud/alibaba_cloud_test.go
provider/aws/aws.go
provider/azure/config_test.go
provider/azure/config_test.json
provider/azure/fixtures/config_test.json
provider/exoscale/exoscale.go
provider/godaddy/godaddy.go
provider/oci/oci.go
registry/dynamodb.go
source/crd.go

- added few more lint check
- now changes to actual logic
follow-up; I'll add more linters
Reasons for changes
**Checklist**

chore(code-quality): added lint checks

---

provider/pihole/clientV6.go
provider/pihole/clientV6_test.go

Fixes #5251 
This PR add support for IPv6 Dual with the following format : **y:y:y:y:y:y:x.x.x.x**
PiHole support such IPs but previous implementations did not take it in account. 
External DNS was able to push such record, but can not read it from the provider (the record was filtered out because mark as IPV6 but containing a '.' . Finally External DNS try to push again the record but the provider return an error because the record is duplicated.
This implementation fix this and the test used to determine if it is an IPv4 or IPv6 is more robust.
Also get rid of **instrumented_http**, httpClient is enough. See https://github.com/kubernetes-sigs/external-dns/pull/5226#issuecomment-2777868810 .
No change done on the V5 implementation as it is now deprecated.
**Checklist**

feat(pihole): add support for IPv6 Dual format

---

charts/external-dns/CHANGELOG.md
charts/external-dns/README.md
charts/external-dns/templates/deployment.yaml
charts/external-dns/tests/deployment-flags_test.yaml
charts/external-dns/values.schema.json
charts/external-dns/values.yaml

With external-dns relying a lot on `extraArgs` for its configuration using a map (key: value) data structure for extraArgs enables a lot more versatility. Multiple values files can be used to e.g. configure common values in one and then only specific values in another. 
Also setting certain values via `--set` is then possible - e.g to only change a single setting per environment or inject some value dynamically from CI.
**Checklist**
- [?] Unit tests updated
I did update the schema file
- [?] End user documentation updated
Maybe it makes sense to change the documented value type of `extraArgs` to map?

feat(helm): allow extraArgs to also be a map enabling overrides of individual values

---

docs/flags.md
docs/tutorials/rfc2136.md
pkg/apis/externaldns/types.go

Updates to documentation related to RFC2136.
- Rewrite description of flag `--rfc2136-zone` to clarify the possibility of multiple uses.
- Update RFC2136 tutorial with Helm example, using the official chart and a secret for the TSIG key.
**Checklist**

docs: update rfc2136

---

provider/cloudflare/cloudflare.go
provider/coredns/coredns.go
provider/dnsimple/dnsimple.go
provider/exoscale/exoscale.go
provider/godaddy/client.go
provider/godaddy/godaddy.go
provider/google/google.go
provider/ibmcloud/ibmcloud.go
provider/linode/linode.go
provider/ns1/ns1.go
provider/oci/oci.go
provider/ovh/ovh.go
provider/plural/plural.go
provider/tencentcloud/tencent_cloud_test.go
provider/ultradns/ultradns.go

Slicing pull request https://github.com/kubernetes-sigs/external-dns/pull/5312
target is to make sure pull requst 5312 only contain `defaultTTL` changes
**Checklist**
Linter warnings

chore(code-quality): providers linter warnings fixes

---

source/node_test.go

The data race is still here, for example [this fail](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_external-dns/5333/pull-external-dns-unit-test/1916572832632934400) is on a documentation PR.
* With `t.Parallel()`: 2.910s
* Without `t.Parallel()`: 3.052s
This is a second attempt for a simple fix, after #5268,  until we have a better solution on log testing.
**Checklist**

test(source): fix data race on node_test

---

provider/webhook/api/httpapi.go
provider/webhook/api/httpapi_test.go
provider/webhook/webhook.go
provider/webhook/webhook_test.go

- Increase code coverage for provider/webhook
- use http constants for methods and error codes
Error cases mainly covered. Not error cases could be easy covered, so stopped at 90% coverage
From ~65% to 92%
Follow-up, bump "github.com/cenkalti/backoff/v4" to "github.com/cenkalti/backoff/v5" 
**Checklist**

chore(code-quality): webhook increase code coverage

---

CONTRIBUTING.md

Some contributors are confused with current situation, where we use conventional commits and it's explicitly detailed in contributing guide, see [here](https://github.com/kubernetes-sigs/external-dns/pull/5271#issuecomment-2818655239).
**Checklist**

docs(contributing): add conventional commits

---

provider/cloudflare/cloudflare_test.go

Improve coverage on Cloudflare provider, test some missing cases(from 89,0% to 91,2%)
Fixes #5118
**Checklist**

test: add tests for cloudflare provider

---

docs/tutorials/rfc2136.md

There are typo on environment variable `EXTERNAL_DNS_RFC2136_TSIG_KEYNAME` and `EXTERNAL_DNS_RFC2136_TSIG_SECRET` on the docs causing external-dns failed to start up.
Fixes #ISSUE
**Checklist**

docs(rfc2136): fix env variable in the guideline

---

charts/external-dns/README.md
charts/external-dns/values.yaml

Small commit to fix typo on chart value in txtOwnerId description

chore: fix typo on txtOwnerId comment/description

---

plan/plan.go
plan/plan_test.go
provider/webhook/api/httpapi.go
provider/webhook/api/httpapi_test.go
provider/webhook/webhook.go

Fixes #5177 #5110
- In this pull request I've added an explicit support for casing.
- I've also added unit tests for lower and mixed casing
this is a follow up for https://github.com/kubernetes-sigs/external-dns/pull/5337
**Checklist**

fix(webhook): api json object plan.Changes case

---

source/store_test.go

Improve the `store.go` file test coverage, from 23ish % to 33,3%
Related to #5150
**Checklist**

test(source): cover unhappy paths

---

pkg/tlsutils/tlsconfig_test.go

Improve code coverage of the tlsconfig package from 0 to 90%
The test key and certificate were retrieved from the [Go crypto package](https://github.com/golang/go/blob/00b63486583ef8055c821fa16a87017e04dc2920/src/crypto/tls/tls_test.go)
Linked to #5150
**Checklist**

test(tlsconfig): add unit tests

---

docs/advanced/fqdn-templating.md
source/fqdn/fqdn.go
source/fqdn/fqdn_test.go
source/node_test.go

Adds a few useful text/template functions:
- replace: replace all substrings in a target string
- isIPv6: exposes an existing function that returns a bool to let you know if a string is an IPv6 address
- isIPv4: a new function that returns a bool to let you know if a string is an IPv4 address
N/A
**Checklist**

feat: additional template functions

---

docs/flags.md
pkg/apis/externaldns/types.go

Document the default behavior of --[no-]combine-fqdn-annotation at https://github.com/kubernetes-sigs/external-dns/blob/master/docs/flags.md
Fixes #5264
**Checklist**

chore(docs): document the default behavior of --[no-]combine-fqdn-annotation

---

provider/pihole/clientV6_test.go
source/compatibility.go
source/node.go
source/service.go
source/service_test.go
source/store.go

- Ensured consistency in naming of IPv6 variables (renamed all IPV6 -> IPv6 to be inline with Golang)
- Added already existing `exposeInternalIPv6` flag to service source
- Changed all two places where internal IPv6 were used as if they were external to take into account exposeInternalIPv6
+ `legacyEndpointsFromDNSControllerNodePortService`
+ `extractHeadlessEndpoints`
- **Modified all service tests to already default to unset `exposeInternalIPv6`** -> this only invalided three tests
+ These three tests had the `exposeInternalIPv6` flag set
- Added single test to ensure only external IPv6 are "exposed" when `exposeInternalIPv6` is **not** set
Fixes #5377 
**Checklist**

fix(source): expose internal ipv6 flag on headless service

---

.golangci.yml
provider/alibabacloud/alibaba_cloud.go
provider/azure/config.go
provider/ibmcloud/ibmcloud.go
provider/tencentcloud/tencent_cloud.go

`codebase uniformity`
1. Reduced Cognitive Load During Code Review: When a codebase adheres to consistent style guidelines, naming conventions, and architectural patterns, reviewers can focus more on the logic and potential issues within the code changes rather than spending time deciphering unfamiliar or inconsistent formatting and structures. This allows for more efficient and insightful reviews, ultimately leading to higher quality code.
2.  Enhanced Readability: A uniform codebase is more predictable, making it easier for developers to follow and understand the code, thereby reducing the cognitive load.
3.   Easier Onboarding: When a codebase is consistent, new team members can get up to speed more quickly as they don’t have to adjust to different coding styles or paradigms in …

chore(codebase): add linters for json/yaml tags

---

.golangci.yml
internal/testutils/env.go
pkg/tlsutils/tlsconfig.go
provider/cloudflare/cloudflare.go
provider/coredns/coredns.go
provider/coredns/coredns_test.go
provider/digitalocean/digital_ocean_test.go
provider/ns1/ns1_test.go
provider/pdns/pdns_test.go
provider/scaleway/scaleway_test.go
provider/ultradns/ultradns_test.go
source/istio_virtualservice.go
source/traefik_proxy_test.go

codebase uniformity benefits
1. Reduced Cognitive Load During Code Review: When a codebase adheres to consistent style guidelines, naming conventions, and architectural patterns, reviewers can focus more on the logic and potential issues within the code changes rather than spending time deciphering unfamiliar or inconsistent formatting and structures. This allows for more efficient and insightful reviews, ultimately leading to higher quality code.
2. Enhanced Readability: A uniform codebase is more predictable, making it easier for developers to follow and understand the code, thereby reducing the cognitive load.
3. Easier Onboarding: When a codebase is consistent, new team members can get up to speed more quickly as they don’t have to adjust to different coding styles or …

chore(codebase): add nilnil return check

---

controller/execute.go
docs/flags.md
docs/tutorials/cloudflare.md
pkg/apis/externaldns/types.go
pkg/apis/externaldns/types_test.go
provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_test.go
source/annotations/annotations.go
source/annotations/provider_specific.go
source/annotations/provider_specific_test.go

This will add a flags to be used on the Cloudflare provider for making `comment` available for DNS records. That's helpful when you already have a lot of records and you'd like to track what external-dns is provisioning there and why.
Comment can be set as follows 
- As a program flag `--cloudflare-record-comment="Ingresses for my domain"`
- Or as Ingress annotations, taking precedence over the program args
```yaml
annotations:
external-dns.alpha.kubernetes.io/cloudflare-record-comment: "An Ingress for my-app"
```
Fixes #3934
This is a subset of https://github.com/kubernetes-sigs/external-dns/pull/5359
Tags were posing issues to work without causing a config drift and endless syncs; Will address these separately on a subsequent pull request.
**Checklist**

feat(cloudflare): Suppport DNS record comments

---

provider/rfc2136/rfc2136.go
provider/rfc2136/rfc2136_test.go

This closes #5240, and fixes RFC3645 issues.
This removes `krb5Realm` updates in apply changes, and removes storing the credentials handle due to issues with handle loosing ctx which stores the credentials during updates, causing the next update to always fail.
```go
---
r.krb5Realm = strings.ToUpper(zone)
```
Fixes #5240
**Checklist**

fix(rfc2136): credential and realm issue when using active directory

---

.golangci.yml
docs/flags.md
endpoint/crypto_test.go
pkg/apis/externaldns/types.go
provider/ns1/ns1.go
provider/rfc2136/rfc2136_test.go
provider/transip/transip.go
provider/transip/transip_test.go

Duplicate word linter
previos pr https://github.com/kubernetes-sigs/external-dns/pull/5433
**Checklist**

chore(codebase): enable dupword linter

---

.golangci.yml
internal/gen/docs/utils/utils.go
provider/akamai/akamai.go
provider/alibabacloud/alibaba_cloud.go
provider/azure/azure.go
provider/azure/azure_private_dns.go
provider/azure/config.go
provider/azure/config_test.go
provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_test.go
provider/google/google_test.go
provider/ibmcloud/ibmcloud.go
provider/pdns/pdns.go
provider/pihole/clientV6_test.go
provider/pihole/client_test.go
provider/rfc2136/rfc2136.go
provider/tencentcloud/cloudapi/tencentapi.go
provider/webhook/webhook.go
source/skipper_routegroup.go
source/source.go

Enable errorlint. Fixes formattting for errors, and correct usage. All changed by linter itself.
**Checklist**

chore(codebase): enable errorlint

---

source/service.go

Reducing cyclomatic complexity of the extractNodePortTargets function. 
- move pod retrieval logic into a separated function
- move nodes retrieval logic into a separated function
- replace a switch definition with one case by a if/else statement
- replace 2 ifs statements by a switch definition
Related to #5419
**Checklist**

chore(source): reduce cyclomatic complexity of extractNodePortTargets

---

.github/pull_request_template.md

It updates the PR template for GitHub.
* The current template does not follow markdown convention
* Put in front the hidden comment for newcomers
* Does not enforce ownership

docs(github): update pr template

---

pkg/apis/externaldns/validation/validation.go
pkg/apis/externaldns/validation/validation_test.go

Reduce cyclomatic complexity of `validation.ValidateConfig()` (cylcop=30) function by splitting it into functions.
Also add new tests to cover every cases.
See https://github.com/kubernetes-sigs/external-dns/issues/5419

chore(code-quality): reduce cyclomatic complexity of validation.ValidateConfig

---

provider/rfc2136/rfc2136.go
provider/rfc2136/rfc2136_test.go

Recap from #5261:
> When multiple zones are configured for the RFC2136 provider with --rfc2136-zone, the provider only reads zone data with AXFR from each zone in sequence until it reaches a zone that returns > 0 records, and stops reading.
> 
> This results in the zones that are not read via AXFR re-adding their RR records every sync interval, regardless of whether they exist in the server (properly-read zones do not do this).
In addition to this behavior, when the TXT record registry is used with encryption, many duplicate TXT records are created over time as the values differ, leading to increased load on the DNS server.
Fixes #5261
**Checklist**

fix(rfc2136): collect existing records from all configured zones

---

.golangci.yml
provider/akamai/akamai_test.go
provider/godaddy/godaddy_test.go
provider/ovh/ovh_test.go
provider/webhook/api/httpapi.go
provider/webhook/api/httpapi_test.go

Added errcheckjson linter.
Looks like the only fixes are in tests. This linter is still useful, as if tests swallowing errors, and then we validate for no error, it's not really a test.
initial error https://github.com/kubernetes-sigs/external-dns/actions/runs/15182117601/job/42693734466?pr=5448

chore(code-quality): added linter errchkjson

---

source/ambassador_host.go
source/contour_httpproxy.go
source/f5_transportserver.go
source/f5_virtualserver.go
source/gateway.go
source/informers/informers.go
source/informers/informers_test.go
source/ingress.go
source/istio_gateway.go
source/istio_virtualservice.go
source/kong_tcpingress.go
source/node.go
source/openshift_route.go
source/pod.go
source/service.go
source/source.go
source/source_test.go
source/traefik_proxy.go

I was looking at issues, example
- https://github.com/kubernetes-sigs/external-dns/issues/4955
- https://github.com/kubernetes-sigs/external-dns/issues/3173
- https://github.com/kubernetes-sigs/external-dns/issues/3169
Most of them related timeouts. This PR is not a fix for any of them. There is a flag https://github.com/kubernetes-sigs/external-dns/blob/36bc7d6bc47d4d8862aa02f88ac57d0608919a2a/docs/flags.md?plain=1#L12C1-L12C2 `--request-timeout=`, but the config is not respected, the timeout is static.
In this PR I've
- added more unit tests
- moved cache to dedicated folder
- different source do use different aliases for imports, fixed this
- added more units tests
This will simplify in follow-up to
- support sync request timeout in cache sync with the flag
- will simplify in fiture to …

chore(source): move cache informer to dedicated folder

---

endpoint/endpoint.go
internal/testutils/endpoint_test.go
source/crd.go
source/crd_test.go
source/shared_test.go

Relates https://github.com/kubernetes-sigs/external-dns/issues/5243
Working with CRD, I found that labels applied in a loop, such as ResourceLabelKey. The flow looks like that
```mermaid
flowchart TD
A[Start Endpoints Method] --> B[List DNSEndpoints from Informer]
B --> C{Error?}
C -- Yes --> Z[Return Error]
C -- No --> D[Loop over DNSEndpoint Items]
D --> E[Extract Metadata and TTL]
E --> F[Loop over Spec.Endpoints]
F --> G[Convert to endpoint.Endpoint]
G --> H[Call setResourceLabel]
H --> I[Loop over Labels to set resource label]
I --> J[Append to Final Result List]
J --> K{More Spec.Endpoints?}
K -- Yes --> F
K -- No --> L{More DNSEndpoints?}
L -- Yes --> D
L -- No --> M[Return Final Result List]
```
Let:
- n = number of DNSEndpoint resources
- m = average number of .Spec.Endpoints per …

chore(source/crd): optimize endpoint labels without looping over

---

controller/controller.go
controller/controller_test.go
docs/monitoring/metrics.md
internal/gen/docs/metrics/main_test.go

- **New Metric Added**
- Added a Prometheus gauge metric: `external_dns_controller_consecutive_soft_errors`
- This metric tracks the number of consecutive soft errors (non-fatal, retryable errors) encountered during the controller’s reconciliation loop.
- **Metric Registration**
- Registered the new `consecutiveSoftErrors` metric with the existing set of metrics.
- **Enhanced Error Handling in Controller Loop**
- Introduced a `softErrorCount` counter to track consecutive soft errors.
- On each soft error:
- Increment the counter.
- Update the Prometheus metric.
- Log the error including the current consecutive count.
- On successful reconciliation after soft errors:
- Log the recovery and count of previous consecutive soft errors.
- Reset the counter and metric to zero.
**Benefit:** …

feat(metrics): consecutiveSoftErrors

---

provider/ovh/ovh.go
provider/ovh/ovh_test.go

Fixing OVH provider latest release
Report from #5407

fix: ovh: correct handling of records deletion

---

source/pod_test.go

Removes a second call to `t.Parallel()`.
There is already a first one at the beginning of the test, L36.
Fix CI.

test(source): fix flakyness on pod_test.go

---

source/pod_test.go

Remove flaky log assertions from `TestPodSource` to fix race conditions that caused intermittent test failures with "Expected no debug messages" errors.
Example of the race condition failure:  : [link](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_external-dns/5459/pull-external-dns-unit-test/1932580133185523712)
The `TestPodSource` test was experiencing flaky failures due to race conditions when running in parallel. 
The issue occurred because:
1. **Global logger state conflicts**: Multiple tests with `t.Parallel()` were simultaneously
modifying the global logrus logger through `LogsUnderTestWithLogLevel()`
2. **Implementation detail testing**: Testing log output (an implementation detail) rather than
focusing on the core functionality
**Solution**: Remove …

test(source): remove flaky log assertions from pod tests

---

controller/controller_test.go

Fix flaky `TestToggleRegistry` test by increasing timeout from 2 seconds to 15 seconds.
Example of the race condition failure: [link](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_external-dns/5459/pull-external-dns-unit-test/1932571764517244928)
The `TestToggleRegistry` test was experiencing intermittent failures in CI environments due to an insufficient 2-second timeout. 
The test validates that a controller continues retrying after soft errors, but slow CI environments couldn't consistently complete 3 retry attempts within the tight deadline.
**Solution**: Increase timeout to 1 minute as a safety net against infinite loops while being generous enough for any reasonable CI environment. 
Additionally, improve test efficiency by:
- Extracting magic number `3` …

test(controller): increase timeout and refactor toggle registry test

---

source/service.go
source/service_fqdn_test.go

- add fqdn specific tests for service source
- get better understanding how source service currently behaves
- simplified in the method if statement. added early return
Similar PR https://github.com/kubernetes-sigs/external-dns/pull/5507
To reduce a likelhood that following PRs are about to break FQDN templating for source=service
- https://github.com/kubernetes-sigs/external-dns/pull/5493
- https://github.com/kubernetes-sigs/external-dns/pull/5383

test(source): add fqdn specific tests on service

---

docs/advanced/fqdn-templating.md
source/node.go
source/node_fqdn_test.go
source/node_test.go
source/store.go

Adds support for nodes source and FQDN Combine.
Follow up for PR https://github.com/kubernetes-sigs/external-dns/pull/5498
follow-up:
- review a FQDN framework, maybe to have an interface or something bit better
- review what's left in PR to add/fix https://github.com/kubernetes-sigs/external-dns/pull/5498

feat(source/node): fqdn support combineFQDNAnnotation

---

source/endpoint_benchmark_test.go
source/endpoints.go
source/endpoints_test.go
source/f5_virtualserver_test.go
source/istio_gateway.go
source/istio_gateway_test.go
source/istio_virtualservice.go
source/istio_virtualservice_test.go

In this PR, I've added a benchmark tests, to showcase bottlenecks described here https://github.com/kubernetes-sigs/external-dns/pull/5473#issuecomment-2911576025
- benchmark tests
- added more tests
- found duplicate code and replaced with function
When decided to have a look started
- https://github.com/kubernetes-sigs/external-dns/pull/5473
- https://github.com/kubernetes-sigs/external-dns/issues/5016
And this comment https://github.com/kubernetes-sigs/external-dns/pull/5493#discussion_r2143457453
One of the bottlenecks is in this lines https://github.com/kubernetes-sigs/external-dns/blob/051c900d1c6073a2e02c2b55c05ab932af8bcc66/source/endpoints.go#L87-L110
Basically it does
- retrive all services from the cache
- iterate over each service
- iterate over each label
On top of that, the …

perf(source): benchmarks on EndpointTargetsFromServices

---

provider/awssd/fixtures_test.go

Fix the flaky test `TestAWSSDProvider_CreateService()`.
Use a deterministic ID when creating a service in the stub client to avoid random collision in `s.service` map (indexed by service ID). 
https://github.com/kubernetes-sigs/external-dns/blob/a4522f0b7616ef97c7deb9bec6959611bc4d92cd/provider/awssd/fixtures_test.go#L74
```
--- FAIL: TestAWSSDProvider_CreateService (0.00s)
fixtures_test.go:264: 
Error Trace:	/home/prow/go/src/github.com/kubernetes-sigs/external-dns/provider/awssd/fixtures_test.go:264
/home/prow/go/src/github.com/kubernetes-sigs/external-dns/provider/awssd/aws_sd_test.go:497
Error:      	"map[1307:0xc0000f7340 7804:0xc0000f7180 9424:0xc0000f6fc0]" should have 4 item(s), but has 3
Test:       	TestAWSSDProvider_CreateService
FAIL
``` …

test(awssd): fix a flaky test

---

docs/sources/mx-record.md
endpoint/endpoint.go
endpoint/endpoint_test.go
provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_test.go
provider/digitalocean/digital_ocean.go
registry/txt.go
registry/txt_test.go

Hi there! 👋
Description
This PR introduces support for MX records for the Cloudflare provider.
- Cloudflare can now manage MX records via the DNSEndpoint CRD.
- Adds logic to parse MX records and extract priority and mail host
- Extends unit tests to validate proper MX record creation and priority 
- Updates the documentation to reflect support for cloudflare in MX record management.
Fixes https://github.com/kubernetes-sigs/external-dns/issues/5282
Checklist
Thanks for checking this out! 🙏
Looking forward to your feedback — happy to make any changes if needed.

feat(cloudflare): add support for MX records

---

.github/workflows/json-yaml-validate.yml

Update the dependency
Blocking [issue](https://github.com/GrantBirki/json-yaml-validate/issues/86) has been fixed

chore(deps): bump json-yaml-validate to v3.3.1

---

docs/flags.md
docs/snippets/traefik-proxy/ingress-route-default.yaml
docs/snippets/traefik-proxy/ingress-route-public-private.yaml
docs/snippets/traefik-proxy/traefik-public-private-config.yaml
docs/snippets/traefik-proxy/with-cluster-rbac.yaml
docs/snippets/traefik-proxy/without-rbac.yaml
docs/sources/traefik-proxy.md
pkg/apis/externaldns/types.go
source/traefik_proxy.go
source/traefik_proxy_test.go

- Added docs how to traefik proxy with public/private routing
- treafik-proxy.go IDE linting
- linked https://github.com/kubernetes-sigs/external-dns/pull/5380
Issue https://github.com/kubernetes-sigs/external-dns/issues/5474
follow-up for traefik-proxy source (just too keep a todo list for future):
- support label selectors
- support FQDN
- add support for native traefik informers (currently not exist)
- remove legacy/old Treafik apis
how it looks like

docs(traefik): public and private routing

---

charts/external-dns/CHANGELOG.md
charts/external-dns/README.md
charts/external-dns/values.schema.json
charts/external-dns/values.yaml

Adding additional containers is currently impossible because the `.extraContainers` attribute is defined as object while the templating expects an array. This blocks the addition of other containers to the deployment using the Helm chart.
This PR changes the type of the `.extraContainers` attribute to an array to match [the template logic](https://github.com/kubernetes-sigs/external-dns/blob/57abe1d2/charts/external-dns/templates/deployment.yaml#L74-L76).
Adding additional containers to the `Deployment` using the Helm chart.
I also came across this problem while trying to add a webhook provider container as a workaround for https://github.com/kubernetes-sigs/external-dns/issues/5071, but this was also impossible due to this type mismatch.
I suspect that this attribute has never been …

fix(chart): Change .extraContainers type to array

---

scripts/releaser.sh

Improve releaser script with
1. A new Breaking Changes section 
2. Better parsing on all sections
Readability on release notes

chore(ci): improve releaser script

---

docs/flags.md
docs/proposal/002-internal-ipv6-handling-rollback.md
docs/sources/nodes.md
pkg/apis/externaldns/types.go

Change default of expose-internal-ipv6
Follow-up of #5192

feat(nodes)!: expose external ipv6 by default

---

plan/plan.go
plan/plan_test.go

fixes #5581, tested by running test with -v and added println("warn") to the log warning path

fix: reduce warning by using idna profile

---

.golangci.yml
source/store.go
source/store_test.go

Reduces Cyclic complexity on the `BuildWithConfig` function
Helps with #5419

chore(store*): add reduce complexity and improve code coverage

---

provider/rfc2136/rfc2136.go
provider/rfc2136/rfc2136_test.go

If there are many updates to be made, UpdateNew is split into several chunks.
To get the corresponding row in UpdateOld, only the index in the current chunk is used.
But UpdateOld is not splitted, to get the right element in UpdateOld (not splitted), you have to adjust the index to be in the corresponding chunk.

fix(rfc2136): Use correct index for accessing UpdateOld if there are multiple chunks

---

apis/OWNERS
controller/OWNERS
internal/OWNERS
kustomize/OWNERS
pkg/apis/OWNERS
pkg/metrics/OWNERS
pkg/rfc2317/OWNERS
pkg/tlsutils/OWNERS
plan/OWNERS
registry/OWNERS
scripts/OWNERS

Automatically set a label on each root directory
Follow-up of #5481.
Easier PR review / triage.

chore(ci): update labels automation

---

source/ambassador_host.go
source/contour_httpproxy.go
source/endpoints.go
source/endpoints_test.go
source/f5_transportserver.go
source/f5_virtualserver.go
source/gateway.go
source/gloo_proxy.go
source/ingress.go
source/istio_gateway.go
source/istio_virtualservice.go
source/kong_tcpingress.go
source/openshift_route.go
source/service.go
source/skipper_routegroup.go
source/traefik_proxy.go

Code reuse, reduce codebase
EndpointsForHostname for better incapsulation worth most likely to move to `endpoint/endpoint.go` file or similar. We will see, as immediate value not yet clear. 
Follow up for PRs
- https://github.com/kubernetes-sigs/external-dns/pull/5598#discussion_r2182298226
- https://github.com/kubernetes-sigs/external-dns/pull/5304

chore(codebase): code reuse

---

provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_regional.go
provider/cloudflare/cloudflare_regional_test.go
provider/cloudflare/cloudflare_test.go

Use a local regionalHostname stuct instead of the cloudflare.RegionalHostname from the deperecated cloudflare client.
This is to prepare for https://github.com/kubernetes-sigs/external-dns/pull/5609 and reduce PR size/complexity.

refactor(provider/cloudflare): use local regionalHostname struct

---

docs/sources/istio.md
registry/txt_test.go
source/istio_gateway.go
source/istio_gateway_test.go
source/istio_virtualservice.go
source/istio_virtualservice_test.go

- Added support for currently supported version 1.22 - 1.25, 1.26 https://istio.io/latest/docs/releases/supported-releases/
- fixed `istio.md` with pre-commit-hook
> Note; tested with 1.22 and 1.25 versions. Works without issues
Currently supported version is 1.25, as 1.22 end of life is Jan 22, 2025 
Stored versions
```sh
❯❯ kubectl get crd virtualservices.networking.istio.io -ojsonpath='{.status.storedVersions}'
["v1beta1"]%
❯❯ kubectl get crd gateways.networking.istio.io -ojsonpath='{.status.storedVersions}'
["v1beta1"]%
❯❯ kubectl get crd virtualservices.networking.istio.io -ojsonpath='{.status.storedVersions}'
["v1beta1"]%
❯❯ kubectl get crd gateways.networking.istio.io -ojsonpath='{.status.storedVersions}'
["v1beta1"]%
```
It is safe to use`v1`, but I think we should support …

feat(source/istio): support version 1.25+

---

docs/annotations/annotations.md
docs/tutorials/hostport.md

- Updated documentation for kafka and headless records handling
- Added use cases for `external-dns.alpha.kubernetes.io/hostname` annotations
- Follow-up for PR https://github.com/kubernetes-sigs/external-dns/pull/5614
- Discussion https://github.com/kubernetes-sigs/external-dns/pull/5614#issuecomment-3042800664
Fixes #4282, #2832
I'm unsure if there is a solution. At the moment we could use annotation or FQDN templating. When `host` annotation is used, my understanding the host is set as is, which make sense. It's more a misconfiguration to me on client side. We ofcourse could do a validation, something like `publicsuffix.EffectiveTLDPlusOne(hostname)` or similar, but not clear what the value is.

docs(source/service): headless records and root/base domain

---

source/crd.go
source/crd_test.go

- The `*` is not required when `cache.SharedInformer` is an interface. In Go, interfaces are reference types, so we should use `cache.SharedInformer` (not `*cache.SharedInformer`). Using a pointer to an interface is almost always unnecessary and can lead to confusion.
- slightly simplify decision logic
- Relates https://github.com/kubernetes-sigs/external-dns/issues/5243

chore(codebase): remove pointer to an interface

---

provider/pihole/clientV6.go
provider/pihole/clientV6_test.go
provider/pihole/pihole.go
provider/pihole/piholeV6_test.go

- create multiple targets for A and AAAA records for the pihole provider
#5423  
Since a month already passed from the original PR without any updates, I created this PR with some improvements.
It's also fine by me if the original PR gets merged after appropriate changes, I don't want to take any credits or anything, just want to get this fix in place :).
Should we do anything if any of the individual requests fail, e.g.
1. I want to create a DNS entry with multiple targets: example.com, [192.168.1.2, 192.168.1.3]
2. The first entry gets created: `example.com 192.168.1.2`
3. The second entry fails for some reason
The same would probably happen with updates.
As it currently stands (if I read it correctly), updates and failures wouldn't get noticed ever: …

fix(pihole): create record for all targets

---

go.mod
go.sum
provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_regional.go
provider/cloudflare/cloudflare_regional_test.go
provider/cloudflare/pagination.go
provider/cloudflare/pagination_test.go

Migrate the regional services logic to the cloudflare lib v4.
We keep the old version for other parts (zone, custom hostnames, dns).
~~The v4 lib do not have the `RegionalHostname` struct so I redefined it~~ (done in https://github.com/kubernetes-sigs/external-dns/pull/5615).
I also introduce a function `autoPagerIterator()` to convert the v4 lib "AutoPager" to a go iterator.
This is used only once for now but it is intended to be used in other list calls.
There is no changes in the logic, simply a different api / structs.
The current client is not supported anymore. 
See https://github.com/kubernetes-sigs/external-dns/issues/5540.

chore(cloudflare): use lib v4 for regional services

---

docs/tutorials/aws.md

Added the missing Helm command under the AWS Installation tutorial.
Although the command is mentioned under the "[Chart](https://kubernetes-sigs.github.io/external-dns/latest/charts/external-dns/#installing-the-chart)" section, users who land directly on the AWS Installation page may find it difficult to locate.

docs(aws): add helm repo command to the tutorial

---

source/informers/handlers.go
source/informers/handlers_test.go
source/service.go
source/service_test.go

- when `--service-type-filter` is configured, disable node informer when not required
`nodeInformer` used in 2 places
- `v1.ServiceTypeNodePort` (could be safely disabled)
- extractNodePortTargets
- nodesExternalTrafficPolicyTypeLocal
- `V1. ServiceTypeClusterIP`  -> added null check, and warning message, so that if informer is disabled but should be enabled
- extractHeadlessEndpoints
Fixes #3169
Follow-up:
- we could exclude certain services from caching/indexing when `--service-type-filter` is specified. This should increase performance and reduce number of API calls and etc.
- disable pod informer when LoadBalancer is set https://github.com/kubernetes-sigs/external-dns/issues/4955 and https://github.com/kubernetes-sigs/external-dns/issues/3173 and …

fix(source/service): disable node informer when not required

---

provider/aws/aws.go
provider/aws/aws_test.go

- added null pointer check when endpoints sizes do not match
This fix will help as well https://github.com/kubernetes-sigs/external-dns/pull/5459
Managed to capture null pointer with tests, but not in real cluster. 
Fixes #5634

fix(provider/aws): null pointer when records mailformed

---

README.md

As the usage of webhook expands, I think we want to add more information to the README file so that people know what to expect when adopting webhook providers. It's obvious material, but I'd rather give more guidance to users than false expectations. 
I want to provide more guidance to users and protect the project from possible legal issues.

docs: add information on external webhook usage

---

pkg/apis/externaldns/types.go
provider/cloudflare/cloudflare.go

Comments were merged getting separated into another PR; a piece went missing, that prevented them from getting properly set.
There's a bug on the current feature,

fix(cloudflare): set comments properly

---

source/node.go
source/node_test.go
source/pod.go
source/pod_test.go

- `--event` flag to work with sources
- pod
- node
Pod `event handler` not required nodeinformer. If there going to be a use case, we could add `nodeinformer` events handling as well.
Fixes #5274
-  [x] Yes, I added unit tests

feat(source): support --event flags with sources pod and node

---

source/service.go
source/service_test.go

- Changed `extractNodePortTargets` to also respect `exposeInternalIPv6` flag
- Modified all relevant tests to include both internal and external IPv6 addresses, to test the difference
- Added test for explicit enable of `--expose-internal-ipv6`
Fixes #5651

fix(source): respect --expose-internal-ipv6 flag on NodePort services

---

docs/flags.md
pkg/apis/externaldns/types.go
provider/awssd/aws_sd.go
provider/awssd/aws_sd_test.go

It fixes supports Service Discovery for AWS Cloud Map. However, the main challenge is that without real smoke tests against the API, bugs are undetectable. This is because the client Go SDK doesn't return errors for misconfigured filters.
Note the flag `--aws-zone-type` is not optional despite it should be. As with current implementation it must to be set to a value `public` or `private`.
Fixes #5675
Fixes #5167
Reproduced
Setting values to empty in filter will not work either
With the fix works without any issues

fix(provider/aws-sd): fix namespace type filtering

---

docs/tutorials/cloudflare.md
provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_test.go

This pull request migrates the regional services logic to the Cloudflare library v4 while retaining the old version for other functionalities like zones, custom hostnames, and DNS records. It introduces a redefined RegionalHostname struct (as done in #5615) and a new autoPagerIterator() function to convert the v4 library's "AutoPager" into a Go iterator, intended for broader use in list calls. The logic remains unchanged, with adjustments only to the API and associated structs.
Similar to #5609 
Iterative approach to #5540

refactor(cloudflare): use lib v4 for zone services

---

endpoint/domain_filter.go
internal/idna/idna.go
internal/idna/idna_test.go
plan/plan.go
provider/aws/aws.go
provider/zonefinder_test.go

- We need custom idna profile in multiple locations
- TXT records not deleted for idna affected records
- records with `*` not handled correctly 
- for aws provider on DryRun added early return to reduce nesting
Follow-up most likely
- AWS provider HostedZoneId should be just an ID, without `prefix`. Example terraform https://github.com/hashicorp/terraform-provider-aws/blob/47afa5c147c6c5efede000e47d5d42483a0da928/internal/service/route53/record.go#L980 and API https://docs.aws.amazon.com/Route53/latest/APIReference/API_ChangeResourceRecordSets.html
Fixes #5649
Fixes #5602
Current
With the fix
records added
records deleted
same for records with `*` and `_`

fix(endpoint): domains handling with idna

---

provider/zonefinder.go
provider/zonefinder_test.go

This PR fixes an overlooked usage of the old IDNA logic in `FindZone()` that still emits warning logs when parsing hostnames containing the `*` character. Although PR #5685 addressed this issue in some parts of the code by using a new IDNA profile that allows characters like `*`, one remaining path still uses the old profile, resulting in warning logs like:
`Failed to convert label “*” of hostname “*.example.com” to its Unicode form: idna: disallowed rune U+002A`
This PR updates the logic to consistently use the intended IDNA profile and avoid logging spurious warnings for wildcard hostnames.
This PR follows up on the changes in #5685 , which partially addressed unnecessary warning logs for hostnames with characters like `*`. However, the `FindZone()` function still uses the outdated IDNA …

fix(provider): IDNA awareness in the zone finder

---

docs/monitoring/metrics.md
internal/gen/docs/metrics/main_test.go
pkg/http/http.go
pkg/http/http_test.go
pkg/metrics/metrics.go
pkg/metrics/metrics_test.go
pkg/metrics/models.go
pkg/metrics/models_test.go

This PR refactors the metrics so that the request_duration_metric is configured in the same way as the other metrics.
While working on solving the AWS_CA_BUNDLE issue we had to refactor the request_duration_metric and it was decided to split the refactor off into it's own PR.
- [ x ] Yes, this PR title follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ x ] Yes, I added unit tests
- [ x ] Yes, I updated end user documentation accordingly

chore(metrics): refactor metrics to use common registry

---

source/endpoints_test.go
source/istio_gateway_test.go
source/istio_virtualservice_test.go

In this PR https://github.com/kubernetes-sigs/external-dns/pull/5708, while was doing smoke testing on real clusters, found, that some of the cases with selectors where not covered, as a results all tests where green, but on real cluster the change could lead to a bug. 
follow-up:
- slice PR https://github.com/kubernetes-sigs/external-dns/pull/5708

test(source/istio): add missing test cases

---

.github/workflows/lint.yaml
scripts/install-tools.sh

chore(deps): update golangci-lint version to v2.2.2

---

source/pod.go
source/pod_test.go
source/service.go
source/service_test.go

This PR adds transformers to the pod informers in the `pod` and `service` sources to reduce the resulting memory footprint.
As described in the issue, the pod informers currently lead to a large memory usage of the external-dns pods. As the controller only requires a few specific fields we can leverage transformers in the informers to greatly reduce the footprint.
In our environment this reduces the _average_ memory usage by ~10 times, and once using watch list (disabled by default) and the next client-go release, we now have a _peak_ memory usage 10 times smaller, greatly reducing our controller footprint.
This PR does not enable watchlist (but I'll raise a PR to optionally do so) as it is currently not really valuable without a fix in the next release of client-go.
Refs: #5595

feat(source): use transformers in pod informers to reduce memory footprint

---

go.mod
go.sum
provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_regional.go
provider/cloudflare/cloudflare_regional_test.go
provider/cloudflare/cloudflare_test.go

Upgrade cloudflare api library to v5 (only import path is modified).
Alias legacy cloudflare api library as `cloudflarev0`.
Remove alias for cloudflare api library v5.
Cloudflare api library changes its import path for each major version which requires a manual PR.
Removing the version in the alias module willl minimize changes for future PR.

chore(cloudflare): upgrade library to v5

---

charts/external-dns/CHANGELOG.md
charts/external-dns/README.md
charts/external-dns/templates/deployment.yaml
charts/external-dns/values.schema.json
charts/external-dns/values.yaml
scripts/helm-tools.sh

This PR introduces ability to configure `--annotation-filter` flag with `annotationFilter` helm value.
Both `labelFilter` and `annotationFilter` should be supported and be easily configurable with helm chart.
Our team is moving from bitnami chart to this one and this change would be useful for other teams who probably doing the same. This will help us to ensure smooth transition without breaking expectations.

feat(chart): add option to configure annotationFilter via dedicated helm value

---

charts/external-dns/tests/rbac_test.yaml

Adds RBAC tests for istio sources.
> RE the duplicate calls were you thinking of adding something like a singleflight wrapper?
I think the code already have `singleflight` https://github.com/kubernetes-sigs/external-dns/blob/master/source/wrappers/dedupsource.go. Unless I misunderstood the idea.
The problem I see at the moment, `istio-virtualservice` actually fully duplicates some of the `istio-gateway` logic with `ingresses`. So we may need to consider cleanup in the future `istio-virtualservice`
https://github.com/kubernetes-sigs/external-dns/pull/5743#issuecomment-3195820713

chore(helm): add rbac unit-tests for istio sources

---

README.md

Update the Kubernetes compatibility table in `README.md`.
There is a breaking change since `v0.18.0` with the switch to `endpointslices` (https://github.com/kubernetes-sigs/external-dns/pull/5493). See https://github.com/kubernetes-sigs/external-dns/pull/5493#issuecomment-3160760711.

docs(readme): update k8s compatiblity table

---

docs/annotations/annotations.md
source/annotations/annotations.go
source/istio_gateway.go

Documentation for istio ingress annotation, that was added while ago https://github.com/kubernetes-sigs/external-dns/pull/3842
https://github.com/kubernetes-sigs/external-dns/pull/5743#discussion_r2285018732

docs(istio): document ingress annotation

---

source/crd_test.go

Increase some timeout in CRD source unit tests.
Some tests randomly fails: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_external-dns/5781/pull-external-dns-unit-test/1962451651566505984

tests(source/crd): increase timeouts when it can randomly fails

---

provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_regional.go
provider/cloudflare/cloudflare_regional_test.go

In the cloudflare provider:
- Move the code in `AdjustEndpoints()` to add the provider specific regional key in a new func in `cloudflare_regional.go`.
- This new func set the endpoint's regional key when regional support is enabled and the record type is supported. If not it remove the key (if a user defined it in `DNSRecord` crd for example).
- always add the provider specific regional key in `addEnpointsProviderSpecificRegionKeyProperty()` when regional support is enabled (empty string if there is no corresponding regional hostname on cloudflare).
Improve consistency between the endpoints from sources and endpoints from the cloudflare provider in order to prevent false diff detection.
There is currently unneeded updates due to a missing provider specific regional key in …

fix(cloudflare): unnecessary record updates

---

docs/release.md
scripts/releaser.sh

1. Add a section on docker image pull
2. Improve CLI help
Consistent experience on release and less manual tasks.

docs(ci): improve release note template

---

provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_test.go

Migrate the cloudflare provider `ListRecords()` func to the new lib.
See #5540.

chore(cloudflare): migrate ListRecords() to new lib

---

endpoint/endpoint.go
endpoint/endpoint_test.go
source/endpoints.go
source/endpoints_test.go
source/istio_gateway_test.go
source/service.go
source/service_test.go
source/wrappers/dedupsource.go
source/wrappers/dedupsource_test.go

Deduplicate not just DNS names but targets as well
- deduplicate targets
- added tests
- added targets sorting, this will reduce a number of issues with DIFF related to target sorted/not-sorted
- follow-up https://github.com/kubernetes-sigs/external-dns/blob/master/source/istio_gateway.go#L197-L200
Fixes #5664

fix(endpoint): deduplicate targets

---

charts/external-dns/CHANGELOG.md
charts/external-dns/Chart.yaml
charts/external-dns/README.md

This PR updates the Helm chart for the [v0.19.0](https://github.com/kubernetes-sigs/external-dns/releases/tag/v0.19.0) release.
Closes #5793

feat(chart): Release for v0.19.0

---

pkg/apis/externaldns/binders.go
pkg/apis/externaldns/binders_test.go
pkg/apis/externaldns/types.go
pkg/apis/externaldns/types_test.go

- Introduces a `FlagBinder` interface with `KingpinBinder` and `CobraBinder` implementations.
- Adds an experimental Cobra code path:
- Hidden flag `--cli-backend [cobra|kingpin]`.
- Environment variable `EXTERNAL_DNS_CLI` as a secondary toggle.
- Default is Kingpin.
- CLI flag overrides the env.
- Implements a minimal `newCobraCommand(cfg *Config)` and binds a subset of flags.
It's a proposal to approach issue #5379. By using the `FlagBinder` interface we have the option to work on the migration to cobra and thoroughly test it, without impacting the user experience.
Once the migration from Kingpin to Cobra is done, we can switch the default behaviour with a safe fallback option.
If this proposition gets approved, I will continue to work on further flags.

feat(cli): add Cobra binder and backend switch

---

docs/advanced/import-records.md
docs/tutorials/externaldns-import-tutorial.md
mkdocs.yml

This PR adds a new tutorial document (externaldns-import-tutorial.md) that explains how to manage and import manually created DNS records into ExternalDNS using TXT records. It provides a step-by-step guide with examples for scenarios where records were created outside ExternalDNS but still need to be managed going forward.
Many users run into issues when they already have manually created DNS records (for example, for Istio Gateways or pre-existing A records) and want ExternalDNS to take ownership. Without proper TXT records, reconciliation can fail with errors like `response error StatusCode: 400`. This tutorial helps users understand how to safely import and manage such records, reducing confusion and avoiding misconfigurations.

docs(tutorials): import existing DNS records into ExternalDNS

---

controller/execute.go
controller/execute_test.go
source/wrappers/nat64source.go
source/wrappers/nat64source_test.go

- add the nat64 source only when nat64 networks are defined (--nat64-networks)
- parse nat64 networks when creating the source, not on every `Endpoints()` call
The NAT64 source do nothing when no nat64 networks are defined.

refactor(source/nat64): optional source & early prefixes parsing

---

provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_test.go

Add a default comment provider specific property with `cloudflare-record-comment` flag in `AdjustEndpoints()`.
Also change `TestProviderPropertiesIdempotency()` to test Comment, Region key & Custom hostnames properties.
Custom hostnames tests cases are missing because the `AdjustEndpoints()` don't add them based on remote api state (it only sort the hostnames in the property value).
I'll try to implement this in a future PR.
Fix https://github.com/kubernetes-sigs/external-dns/issues/5826

fix(cloudflare): infinite reconciliation loop with cloudflare-record-comment flag

---

source/wrappers/multisource_test.go

Deep copy endpoint in test cases in `testMultiSourceEndpoints()` before testing.
Fix a race condition in source/wrappers tests.
Before:
<details>
```
$ CGO_ENABLED=1 go test -race -count=100 ./source/wrappers/...
==================
WARNING: DATA RACE
Read at 0x00c000608c10 by goroutine 195:
sigs.k8s.io/external-dns/source/wrappers.sortEndpoints()
/external-dns/source/wrappers/source_test.go:30 +0x8e
sigs.k8s.io/external-dns/source/wrappers.validateEndpoints()
/external-dns/source/wrappers/source_test.go:67 +0x144
sigs.k8s.io/external-dns/source/wrappers.testMultiSourceEndpoints.func1()
/external-dns/source/wrappers/multisource_test.go:100 +0x444
testing.tRunner()
/go/1.25.1/libexec/src/testing/testing.go:1934 +0x21c
testing.(*T).Run.gowrap1()
/go/1.25.1/libexec/src/testing/testing.go:1997 …
```

test(source/wrappers): fix race condition

---

provider/cloudflare/cloudflare_test.go

Change `TestCloudFlareProvider_newCloudFlareChange()` to use a mockProdiver instead of a real one with fake credentials.
Also edit the way tests comments are generated.
Current implementation perform a query on cloudflare api as it use a real provider & cloudflare client which is not needed for this test.
This decrease cloudflare package test up to 800ms on my machine. (2,3s->1.5s)

test(cloudflare): mock provider for cf change tests

---

provider/pihole/pihole_test.go

Reduces the cyclomatic complexity of TestProvider from 43. The next highest is TestProviderV6 with a complexity of 43
Addresses #5419

refactor(pihole): reduce cyclomatic complexity of TestProvider

---

docs/registry/txt.md

This PR updates the documentation for the TXT registry to clarify how --txt-prefix and --txt-suffix behave with apex domains.
It removes potentially misleading examples and highlights the recommended configuration (--txt-prefix="%{record_type}.") to ensure correct TXT record creation under the same zone.
While reviewing #5850 , I noticed that some users are still confused about how to configure TXT registry options when managing apex domains.
I also tested the current examples from the docs, and found that TXT records could not be created as expected when using them with an apex domain.
Based on this, I believe the docs should be updated to prevent others from hitting the same issue.
That said, if I misunderstood the intended behavior, I apologize — please correct me if this change is not …

docs(txt-registry): improve formatting and examples for apex record

---

docs/tutorials/cloudflare.md
provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_test.go
source/annotations/annotations.go
source/annotations/provider_specific.go
source/annotations/provider_specific_test.go

This pull request adds support for Cloudflare's native Tags feature.
It introduces a new annotation, external-dns.alpha.kubernetes.io/cloudflare-tags, which allows users to specify a comma-separated list of key:value tags on a source resource.
The provider code has been updated to:
1. Parse this new annotation.
2. Include the tags in the payload for both CREATE and UPDATE API calls to Cloudflare.
3. Read existing tags from Cloudflare records to ensure the correct plan is calculated.
Currently, external-dns supports provider-specific metadata like comments for Cloudflare, but it lacks support for Tags. Cloudflare Tags are a powerful feature for resource management, allowing users to:
- Filter DNS records in the dashboard and via the API.
- Automate actions based on specific tags.
- Track …

feat(provider/cloudflare): add support for tags

---

.github/workflows/ci.yaml
Makefile

1. Switch CI to use [coveralls](https://coveralls.io/)
2. Rename job name from "Build" to "Test", since it calls `make test`
3. Upgrade resources, following https://github.com/kubernetes/test-infra/pull/35591
1. Fixes #5854
2. Speed-up CI

chore(ci): speed-up & coveralls

---

docs/tutorials/myra.md

This PR updates documentation about how to use ExternalDNS to use Myra Security DNS services using [Myra ExternalDNS webhook](https://github.com/Myra-Security-GmbH/external-dns-myrasec-webhook).
It includes info about the new `disable-protection` option and the newly published docker image.
To give more information how to use Myra Security DNS with K8s using ExternalDNS.

docs(myra): add info about protection option and docker image

---

pkg/metrics/models_test.go

Update test label to Go 1.25 in metrics and ensure workflow uses correct Go version. References kubernetes-sigs/external-dns#5869.

test: update goversion label to 1.25 in metrics test

---

docs/advanced/configuration-precedence.md
docs/annotations/annotations.md
mkdocs.yml

We may need some clarification around configuration order.
We may need to update release notes with change in flag behaviour if we could, as when `--service-type-filter` is specified, the external dns will only consider those **scoped** resources.
Relates https://github.com/kubernetes-sigs/external-dns/issues/5867

docs(advanced): configuration precedence
