CONTRIBUTING.md, OWNERS, code-of-conduct.md
solves https://github.com/kubernetes-incubator/external-dns/issues/2
=> Code of conduct and other important files

README.md
=> Add incubator information to README

docs/project-structure.md
=> Draft project structure documentation

README.md
Document the current status and next steps in the readme so others know what they can expect.
/cc @justinsb @ideahitme @iterion @hjacobs
=> Add notes about the current status and plan

Makefile
verify runs the same verification as the CI runs.
=> Add simple makefile, with `make verify` task

source/service.go, source/service_test.go
On AWS, the loadbalancer is / will be / should be set up in the
hostname.
=> Extract Status.LoadBalancer.Hostname from service annotations

README.md
* Travis Build status on master
* Coveralls Coverage Report on master
* Go report card on master
=> add useful badges to the readme

source/service_test.go, source/shared_test.go
=> create shared_test and scope service tests

controller/controller_test.go
This allows passing objects to the mock implementations which they will return or validate. This makes them a little more flexible to us.
=> make mock implementations more flexible by taking slices

source/ingress.go, source/ingress_test.go
Basic ingress implementation, basically doing the same thing as we did for services
=> ingress basic implementation

dnsprovider/google.go, source/ingress.go, source/service.go
fixes `gotip` on `master`
/cc @ideahitme
=> avoid shadowing the endpoint package

dnsprovider/google.go
when there are no changes to submit we shouldn't fail.
=> do not fail when changeset is empty

docs/initial-design.md, source/service.go, source/service_test.go
Fixes https://github.com/kubernetes-incubator/external-dns/issues/42
=> use alpha annotations

cloudbuild.yaml
Tag each image with the cmmit sha.
=> push image tagged with commit sha

docs/proposal/storage.md
/cc @linki @iterion @justinsb @Raffo
=> storage proposal v1

controller/controller_test.go, source/mock_source.go, source/mock_source_test.go
I'm going to need it for the MultiSource tests.
=> promote MockSource to source package

main.go, source/ingress.go, source/ingress_test.go, source/service.go, source/service_test.go
prerequisite to create a generic `NewSource("sourceName")` /cc @ideahitme
=> use constructor methods to create sources

dnsprovider/store.go, dnsprovider/store_test.go
So that we can use the CLI flag to lookup the DNS provider.
=> allow to register and lookup providers by name

dnsprovider/inmemory.go, dnsprovider/inmemory_test.go
Allows to create a zone in inmemory dns provider. Needed for testing
=> CreateZone for InMemory DNS provider

docs/tutorials/gke.md
Describes how to setup `external-dns` on GKE. I encourage you to try it out.
/cc @ideahitme @justinsb @ideahitme
=> add tutorial on how to use external-dns with GKE

provider/google.go
Makes it easier to identify updates in google.
=> list deletions first to make log output clearer

README.md
Makes the FAQ section more prominent in the README as it contains valueable information for early adopters.
=> move faq section upwards

internal/testutils/endpoint.go, provider/inmemory_test.go
this adds package with utility function for testing if two multisets of endpoints are same. Not the prettiest code, will gladly change it if you have any better idea how to compare two multi-sets of items 
/cc @linki
=> create internal testutils package

README.md, docs/faq.md
Some pretty lightweight fixes.
=> Edited README and FAQ

CHANGELOG.md
Starting a changelog.
PRs can add stuff in the top section. On release we just put a version on top.
Use the following keys
* Features
* Bug fixes
* UX improvements
=> add a CHANGELOG.md

docs/proposal/registry.md
=> adjust documentation as per latest discussion regarding registry/storage

controller/controller.go, main.go, pkg/apis/externaldns/types.go, pkg/apis/externaldns/types_test.go
useful and also needed to support https://github.com/wearemolecule/route53-kubernetes/blob/master/service_listener.go#L38
=> make interval between synchronizations configurable

controller/controller_test.go, endpoint/endpoint.go, endpoint/endpoint_test.go, internal/testutils/endpoint.go, plan/plan.go, plan/plan_test.go, provider/aws.go, provider/aws_test.go, provider/google.go, provider/google_test.go, provider/inmemory.go, provider/inmemory_test.go, provider/provider.go, source/ingress.go, source/ingress_test.go, source/mock_source.go, source/mock_source_test.go, source/multi_source.go, source/multi_source_test.go, source/service.go, source/service_test.go, source/shared_test.go, source/source.go
/cc @linki 
as per your suggestion moving out part of the another PR to the current one. Need this PR merged first
=> use pointer to endpoint via NewEndpoint initializer

provider/inmemory.go, provider/inmemory_test.go
This will allow us test components (e.g. controller) for the provider method invocation 
/cc @linki
=> inject callbacks

CHANGELOG.md, README.md, docs/tutorials/aws.md, docs/tutorials/gke.md, provider/aws.go, provider/aws_test.go, provider/google.go, provider/google_test.go, provider/provider.go, source/ingress.go, source/ingress_test.go, source/service.go, source/service_test.go, source/source.go
auto-detects whether to use CNAME or A records based on whether the Endpooint's target is an IP.
=> support hostnames as endpoint targets (CNAME support)

internal/testutils/endpoint.go, provider/inmemory.go
=> add testutils to compare changes, im provider allow to inspect changes 

endpoint/endpoint.go, endpoint/endpoint_test.go, provider/aws_test.go, source/ingress.go, source/ingress_test.go, source/service.go, source/service_test.go, source/source.go
Moved sanitize part to the endpoint init func. Let me know if you think this is premature;) 
/cc @linki
=> endpoint sanitize dns in the init func 

docs/tutorials/aws.md, provider/aws.go, provider/aws_test.go
first attempt to improve the test code for the aws provider. drops most of the hosted zone functions as they are not needed. ~~needs go1.8 for sorting stuff.~~ tests are green against the stub as well as against the real AWS api (just need to change the hosted zone ID accordingly)
=> improve quality of test code

main.go, pkg/apis/externaldns/types.go, source/multi_source.go, source/multi_source_test.go, source/store.go, source/store_test.go
https://github.com/kubernetes-incubator/external-dns/issues/148
=> cmd flags fixes, fix the bug with multi source

controller/controller.go
Addresses #103.
Add minimal logging (planned changes in central controller to not repeat logging in all providers).
```
INFO[0001] Creating  nginx.external-dns-test.example.org -> a123-1598269060.eu-central-1.elb.amazonaws.com .. 
INFO[0001] Deleting CNAME nginx1.external-dns-test.example.org -> a456-1433401422.eu-central-1.elb.amazonaws.com .. 
INFO[0001] Deleting A via-ingress.external-dns-test.example.org -> 54.93.245.70 ..
=> #103 log calculated changes

CHANGELOG.md
=> fixes the description of the fqdn flag in the changelog

registry/txt.go, registry/txt_test.go
=> change owner key in txt records

CHANGELOG.md, controller/controller.go, endpoint/endpoint.go, internal/testutils/endpoint_test.go, plan/plan.go, plan/policy.go, provider/aws.go, provider/google.go, registry/noop.go, registry/registry.go, registry/txt.go, source/ingress.go, source/service.go, source/service_test.go
https://github.com/kubernetes-incubator/external-dns/issues/103#issuecomment-296661789
=> first effort to improve logging in external-dns to provide with basic needed logging 

controller/controller.go, endpoint/endpoint.go, internal/testutils/endpoint_test.go, main.go, provider/aws.go, provider/google.go, registry/registry.go
=> minor improvements to logging

plan/policy.go
as discussed in https://github.com/kubernetes-incubator/external-dns/issues/180
=> policy: remove confusing log line

README.md, docs/contributing/getting-started.md, docs/faq.md, docs/initial-design.md, docs/tutorials/aws.md, docs/tutorials/gke.md, docs/tutorials/nginx-ingress.md
=> adjust docs before the v0.3.0 release

docs/faq.md
The link to `aws.md` was wrong..
=> fix link to AWS tutorial

README.md, docs/tutorials/aws.md, docs/tutorials/gke.md, docs/tutorials/nginx-ingress.md
=> align more docs with the current release

README.md
adds a badge pointing to godoc
=> chore: add godoc badge

README.md, pkg/apis/externaldns/types.go
=> Make it clearer that all flags are settable by env var

CONTRIBUTING.md
=> CONTRIBUTING needs a link to the CLA-FAQ.

main.go, provider/inmemory.go, provider/inmemory_test.go
=> remove inmemory provider complex interface

README.md, docs/contributing/sources-and-providers.md
Adds docs on how to write sources and providers.
=> docs: explain the concept behind sources and providers

docs/tutorials/cloudflare.md
#139 Fix missing Cloudflare tutorial
=> Cloudflare Tutorial

.zappr.yaml
This is needed for CDP to be able to push.
=> add zappr file in order to push to pierone

Dockerfile, Makefile, delivery.yaml
Build docker image using multi-stage builds on Zalando's CDP
=> Build docker image using multi-stage builds on Zalando's CDP

delivery.yaml
squash the docker image layers
=> squash the docker image layers

CHANGELOG.md, docs/tutorials/azure.md, docs/tutorials/cloudflare.md, docs/tutorials/digitalocean.md
updates the docs to the latest version. Also locks in changelog.
=> update docs to the v0.4.0 release

docs/faq.md
Which permissions are required for ExternalDNS?
=> faq: add gke permissions to the faq

README.md, docs/faq.md, docs/initial-design.md, docs/proposal/registry.md, docs/tutorials/aws.md, docs/tutorials/gke.md, docs/tutorials/nginx-ingress.md
several updates to the docs for the latest release. /cc @ideahitme
=> docs: update documented version to v0.4

provider/aws.go, provider/aws_test.go
Wildcard domains (*.abc) are stored as "\\052.abc" in Route53,
which confuses external-dns as it tries to recreate entry over and
over.
It is confusing, but documented behaviour of Route53:
http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DomainNameFormat.html?shortFooter=true#domain-name-format-asterisk
=> Fix for wildcard domains handling in Route53

docs/faq.md
Adds a FAQ entry on how to configure Sources via env vars.
=> document how to configure sources via env vars

README.md
This adds a link to the video (https://www.youtube.com/watch?v=9HQ2XgL9YVI) to show external DNS in action.
=> Added link to video demo in README

CHANGELOG.md, provider/cloudflare.go, provider/cloudflare_test.go
Closes #360.
@MichielDeMey, would you mind checking if it fixes your issue?
=> Cloudflare: Disable proxy mode for TXT and others

docs/tutorials/infoblox.md
=> Fix minimum version of external-dns container in InfoBlox tutorial

docs/tutorials/hostport.md
Added a small example on using the new feature, with a usecase example and some motivation.
I went with the example, that made me write the feature, specifically exposing Kafka to external access.
I dont think its too specific and it should be very easy for somebody to adapt it their usecase. 
Let me know if its too specific. And any other comments are also welcome.
=> Added HostPort feature docs

.travis.yml, registry/txt.go, source/fake.go
Linting failed here: https://travis-ci.org/kubernetes-incubator/external-dns/jobs/309953426
=> Avoid shadowing package name

CONTRIBUTING.md
ref: kubernetes/kubernetes#57689
=> Follow CLA doc to kubernetes/community

docs/faq.md
There were no documentation describing how to use the annotation-filter
parameter
=> Add documentation about annotation-filter

README.md
In response to https://github.com/kubernetes-incubator/external-dns/issues/511
=> Update the roadmap to the lastest info

provider/designate.go, provider/designate_test.go
This will finally fix Openstack Designate provider 
I merged the Openstack PR but afterwards I realized the tests from Travis didn't pass, due to changes in our base code. 
I changed only the necessary part which affected Travis from successfully testing and building.
=> Fix for Openstack Designate and tests

docs/tutorials/gke.md
=> RBAC permissions

docs/tutorials/pdns.md
Add documentation for the PDNS provider, including:
* Sample deployment.yaml
* Requirements
* Testing and verification
=> Add docs for pdns provider

provider/pdns.go, provider/pdns_test.go
Multi targets for PowerDNS provider and fixing tests
=> Fix multi targets PowerDNS

.travis.yml
Let's see if this does anything
=> Give linters more time to do their work

provider/pdns.go, provider/pdns_test.go
=> Fixes CNAME support in the PowerDNS provider

docs/tutorials/aws.md
=> AWS IAM Instance Profile

CHANGELOG.md, docs/faq.md, docs/tutorials/aws.md, docs/tutorials/azure.md, docs/tutorials/cloudflare.md, docs/tutorials/digitalocean.md, docs/tutorials/dyn.md, docs/tutorials/gke.md, docs/tutorials/hostport.md, docs/tutorials/infoblox.md, docs/tutorials/nginx-ingress.md, docs/tutorials/pdns.md, docs/tutorials/public-private-route53.md
* Add changes to the changelog
* Update version in docs
/cc @njuettner
=> Bump version to v0.5.1

Gopkg.lock, Gopkg.toml, docs/tutorials/azure.md, provider/azure.go, provider/azure_test.go
This change adds MSI support for Azure provider.
Fixes: https://github.com/kubernetes-incubator/external-dns/issues/577
=> Add Azure MSI support

CHANGELOG.md, README.md, docs/faq.md, docs/tutorials/aws-sd.md, docs/tutorials/aws.md, docs/tutorials/azure.md, docs/tutorials/cloudflare.md, docs/tutorials/digitalocean.md, docs/tutorials/dyn.md, docs/tutorials/gke.md, docs/tutorials/hostport.md, docs/tutorials/infoblox.md, docs/tutorials/nginx-ingress.md, docs/tutorials/pdns.md, docs/tutorials/public-private-route53.md
* Add recent changes to the changelog
* Update version in docs
=> Bump version to v0.5.2

provider/aws.go
=> Print a message if no hosted zones match (aws provider)

CHANGELOG.md, README.md, docs/faq.md, docs/tutorials/aws-sd.md, docs/tutorials/aws.md, docs/tutorials/azure.md, docs/tutorials/cloudflare.md, docs/tutorials/digitalocean.md, docs/tutorials/dyn.md, docs/tutorials/gke.md, docs/tutorials/hostport.md, docs/tutorials/infoblox.md, docs/tutorials/nginx-ingress.md, docs/tutorials/pdns.md, docs/tutorials/public-private-route53.md
* Add recent changes to the changelog
* Update version in docs
/cc @linki
=> Bump version to v0.5.3

plan/plan.go, plan/plan_test.go
Should fix causing problems by running DNS updates #561 and #480
Signed-off-by: Nick Jüttner <nick@juni.io>
=> annotation with upper-case hostnames block further updates

.travis.yml, delivery.yaml, pkg/apis/externaldns/types.go, pkg/apis/externaldns/types_test.go, provider/google.go, provider/google_test.go, registry/txt.go, registry/txt_test.go
Fix for https://github.com/kubernetes-incubator/external-dns/issues/605
Could you have a look please?
/cc @peterbale @plarivee
=> Only store endpoints with their labels in the cache

CHANGELOG.md, docs/faq.md, docs/tutorials/aws-sd.md, docs/tutorials/aws.md, docs/tutorials/azure.md, docs/tutorials/cloudflare.md, docs/tutorials/digitalocean.md, docs/tutorials/dyn.md, docs/tutorials/gke.md, docs/tutorials/hostport.md, docs/tutorials/infoblox.md, docs/tutorials/nginx-ingress.md, docs/tutorials/pdns.md, docs/tutorials/public-private-route53.md
* Add recent changes to the changelog
* Update version in docs
/cc @linki
=> Bump version to v0.5.4

.travis.yml, Gopkg.lock, Gopkg.toml
We can remove modifying the deadline for gometalinter
PR https://github.com/kubernetes/repo-infra/pull/75 got merged
/cc @linki
=> Remove sed deadline from travis.yml

provider/aws.go
See the conversation in https://github.com/kubernetes-incubator/external-dns/pull/592
=> fix log message for #592 when no updates in hosted zones

provider/dyn.go
As per https://help.dyn.com/managed-dns-api-rate-limit/ clients
should idle for at least a minute.
Fix a few typos, more debug logging.
=> Retry calls to dyn on ErrRateLimited

main.go, provider/aws_sd.go
potential fix for issue #670 (still pending CLA agreement and verification)
=> adding assume role to aws_sd provider

Gopkg.lock, Gopkg.toml, provider/exoscale.go
we fixed one or two things in the dns section.
=> exoscale: bump version to 0.11

provider/dyn.go, provider/dyn_test.go
The only thing preventing use of a smaller interval is the API request
limit. Caching records by the zone's serial number would let users set a
smaller interval and still not hit Dyn's request limit if there aren't
any changes to the zone since the last time external-dns has run.
In a dynamic setting bigger interval is still the main throttling
mechanism.
=> Dyn: cache records per zone using zone's serial number

CHANGELOG.md, docs/tutorials/linode.md
Updating changelog for new release v0.5.5
=> Updating changelog for new release v0.5.5

Gopkg.lock, controller/controller.go
Related to issue #629, I want to know when there are source or registry errors, to trigger investigation (using existing logging).
=> Add generic metrics for Source & Registry Errors

docs/tutorials/alibabacloud.md
In Alibaba Provider , we need time zone info to refresh sts token. So add it to pod through volume.
=> Alibaba Cloud Provider add zone info to deployment

registry/txt.go
=> Don't erase endpoints labels

CHANGELOG.md
=> Update changelog to v0.5.8

CHANGELOG.md
=> Fix wrong entry in changelog

docs/tutorials/azure.md
I added the new possibility for deployments without cluster access from #663 and also tried to improve the general Azure documentation a bit.
=> Update Azure documentation

docs/tutorials/alibabacloud.md, provider/oci.go
Remove duplicated words:
1. docs/tutorials/alibabacloud.md
2. provider/oci.go
=> Remove duplicated words

provider/alibaba_cloud.go, provider/alibaba_cloud_test.go
Fix multi-level domain record bug.
Url like `a.b.c.container-service.top` may cause some error, this PR fix it .
=> Alibaba Cloud Provider Fix Multiple Subdomains Bug

docs/faq.md
=> Add Traefik to the supported list of ingress controllers.

docs/tutorials/pdns.md, provider/pdns.go, provider/pdns_test.go
Implements feature request #554
=> PowerDNS: Add DomainFilter support

delivery.yaml
=> Update delivery.yaml to new format

CHANGELOG.md
https://github.com/kubernetes-incubator/external-dns/releases/tag/v0.5.9
=> Changelog v0.5.9

pkg/apis/externaldns/types.go, pkg/apis/externaldns/types_test.go, source/crd.go
Fixes #773 
- Change default apiversion of DNSEndpoint
- Add error to output CRDClient
=> Change default apiversion of crd

README.md
Notes that Linode support was added in 0.5.5
=> update README to include Linode on the 0.5 roadmap

provider/infoblox.go
=> Improve errors in Records() of infoblox provider

docs/tutorials/rfc2136.md
- Adding bind config for RFC2136 tsig updates for externaldns.
- All configs verified
=> adding config for bind for tsig

docs/tutorials/azure.md
there was an unexpected comma in json used as custom configuration file
=> fix json syntax error - typing error

docs/tutorials/coredns.md
=> Update coredns tutorial with RBAC manifest (see #791)

plan/plan.go
Makes for clearer log messages.
=> Implement Stringer for planTableRow

provider/rfc2136.go
Fix for issue #811. I've done some testing and this does not seem to have any adverse effects.
Please review and approve.
=> Issue #811 - RFC2136 seems to require one IP Target per RRSET

provider/alibaba_cloud.go
Fix private zone dns record does not work
=> Fix private zone dns record does not work

docs/tutorials/azure.md
Solves https://github.com/kubernetes-incubator/external-dns/issues/813
=> docs(azure): better security granuality concerning external dns service principal

docs/faq.md
So we don't lose the answers. /cc @njuettner
=> Add questions from slack to the FAQ

docs/tutorials/aws.md
I got stuck here and opened #865 because I thought it was a bug. I hope this will help others set it up correctly the first time.
=> Improve documentation regarding Alias

CHANGELOG.md
tentative changelog for v0.5.10
=> Update changelog for v0.5.10

docs/faq.md
That's just some quick Stackenblochen on the `faq.md` file that I was reading.
=> Fixes some style in the faq.md file

provider/rfc2136.go
=> Fixed typo in debug output

CHANGELOG.md
Introduces changes for external-dns v0.5.11
Updates the changelog, probably forgotten 😄
=> Changelog for v0.5.11

docs/tutorials/aws.md
Trying to make the wording less vague here.
=> Clarify that hosted zone identifier is to be used

docs/tutorials/aws.md
This PR is a comment about "Multiple DNS names per Service" setting.
=> Added description for multiple dns name

provider/rfc2136.go
=> set log level to debug when axfr is disabled

CHANGELOG.md, README.md
- Introduces changes of external-dns v0.5.12
=> Release v0.5.12

provider/infoblox.go
=> Reduce verbosity of infoblox provider logs

docs/tutorials/aws.md
While reading I was asking myself this question so I thought it would be smart to pass to another guy who will read it.
=> describe how to check if your cluster has a RBAC

provider/aws.go, provider/aws_test.go
This addresses issue #905 and potentially #891 
For each pass of the AWS Provider's ApplyChanges, we will collect the zones and respective resource records once.
To optimize away the entire Controller loop would require either changes to the public APIs or determining the hosted zone of the AWS Alias when we create the endpoint. I wasn't sure if it was valid to compute this at construction time.
The other odd thing I realized the Controller loop may use the cached endpoints from Registry while the AWS Provider will process them against a fresh set of endpoints. If we went with a single view of the world where its all cached or all fresh, then computing the hosted zone during construction makes perfect sense.
=> Streamline AWS ApplyChanges

CHANGELOG.md
=> Release v0.5.13

docs/faq.md
This PR adds a few comments on docker images and tags, with the goal to be even more transparent with the community.
Closes #795
=> Add docker image faq

CHANGELOG.md
=> Changelog for v0.5.14

Dockerfile
=> Install ca-certificates

provider/rfc2136.go
=> Log RR adds/deletes as Info in provider/rfc2136

source/service.go, source/service_test.go
fix https://github.com/kubernetes-incubator/external-dns/issues/602
=> 602 nodeport trafficpolicy

CHANGELOG.md
=> Changelog v0.5.15

.travis.yml, Dockerfile, Dockerfile.mini
Chore: Bumping up the versions of Go and golangci-lint
=> Update Go version and golangci-lint to the latest release

Dockerfile, Dockerfile.mini
@njuettner Fixes the docker build.
=> Add bzr to build container for gocheck

CHANGELOG.md
@njuettner changelog for v0.5.16
=> Update changelog for v0.5.16

Dockerfile, Dockerfile.mini
This is a follow up of PR #1148
=> update versions and remove unnecessary files in Dockerfile

go.mod, go.sum
Update the AWS go SDK to support AWS IAM for Service Accounts
=> Updated AWS SDK to v1.23.12

go.mod, go.sum
Fixes #1181
Update the AWS SDK to support Web Identity providers for IAM credentials
=> Updated AWS SDK version

go.mod, go.sum, provider/exoscale.go, provider/exoscale_test.go
As #1001 added a  `context.Context`, let's use it. /cc @FaKod
=> exoscale: add context support

docs/tutorials/aws-sd.md
Submitting to update the tutorial with RBAC details and include wording that the instance profile requires permissions.
Also happy to add wording to include the AWS_REGION variable as [suggested](https://github.com/kubernetes-incubator/external-dns/issues/584#issuecomment-394108253) before merging if this is desired.
=> Add RBAC manifest, update wording around IAM policy

docs/tutorials/gke.md
Seems like there was attempts to fix it but change didn't make it to master
=> #582: Unknown Serviceaccount error

docs/tutorials/designate.md
* extend the external-dns deployment to work within a RBAC enabled
environment
* add short hint how to mount/use/trust self-sign certificates
=> docs/designate: add snippet for rbac env

docs/tutorials/rdns.md
=> update broken links to RDNS

.github/workflows/labeler.yml
* Drop adding labels when using fork
=> Drop labeler when forking

provider/aws.go
https://github.com/kubernetes-sigs/external-dns/issues/1265
=> Add me-south region to canonicalHostedZones

docs/ttl.md, docs/tutorials/rfc2136.md
=> Improve RFC2136 documentation.

main.go, pkg/apis/externaldns/types.go, provider/azure.go, provider/azure_test.go
=> feat(Azure): support specifying user assigned identity\'s clientID to authenticate

docs/tutorials/vinyldns.md
Make registry txt usage more clear
=> Update vinyldns docs

OWNERS
Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>
=> resource was moved

Makefile
Cloudbuild version as docker tag
=> Use cloudbuild tag as version in Makefile

CHANGELOG.md
Add the Changelog for the next version.
=> Add changelog for v0.5.18

README.md, docs/tutorials/gke.md
A demo app deployment with external-dns integration on Google Cloud Platform GKE cluster, featuring CloudDNS + User permission mapping
=> A How-to of a working GCP GKE app demo

CHANGELOG.md
changelog for the next version.
=> Add changelog for v0.7.0

README.md
Add info on maintainers as mentioned in https://github.com/kubernetes-sigs/external-dns/issues/1317 
/cc @njuettner
=> Add first maintainers in list.

Dockerfile
Update the alpine base image to include security patches
=> Bump alpine base image to 3.11.5

go.mod, go.sum
This resolves issues reported within `miekg/dns` module: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMMIEKGDNS-537825
=> Upgrade github.com/miekg/dns to v1.1.25

kustomize/external-dns-clusterrole.yaml, kustomize/external-dns-clusterrolebinding.yaml, kustomize/external-dns-deployment.yaml, kustomize/external-dns-serviceaccount.yaml, kustomize/kustomization.yaml
Closes #1614 
This PR adds a plain kustomize base for ExternalDNS. It is intended to be customized before being used. 
/cc @ohauer
=> Add kustomize base

docs/tutorials/linode.md
This PR updates a link from Linode classic manager to Linode cloud manager.
=> Update link for linode cloud manager

docs/tutorials/designate.md
=> Fix Designate doc

source/gateway.go, source/virtualservice.go
=> add event handler for istio gateway and virtualservice source

CHANGELOG.md, docs/tutorials/akamai-fastdns.md, docs/tutorials/azure.md, docs/tutorials/dnsimple.md, docs/tutorials/dyn.md, docs/tutorials/exoscale.md, docs/tutorials/externalname.md, docs/tutorials/hostport.md, docs/tutorials/oracle.md, docs/tutorials/vultr.md
Fixed typos in the tutorial sections
=> Docs: Fixed typos

Makefile, internal/config/config.go, internal/testutils/init.go, provider/scaleway/interface.go, provider/scaleway/scaleway_test.go, source/node_test.go
=> add license header check to the CI

CHANGELOG.md, docs/tutorials/cloudflare.md
=> Add Cloudflare documentation on use of `--zone-id-filter`

.github/pull_request_template.md
This is a followup to pull request #1767. I would like to see checklist added to the pull request template again, but simply remove the CHANGELOG update item from the checklist.
=> Update pull requests template

docs/tutorials/kube-ingress-aws.md
fixing ingress-controller .yml broken link
=> fix ingress-controller yaml link

go.mod, provider/hetzner/hetzner.go, provider/hetzner/hetzner_test.go
update hetzner dns library version, add hetzner requirements for updating records, better logging
=> Hetzner: fix records update

kustomize/kustomization.yaml
=> Bump externalDNS image in kustomization.yaml

docs/tutorials/istio.md
Signed-off-by: 杨阳 10014842 <yangyang1@zte.com.cn>
Fixes #ISSUE
**Checklist**
=> Add namespace for httpbin-gateway in istio doc

docs/contributing/getting-started.md, docs/contributing/sources-and-providers.md
- Fixed broken link in https://github.com/kubernetes-sigs/external-dns/blob/master/docs/contributing/getting-started.md for workflow folder
- Fixed broken link in https://github.com/kubernetes-sigs/external-dns/blob/master/docs/contributing/sources-and-providers.md for CRD source
Fixes #ISSUE
**Checklist**
=> corrected broken link in multiple docs

docs/tutorials/rfc2136.md
- Fixes RBAC ClusterRole  (#961)
- Fixes inconsistency within the document
**Checklist**
=> Fix RFC2136 tutorial

docs/contributing/getting-started.md, docs/tutorials/hostport.md, docs/tutorials/kube-ingress-aws.md, source/httpproxy.go
=> fix some typos

docs/tutorials/akamai-fastdns.md
Documentation for fast dns updated
Fixes #1878 
**Checklist**
=> fix for 1878

controller/controller.go
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>
=> Fix typo in comment

scripts/releaser.sh
This is needed to generate better release notes.
/cc @njuettner
=> Update release script to include squashed commits

docs/faq.md
Adds documentation on how to use external-dns in kubernetes with the new traefik helm chart.
Fixes #1940
**Checklist**
=> Add info in FAQ on how to enable new traefik chart

go.mod, go.sum
Fixes https://github.com/kubernetes-sigs/external-dns/issues/1998 
ran
```
go get istio.io/client-go@1.7.8
go get istio.io/api@1.7.8
```
=> updated to latest Istio 1.7 libs

docs/faq.md, docs/tutorials/public-private-route53.md
Update the document related to `--annotation-filter`.
Mentioned in #1100.
=> Document annotation-filter usage

OWNERS
As discussed with @njuettner adding myself as a reviewer.
**Checklist**
=> Add seanmalloy As Reviewer

docs/release.md
Closes https://github.com/kubernetes-sigs/external-dns/issues/1934
/cc @njuettner
=> Add release conventions

.github/labeler.yml, docs/tutorials/bluecat.md
Add documentation for TLS Verification, and setup GitHub labeling for Bluecat provider
Relates to #2023 and #2052
**Checklist**
=> Bluecat documentation

README.md, docs/tutorials/bluecat.md
* Updated with v0.8.0 details
* Document getting credentials via environment variables
**Checklist**
=> docs: update bluecat tutorial

README.md
The README was wrongly mentioning that v0.7 is the latest release.
/cc @njuettner
=> Update README to mention v0.8 release

docs/tutorials/gke.md
Update GKE example with most recent version, which we are running in production
**Checklist**
=> update for latest version

docs/tutorials/scaleway.md
Updated external-dns version to latest version in example.
Fixes #ISSUE
**Checklist**
=> updated external-dns version to latest

scripts/update_route53_k8s_txt_owner.py
Clean up extra spaces, although these errors are not important, they affect the code specification.
Fixes #ISSUE
Clean up extra spaces, although these errors are not important, they affect the code specification.
**Checklist**
=> Clean up extra spaces

docs/faq.md
This simple PR provides an example in the FAQ as to how to provide a comma separated list of values to filter annotations with the "in" keyword
**Checklist**
=> Provide example of multiple values for "in" filter

kustomize/kustomization.yaml
This bumps kustomize to the latest released version
/cc @njuettner
=> bump kustomize version to v0.9.0

.github/workflows/codeql-analysis.yml
This PR adds an action for CodeQL scanning. It should likely help finding security bugs in this project.
=> Add CodeQL support

kustomize/kustomization.yaml
Updated kustomize version in yaml file
Fixes #2260 
**Checklist**
=> updated kustomize version

README.md
This removes the version from readme that we otherwise have to bump every time we do a release.
=> Remove version from readme

charts/external-dns/Chart.yaml, charts/external-dns/templates/deployment.yaml
Fixes https://github.com/kubernetes-sigs/external-dns/issues/2325
**Checklist**
=> Add registry as a flag for helm chart

charts/external-dns/Chart.yaml, charts/external-dns/templates/deployment.yaml
helm chart respect registry value if not equal to txt
Fixes #ISSUE
**Checklist**
=> helm chart respect registry value if not equal to txt

OWNERS
Add @seanmalloy as an approver. I discussed with the @Raffo and @njuettner in Slack.
**Checklist**
=> Add seanmalloy as an approver

source/openshift_route.go
The PR adds an event handler to the OpenShift Route source so these resources behave as expected when --events is enabled.
**Checklist**
=> Add event handler for OpenShift Route source

kustomize/kustomization.yaml
This bumps the kustomize version to v0.10.2.
/cc @njuettner
=> bump kustomize to v0.10.2

go.sum
The master branch is broken due to a missing update to go.sum. I enabled requiring update for PRs, but we need this to fix master.
=> Fix build by fixing go.sum

Dockerfile
Signed-off-by: Cyril Corbon <corboncyril@gmail.com>
Bump alpine version to 3.15
**Checklist**
=> chore(dockerfile): bump alpine version to 3.15

charts/external-dns/Chart.yaml, charts/external-dns/templates/deployment.yaml, charts/external-dns/values.yaml
Add txtSuffix value to Helm Chart. Also checks for txtPrefix.
=> Add txtSuffix value to Helm chart

main.go, source/ambassador_host.go, source/contour_httpproxy.go, source/contour_httpproxy_test.go, source/ingress.go, source/ingress_test.go, source/istio_gateway.go, source/istio_gateway_test.go, source/istio_virtualservice.go, source/istio_virtualservice_test.go, source/kong_tcpingress.go, source/kong_tcpingress_test.go, source/node.go, source/node_test.go, source/openshift_route.go, source/openshift_route_test.go, source/pod.go, source/pod_test.go, source/service.go, source/service_test.go, source/store.go, source/store_test.go
Simple and straightforward way to fix issue #2145.
**Checklist**
=> Pass stop channel to informer factory instances

.github/workflows/release-chart.yaml
This PR fixes the chart CI issue with specific characters in the release notes.
**Checklist**
=> Fix CI release notes generation

README.md, docs/tutorials/nodes.md
This PR adds a small tutorial about using nodes as source.
=> ADD: added node source doc

docs/tutorials/azure.md
Current documentation for Azure is outdated and does not work with Kubernetes 1.22
**Checklist**
=> Updated tutorial to support Kubernetes 1.22

docs/tutorials/alibabacloud.md, docs/tutorials/aws.md, docs/tutorials/azure-private-dns.md, docs/tutorials/azure.md, docs/tutorials/dyn.md, docs/tutorials/exoscale.md, docs/tutorials/gke.md, docs/tutorials/public-private-route53.md, docs/tutorials/ultradns.md
=> Fix ingress formal error

kustomize/kustomization.yaml
Updates the Kustomize version now that the images for v0.12.0 are pullable.
/cc @njuettner
=> Update kustomize version to v0.12.0

docs/faq.md, docs/tutorials/hostport.md
A few loosely-related improvements to the NodePort/hostPort docs.
**Checklist**
=> Docs: Improve NodePort and hostPort mentions in FAQ

.github/dependabot.yml
The YAML in master is wrong. 
/cc @njuettner
=> fix dependabot.yml intendation

.github/dependabot.yml
dependabot will create PR for us
other: fix typo for github-actions
Fixes #ISSUE
**Checklist**
=> ci: update docker automatically

OWNERS
This PR adds @szuecs to the owners. 
I hope that's enough to approve/merge PRs, but let's see 😄 
EDIT: It looks like there was a problem adding Sandor to the org, following up myself. 
/cc @njuettner
=> updates owners to add szuecs

kustomize/kustomization.yaml
Bumps kustomize to latest release.
cc @njuettner 
**Checklist**
=> Update kustomization.yaml to v0.12.2

kustomize/kustomization.yaml
Part of the normal release process, this PR updates the kustomize tag to v0.13.1.
/cc @njuettner
=> Update kustomize tag to v0.13.1

docs/tutorials/tencentcloud.md
Update the document for Tencent provider.
1. Update the release version and image in document.
2. Update the configuration methods of different network entries in the API.
**Checklist**
- [*] End user documentation updated
=> update the document for Tencent provider.

source/kong_tcpingress_test.go
Fix a minor typo.
**Checklist**
=> Fix minor typo

go.mod, go.sum, provider/gandi/gandi.go
Simple bump of go-gandi to v0.5.0. 
This version bring few refactoring and add pagination support for list methods.
Fixes #2943
=> bump go-gandi to v0.5.0

docs/tutorials/azure-private-dns.md
Signed-off-by: Pulak Kanti Bhowmick <pkbhowmick007@gmail.com>
Fixes #ISSUE
**Checklist**
=> Update ingress-nginx installation guide for azure private dns

provider/alibabacloud/alibaba_cloud.go
Signed-off-by: Shuwei Hao <haoshuwei24@gamil.com>
Set request scheme to "https" (default http) for alibabacloud provider to make it more security
Fixes #3156
**Checklist**
=> Set request scheme to "https" (default http) for alibabacloud provider

provider/infoblox/infoblox.go
Signed-off-by: Greg Sidelinger <sidelig@nationwide.com>
Fixes #ISSUE
**Checklist**
=> Log when infoblox provider deletes a record at info

docs/ttl.md
Adds CloudFlare provider to docs
**Checklist**
=> Fix documentation for CloudFlare TTL

Dockerfile, Makefile
Bump alpine version to 3.17
**Checklist**
=> chore(dockerfile): bump alpine version to 3.17

docs/tutorials/gke.md
Updated the backend.service.name in the Ingress resource to match the name used in the Service created earlier.
Corrected the GKE tutorial.
Updated the backend.service.name in the Ingress resource to match the name used in the Service created earlier.
**Checklist**
- [N/A ] Unit tests updated
- [ X] End user documentation updated
=> Minor correction in GKE tutorial

kustomize/kustomization.yaml
Bumps Kustomize to v0.13.2 which is the new release.
=> updates kustomize with newly released version

.github/workflows/gh-workflow-approve.yaml
This PR fixes incorrect syntax in the GH action workflow approval causing it to fail.
**Checklist**
=> Fixed bad syntax in GH action workflow approval

charts/external-dns/Chart.yaml
Updated path for icon present in Chart.yaml
Fixes #ISSUE
**Checklist**
=> updated icon image path

docs/contributing/crd-source/dnsendpoint-aws-example.yaml
Provide an example configuring a more complex DnsEndpoint resource with AWS specific configurations.
=> [AWS] Include DnsEndpoint example with AWS provider specifics

plan/plan.go
Simplifies the data structure used by the planner.
/kind cleanup
**Checklist**
=> Simplify planner's data structure

docs/tutorials/azure.md
Replaced old annotation:
annotations:
kubernetes.io/ingress.class: nginx
with new one:
ingressClassName: nginx
Fixes #ISSUE
**Checklist**
=> Updated new annotation : ingressClassName: nginx

docs/tutorials/azure.md
=> Added video tutorial in azure.md for using Azure DNS

kustomize/kustomization.yaml
Bump kustomize version to the latest release.
/cc @szuecs
=> Bump kustomize version to latest (v0.13.5)

docs/tutorials/azure.md
Very minor typo update to azure.md
Fixes #ISSUE
**Checklist**
=> Very minor typo Update to azure.md

OWNERS
Per the requirements in https://github.com/kubernetes/community/blob/master/community-membership.md :
[x] member for at least 3 months
[x] Primary reviewer for at least 5 PRs to the codebase
#3285, #3174, #3201, #3104, #3589,
#3590, #3295, #3263, #3297, #2553
[x] Reviewed or merged at least 20 substantial PRs to the codebase
#3285, #3174, #2157, #3261, #3201,
#3297, #2461, #3546, #3589, #3588,
#3590, #3607, #3600, #3603, #3590,
#3295, #3263, #3263, #3640, #3222,
#2054, #2553, #3104,
[x] Knowledgeable about the codebase
[ ] Sponsored by a subproject approver
[ ] With no objections from other approvers
[x] Done through PR to update the OWNERS file
[x] May either self-nominate, be nominated by an approver in this subproject, or be nominated by a robot
**Checklist**
=> Add johngmyers to reviewers

docs/tutorials/aws.md
Update the IAM policy example to include `route53:ListTagsForResource` permissions.
This is required for `--aws-zone-tags`.
**Checklist**
=> Update aws IAM policy example

docs/annotations/annotations.md, mkdocs.yml
Adds reference documentation for annotations.
**Checklist**
=> Document annotations

README.md, docs/scripts/docs.go
fix img dir
Fixes #ISSUE
**Checklist**
=> fix img dir

Makefile, cloudbuild.yaml
Attempts to fix the staging image build. (Can't test to make sure.)
Fixes #3898 
**Checklist**
=> Fixes to staging image build

controller/controller.go, endpoint/domain_filter.go, plan/plan.go, plan/plan_test.go, provider/cloudflare/cloudflare_test.go
This is a minor refactor to remove an unnecessary interface.
**Checklist**
=> Remove DomainFilterInterface

registry/txt.go
Minor refactor to use the common type declaration.
**Checklist**
=> Use common EndpointKey type

kustomize/kustomization.yaml
Updates the kustomization to the latest version.
=> update kustomization.yaml with v0.13.6

OWNERS
Add @johngmyers as an approver
Requirements:
[x] Reviewer of the codebase for at least 3 months
[x] Primary reviewer for at least 10 substantial PRs to the codebase
#3285, #3174, #3201, #3104, #3589,
#3590, #3297, #2553 #3295, #3263, 
#3738, #3451, #3745, #3695, #3690,
#3724
[x] Reviewed or merged at least 30 PRs to the codebase
#3285, #3174, #2157, #3261, #3201,
#3297, #2461, #3546, #3589, #3588,
#3590, #3607, #3600, #3603, #3590,
#3295, #3263, #3222, #2054, #2553, 
#3104, #3263, #3640, #3660, #3652,
#3674, #3635, #3648, #3729, #3738,
#3736, #3451,  #3745, #3690, #3724,
#3711, #3758, #3702, #3726, #3863,
#3835
[ ] Nominated by a subproject owner
[ ] With no objections from other subproject owners
[x] Done through PR to update the top-level OWNERS file
**Checklist**
=> Add johngmyers as approver

OWNERS
Moves @seanmalloy to emeritus_approvers. Recent review activity has been extremely low.
**Checklist**
=> Move seanmalloy to emeritus_approvers

OWNERS
Record the places where the OWNERS file should be kept in sync
**Checklist**
=> Document where OWNERS file should be synced

docs/tutorials/pihole.md
Documented Pi-hole version, since the Pi-hole REST API is much newer than the last time I updated my Pi-hole's software. This will hopefully save frustration for other folks
**Checklist**
=> Clarified documentation for Pi-hole DNS provider

pkg/apis/externaldns/types.go
Add missing ")".
Supersede #3473
**Checklist**
=> fix: parentheses typo on cli help

README.md
As STACKIT we would like to appear in the readme for webhooks.
**Checklist**
=> add stackit webhook to readme

kustomize/kustomization.yaml
Bumps to the latest release `v0.14.0`.
/cc @mloiseleur
=> bump kustomize version to v0.14.0

docs/tutorials/ultradns.md
Description
Corrected various ultraDNS related links in https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/ultradns.md
Fixes: #3523 
Fixes #ISSUE
**Checklist**
=> updated various broken link in ultradns tutorial

README.md
As GleSYS we would like to appear in the readme for webhooks.
Fixes #ISSUE
**Checklist**
=> Add GleSYS to the readme for webhooks

docs/tutorials/aws.md
Correct typo from 'Kuberntes' to 'Kubernetes'.
**Checklist**
=> Correct typo from 'Kuberntes' to 'Kubernetes'

provider/azure/config.go
Chore: fix code comment
**Checklist**
=> chore: fix code comment

charts/external-dns/CHANGELOG.md, charts/external-dns/Chart.yaml, charts/external-dns/templates/clusterrole.yaml
fixing rbac issues with gateway routes
Fixes #ISSUE
https://github.com/kubernetes-sigs/external-dns/issues/3845
**Checklist**
=> add RBAC fix to namespaces - get, watch, list to each gateway-*route

docs/tutorials/gke.md
There is a minor spelling issue in the GKE tutorial that also breaks the link to a Markdown headline. This PR fixes it.
**Checklist**
- [n/a] Unit tests updated
=> Fix "workload identity" spelling

provider/coredns/coredns_test.go
=> Change coredns testing to fix failing tests

.github/ISSUE_TEMPLATE/-support-request.md
- Update the GitHub issue template (support request) to target the right slack URL.
Fixes #ISSUE
**Checklist**
=> chore: update the slack channel URL into the github support template

provider/azure/azure.go, provider/azure/azure_private_dns.go
Implementation of softerror on the azure provider to avoid restarting when the azure api is throttling
Fixes #ISSUE #4198 4198
**Checklist**
=> add soft error

README.md
add gcore external dns provider.
=> Add Gcore provider on readme

README.md
I've added the link to my blog post to `README.md`.
=> docs: 📝 add Azure DNS w/workload identity blog post to readme

docs/tutorials/azure.md
=> doc: explain how to use Azure internal load balancer

docs/annotations/annotations.md, source/ambassador_host.go, source/ambassador_host_test.go
This change adds support for provider-specific annotations for the ambassador source.
=> feat(ambassador): add support for provider specific annotations

kustomize/kustomization.yaml
For release https://github.com/kubernetes-sigs/external-dns/releases/tag/v0.14.1
**Checklist**
=> kustomize-v0.14.1

README.md
This list will grow. 
We should make it more readable.
=> chore: alphabetical order on providers

source/service_test.go
Fix ci test, currently failing on all PRs.
**Checklist**
=> chore(ci): fix failing test

.github/workflows/lint.yaml, .golangci.yml, Makefile
chore(ci): update golangci-lint to v1.57.2
Fixes #ISSUE
**Checklist**
=> chore(ci): update golangci-lint to v1.57.2

docs/tutorials/azure.md
Changed placement of annotation to match schema of service api.
Fixes [#4409](https://github.com/kubernetes-sigs/external-dns/issues/4409)
**Checklist**
=> docs: annotation placement for azuredns tutorial

README.md
I created a webhook provider for Anexia CloudDNS.
Fixes #ISSUE
**Checklist**
=> docs: add reference to anexia webhook provider

kustomize/kustomization.yaml
This PR updates the kustomize version tag to v0.14.2
Fixes #ISSUE
**Checklist**
=> Update kustomize version for v0.14.2

README.md
Add New webhook provider for Unifi to readme
**Checklist**
=> add unifi webhook to readme

docs/overrides/partials/copyright.html, mkdocs.yml
**What type of PR is this?**
/kind documentation
**What this PR does / why we need it**:
Adds correct trademark disclaimer, as part of our ongoing effort to https://github.com/cncf/techdocs/issues/198
**Which issue(s) this PR fixes**:
Fixes #4203 
**Checklist**
=> 🌱 docs(footer): Add trademark disclaimer

README.md, docs/faq.md
PR #4365 changed the anchor in the readme, this change fixes a few outdated links
Fixed links
Fixes #4661
**Checklist**
=> docs: fix broken link

kustomize/kustomization.yaml
This PR bumps kustomize to v0.15.0
=> bump kustomize version to v0.15.0

README.md
Added link to webhook provider for Efficient IP Provider.
Fixes #ISSUE
**Checklist**
=> docs: add reference to Efficient IP webhook provider

README.md
Added link to webhook provider for Netic's TidyDNS.
**Checklist**
=> docs: add reference to Netic's TidyDNS webhook provider

README.md
This PR will add a reference in the docs to the Vultr webhook provider.
**Checklist**
=> add Vultr webhook provider reference

README.md
Add New webhook provider for huaweicloud to readme
**Checklist**
=> add huaweicloud webhook to readme

README.md
=> add mikrotik provider reference

plan/plan.go
Log when dropping create items due to no match for owner id.
Fixes #4814
**Checklist**
=> feat: log when endpoint ignored due to ownerid not match

provider/cloudflare/cloudflare.go
=> fix: change function name to properly reflect crud

README.md
Add link to abion external-dns webhook
Fixes #ISSUE
**Checklist**
=> add abion webhook to readme

kustomize/kustomization.yaml
This PR bumps the kustomize image to v0.15.1
Fixes #ISSUE
**Checklist**
=> kustomize-v0.15.1

README.md
Add a webhook for proxying DNS record updates to the Dreamhost HTTP API per these instructions:
https://help.dreamhost.com/hc/en-us/articles/217555707-DNS-API-commands
**Checklist**
=> feat: add dreamhost webook provider to readme

docs/tutorials/aws.md
Change confusing term from "Principal" to "Principle".
This PR updates the documentation by fixing a typo.
- No-ref
**Checklist**
=> docs: fix typo on aws tutorial

charts/external-dns/CHANGELOG.md, charts/external-dns/Chart.yaml, charts/external-dns/README.md
This PR releases a new Helm chart to release changes made in ti following PRs.
- #5066
- #5067
- #5046
Fixes #ISSUE
**Checklist**
=> chore(release): publish chart v1.15.2

Makefile
No issue, added `helper` support to makefile. 
if we run `make help`
output (not strictly required)
**Checklist**
=> chore(makefile): add helper and document targets

docs/proposal/design-template.md
No issue, added statuses to proposal. Please suggest where we should have less or more, or what is missing
**Checklist**
=> docs(proposal): update template with statuses

docs/proposal/001-leader-election.md, docs/proposal/design-template.md
Fixes [#ISSUE](https://github.com/kubernetes-sigs/external-dns/pull/5079#discussion_r1962364116)
**Checklist**
=> docs(proposal): standartise date format

README.md
For those who are using k8s + openwrt at home. I just released this small project to help in the ecosystem integration.
I want to document it.
**Checklist**
=> docs: openwrt webhook

OWNERS
Update OWNERs with config file for GitHub
**Checklist**
=> chore: update OWNERS with required config file

main.go
Forgot to pass this flag on main
=> fix(source): pass GatewayName to config

Makefile, charts/external-dns/CHANGELOG.md, charts/external-dns/README.md, charts/external-dns/README.md.gotmpl, charts/external-dns/templates/NOTES.txt, charts/external-dns/templates/_helpers.tpl, charts/external-dns/tests/json-schema_test.yaml, charts/external-dns/tests/notes-deprecation_test.yaml, charts/external-dns/values.schema.json, charts/external-dns/values.yaml
Fixes #5213
Fixes #5205
Resolves https://github.com/kubernetes-sigs/external-dns/pull/5207#issuecomment-2754624644
**Checklist**
=> fix(helm): added missing schema values

.github/workflows/lint.yaml, scripts/install-tools.sh
This update linter to latest version + the related GH action accordingly to [v8](https://github.com/golangci/golangci-lint-action/releases/tag/v8.0.0)
**Checklist**
=> chore(deps): update linter to v2.1.x

source/pod.go, source/pod_test.go
Code coverage increase for source/pod
now
with fix
**Checklist**
=> test(source/pod): improve code coverage

endpoint/endpoint_test.go
Fixes #5150.
This PR improves the test coverage for ``endpoint.go`` file from 76.23% to 95.9%.
**Checklist**
=> test(endpoint): improve coverage from 76% to 95.9%

.github/workflows/lint.yaml
Fixes None
Added pre-coomit github action 
Our pre-commit config is here https://github.com/kubernetes-sigs/external-dns/blob/master/.pre-commit-config.yaml
extra automated check
**Checklist**
=> chore(code): add pre-commit github action

internal/testutils/endpoint_test.go
Ref #5150 
This PR improves test coverage for testutils/endpoint.go file from 27.3% to 96%. 
**Checklist**
=> test(testutils/endpoint): improved test coverage for testutils/endpoint

docs/advanced/fqdn-templating.md, source/contour_httpproxy.go, source/fqdn/fqdn.go, source/fqdn/fqdn_test.go, source/gateway.go, source/ingress.go, source/istio_gateway.go, source/istio_virtualservice.go, source/node.go, source/openshift_route.go, source/service.go, source/source.go
No issue
- added more functions
- moved ExecTemplate to fqdn and added code coverage for that function
- added tests highlighting use cases
Related prs
- https://github.com/kubernetes-sigs/external-dns/pull/3949
- https://github.com/kubernetes-sigs/external-dns/pull/5354
**Checklist**
=> feat(fqdn): improve ExecTemplate and add more functions

charts/external-dns/tests/deployment-flags_test.yaml, docs/tutorials/aws-sd.md, docs/tutorials/aws.md
- update AWS permissions example
- execute linter on aws
- execute pre-commit-hook for aws docs
**Checklist**
=> chore(docs): update aws role requirements with conditions

.golangci.yml, endpoint/endpoint_test.go
=> chore(codebase): add cyclop max

CONTRIBUTING.md
It explains to users how to test a PR. 
**Checklist**
=> docs(contributing): detail how to test a PR

provider/gandi/gandi_test.go
Ref:- #5150 
This PR improves test coverage of provider/gandi to 100%
=> test(provider/gandi): bumped to 100% coverage

provider/civo/civo_test.go
Ref #5150 
This PR aims to improve the test coverage to ``90.4 %``
=> test(provider/civo): improved test coverage

README.md
=> docs: add deSEC webhook

README.md
docs update: add alibaba cloud provider reference
**Checklist**
=> docs: add alibaba cloud provider reference

source/crd.go, source/crd_test.go
Relates https://github.com/kubernetes-sigs/external-dns/issues/5243
To address some related CRD issues, worth first to improve coverage and fix deprecations
- fix deprecations
- increase test coverage
deprecation
coverage
before
with change
=> chore(source/crd): improve test coverage, fix deprecations

source/pod.go, source/pod_test.go
Reduce cyclomatic complexity (30) of `podSource.Endpoints()` in `source/pod.go` .
https://github.com/kubernetes-sigs/external-dns/issues/5419
=> chore(code-quality): reduce cyclomatic complexity of podSource.Endpoints()

.github/workflows/release-chart.yaml, charts/external-dns/Chart.yaml
This PR fixes the chart release process as there was a typo in a script.
Closes #5398
=> fix(chart): release chart process

charts/external-dns/CHANGELOG.md
Add a missing changelog record in the chart for #5493
=> feat(chart): add missing changelog for #5493

docs/tutorials/security-context.md, mkdocs.yml
[](https://github.com/kubernetes-sigs/external-dns/pull/5559/files#r2163321571)
- fix docs
=> chore(docs): fix documentation references

plan/plan.go
refactor: use slices.Contains instead of handrolled for loop
=> refactor: use slices.Contains instead of handrolled for loop

plan/plan_test.go
Just added a test to validate cases with asterisks
Resolves #5635
=> chore(plan): added tests for cases with asterisks

docs/contributing/dev-guide.md
Fixing some errors in the developer guide documentation.
Familiarize myself with the contributing process for this repo.
=> fix(docs): Fixing some errors in the dev-guide example.

provider/aws/aws.go
Reduce nesting to simplify decision flow
https://github.com/kubernetes-sigs/external-dns/pull/5685#discussion_r2231805567
=> chore(provider/aws): reduce if-nesting for dryRun condition

source/store.go, source/store_test.go, source/types/types.go
slicing PR https://github.com/kubernetes-sigs/external-dns/pull/5659
ref https://github.com/kubernetes-sigs/external-dns/pull/5659#discussion_r2239283072
The new folder is created, mainly to prevent circular dependencies issues
=> chore(source): use types instead of strings

provider/cloudflare/cloudflare.go, provider/cloudflare/cloudflare_test.go
Migrate the cloudflare provider `CreateDNSRecord()` func to the new lib.
See #5540.
=> chore(cloudflare): migrate CreateDNSRecord() to new lib

provider/coredns/coredns.go
=> fix(coredns): debug message on labels update

docs/tutorials/rfc2136.md
Fix RBAC in rfc2136 tutorial.
Fixes https://github.com/kubernetes-sigs/external-dns/issues/5825
- [] Yes, I updated end user documentation accordingly
=> doc(tutorials/rfc2136): fix RBAC

internal/gen/docs/metrics/main.go
~~Remove hard coded metrics in `metrics.md` generator.~~
Deduplicate metrics in `metrics.md` generator. 
fix #5834
=> fix(gen/metrics): deduplicate generated in metrics.md
