kubernetes-sigs/external-dns

docs/initial-design.md

*** DO NOT MERGE *** 
This is to start design documentation. The following contains the basic outline of what external-dns is and some goals/design decisions we should consider

initial-design file

---

docs/legacy/kops-dns-controller.md

Kops includes a dns-controller, and this document describes the existing
annotations and their behaviour.  This document is intended to allow us
to see the use-cases identified by kops dns-controller, to ensure the
same annotations can be recognized (perhaps with a `--compatibilty`
flag), and to ensure that we have comparable functionality.

Document existing kops dns-controller annotations

---

Makefile

follow-up of https://github.com/kubernetes-incubator/external-dns/pull/38

run tests for all but vendored packages

---

docs/project-structure.md
main.go
pkg/apis/externaldns/types.go
pkg/apis/externaldns/validation/validation.go
pkg/apis/externaldns/validation/validation_test.go

Types that we want to work using apimachinery typically go into
pkg/apis/X, and the validation goes into pkg/apis/X/validation.  We then
add versions into e.g. pkg/apis/X/v1alpha1, but this feels premature at
the moment.
Changing this later is annoyingly difficult, especially in terms of
validation and dependencies.
We will want the apimachinery, so that we can configure from a
configuration file that is versioned.  Hopefully dns-controller won't
end up so complicated that we will require it, but I think there is also
value in following the "standard" patterns for controllers that are
emerging from e.g. ingress.
For a fairly simple example of an API, please consult
https://github.com/kubernetes/kubernetes/tree/master/pkg/apis/certificates

Move config to apimachinery

---

source/service_test.go

follow-up of https://github.com/kubernetes-incubator/external-dns/pull/39

consistently use CoreV1() instead of Core()

---

dnsprovider/google.go

With this you can pass multiple records to the Google DNS provider, which reduces the number of API requests for `ApplyChanges` to max three.

allow google provider to send requests in batches

---

main.go
pkg/apis/externaldns/types.go
source/ingress.go
source/ingress_test.go
source/service.go
source/service_test.go

This allows passing a namespace to limit the resources that are found by the sources. I'm currently wring a simple integration test and want to create a service in a "testing" namespace also validate that this service gets its dns entries created. I don't care about other services in the cluster.

allow passing a namespace that limits found resources

---

main.go
pkg/apis/externaldns/types.go

`--once` terminates the program after first sync.
@ideahitme I'm currently writing a simple integration test where I need this functionality. However, the busy loop at the end of the program still seems odd to me.

add once flag to exit loop after first sync

---

dnsprovider/google.go

Improves the Google DNS provider:
* support pagination
* apply as a single batch request
* share more common code
My messy integration tests (https://github.com/linki/external-dns/blob/google-batch/dnsprovider/google_test.go) didn't change and happily pass with these changes as well.

refactor Google DNSProvider to cleaner

---

Dockerfile
Makefile
cloudbuild.yaml

Builds a docker image for `external-dns` using Google's Container Builder.
You can build your own by enabling the Container Builder API in your project and run:
```
gcloud --project your-project container builds submit --config=cloudbuild.yaml .
```
or find the latest commit at: `gcr.io/zalando-docker/external-dns`
---
I would like to setup triggers so it gets built automatically. Unfortunately, that requires an owner to allow to read `kubernetes-incubator` projects from Google via my Github account.
@justinsb That seems a little odd. Do you have better ideas?

build docker image with google container builder

---

Dockerfile

We need those certs to connect to the Google API.

add missing certificates to container image

---

Makefile
cloudbuild.yaml
main.go
pkg/apis/externaldns/types.go
pkg/apis/externaldns/types_test.go

adds a version flag and also updates the build accordingly. /cc @ideahitme 
fixes https://github.com/kubernetes-incubator/external-dns/issues/70

add --version flag

---

dnsprovider/google.go
dnsprovider/google_test.go
main.go

This adds tests for the google dns provider by defining interfaces which are implemented by the google dns API and mocking the google dns API calls in the tests.
For this to work I moved the initialization of the `GoogleProvider` into `NewGoogleProvider()` rather than initializing it directly in `main.go`. This also allowed making the struct fields of `googleProvider` private.
/cc @linki

Add tests for Google DNS provider

---

source/ingress_test.go
source/service_test.go

Ensures that these sources implement `Source`.

validate that current sources adhere to the Source interface

---

source/ingress.go
source/ingress_test.go

This makes Ingress work with the Google provider. We should standardize either way. For now, I chose to add the dot before passing it onwards.

Ingress: appends trailing dot to hostnames

---

main.go
pkg/apis/externaldns/types.go
source/store.go
source/store_test.go

This also allows specifying the sources on the command line, aka Ingress support.

allow to register and lookup sources by name

---

cloudbuild.yaml

Google's Container Builder doesn't work so well for us at the moment:
* difficult to support github tags as  docker tags
* difficult to support abbrev revisions as tags
* I can't setup triggers b/c I'm no org owner
I've setup a job on our internal Jenkins to do it for now and push the image to our opensource registry, i.e. `docker pull registry.opensource.zalan.do/teapot/external-dns`
I'm leaving the simplest version of cloudbuild here for reference. You can use it to push an image to your Google project's registry without having docker installed.

simplify cloudbuild

---

README.md
docs/tutorials/gke.md

remove tutorial from the readme and link to the tutorials section.

move example from README to tutorials

---

source/ingress.go
source/ingress_test.go
source/service.go
source/source.go

It must be able to opt-out of being controlled by this controller. `IngressSource` was missing that.

ingress: should be ignored if other controller is annotated

---

provider/aws.go
provider/aws_test.go

Sending a change without changes to AWS returns an error. This just returns early if the list of changes is empty.

route53: do not submit request when changes is empty

---

docs/tutorials/nginx-ingress.md

Adds a detailed description how to run nginx ingress controller with ExternalDNS. Includes setup of ExternalDNS as well as the ingress controller on GKE.

document how to use ExternalDNS with nginx ingress controller

---

.travis.yml

/cc @linki seems like a lot of builds are timing out 
https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

increase the timeout to 20minutes for goveralls

---

plan/plan.go
plan/plan_test.go
provider/aws.go
provider/aws_test.go

when detecting the type from the hostname, we have to take the `recordType` into account if it's set. ~~This allows to pres switch between CNAME and ALIAS and allows ExternalDNS to work correctly when removing one for the other.~~ It preserves the type which is required for deleting and updating records.

take record type into account when determining ELBs

---

provider/google.go

When we decided to sanitize by removing a trailing dot we broke the Google provider.

Google: ensure DNS records have trailing dot before sending

---

main.go

To make it easier to detect config errors (like non-empty "domain")

log config on startup

---

docs/tutorials/gke.md

Bug in question: https://github.com/kubernetes-incubator/external-dns/issues/154
This is fixed in 0.2.1

Tutorial uses buggy version for GKE example

---

main.go
source/dedup_source.go
source/dedup_source_test.go

This provides an alternative solution to https://github.com/kubernetes-incubator/external-dns/issues/182 by using a deduplicating source on the outer edge of the sources chain.
Let me know what you think about this and which approach you prefer compared to https://github.com/kubernetes-incubator/external-dns/pull/183.
However, as Sources were intended to be extensible a `DedupSource` doesn't harm and might come in handy in any case.
/cc @jrnt30 @ideahitme

add and use a deduplicating source

---

provider/inmemory.go
provider/inmemory_test.go
registry/noop_test.go
registry/txt_test.go

Refactor InMemoryProvider to simulate current behaviour of other providers 
This PR is required to refactor interfaces and remove mentioning of zones from the codebase 
@linki

refactor inmemory provider

---

controller/controller.go
controller/controller_test.go
provider/aws.go
provider/aws_test.go
provider/google.go
provider/google_test.go
provider/inmemory.go
provider/inmemory_test.go
provider/provider.go
registry/noop.go
registry/noop_test.go
registry/registry.go
registry/txt.go
registry/txt_test.go

We removed the need for the `zone` parameter a while ago. Now purge it from the Interface as well.
/cc @ideahitme

remove superflous zone parameter

---

controller/controller.go
plan/plan.go
plan/plan_test.go

This allows plan to iterate over multiple policies.
This is a precondition to what we intend to do in https://github.com/kubernetes-incubator/external-dns/pull/189.

allow plan to have multiple policies

---

provider/aws.go
provider/azure.go
provider/google.go
provider/google_test.go

This PR unifies implementation details of providers (previously only google implementation is made private) and in the view of that it makes sense to not hide the implementation details of each provider, therefore return actual struct. 
/cc @linki

make all provider implementation public, return struct instead of interface

---

README.md

We've been running external-dns in compatibility mode with route53-kubernetes for a few weeks with no issues. I think it's safe to say that we've met this requirement for 1.0.
Awesome job everyone!
Also, I've officially deprecated route53-kubernetes and will be directing new users to this repo in the future.
lmk if there are any other docs I should update.

Mark compatibility with route53-kubernetes

---

docs/tutorials/nginx-ingress.md

Originally had `dry-run=true` as the dry run flag but that doesn't work and makes external-dns fail to start. Changed to `--dry-run`.

Fix incorrect flag in nginx-ingress.md

---

source/service_test.go

Tests that individual annotations overwrite a globally defined fqdn template. Came out of a misread in an issue. But useful I thought.

add test for annotation taking precendence over template

---

docs/faq.md

How about anyone can add a question to the FAQ section via a PR so that we can go through and answer them from time to time. It's also possible to answer the question directly in the PR.
Background: we have several issues with questions that were answered but it's difficult to find them later. Instead people could add a stub question to the FAQ so we have a single place to look them up.
I don't know if anyone else does it this way. Feedback welcome @ideahitme @Raffo @hjacobs

add some stub questions to the FAQ

---

CHANGELOG.md
docs/tutorials/cloudflare.md
docs/tutorials/digitalocean.md

adds a quick tutorial for digital ocean. https://github.com/kubernetes-incubator/external-dns/issues/170

tutorials: add tutorial for digital ocean

---

docs/faq.md

Just a quick win to document service account setup.
As a result of https://github.com/kubernetes-incubator/external-dns/issues/283#issuecomment-318320780

faq: add answer for how to run ExternalDNS under service account

---

source/store.go

We messed up the parameters order when invoking the `NewSourceSource` and `NewIngressSource` functions. This led to the wrong namespace being tracked (the value of the fqdn template) and therefore didn't find any services nor ingresses.
Fixes https://github.com/kubernetes-incubator/external-dns/issues/295

source: use correct order of parameters

---

README.md
docs/faq.md

I updated the `README.md` to include links to the various tutorials that are provided. Hopefully, this will help new users more easily find the instructions on how to deploy ExternalDNS on the various platforms.
I updated `docs/faq.md` to include details about how to setup `nginx-ingress-controller` on AWS and get ExternalDNS to utilize the ELB's FQDN in the Route 53 entries.

Update README.md and docs/faq.md

---

source/compatibility.go
source/service_test.go

Molecule supports multiple hostnames split by `,` but it wasn't supported until now.
See:
* https://github.com/kubernetes-incubator/external-dns/pull/256#issuecomment-319504658
* https://github.com/wearemolecule/route53-kubernetes/blob/master/service_listener.go#L160

Support multiple hostnames for molecule compatibility

---

docs/faq.md
source/ingress.go
source/ingress_test.go
source/source.go

Support `external-dns.alpha.kubernetes.io/target` annotation on Ingress.
> This allows users to specify a new annotation at Ingress resources for creation of endpoints. This is specifically useful when using Ingress Controllers that do not populate the status.LoadBalancer field of Ingress.
Same contents as #285, but makes it slightly more DRY.

Support for annotation based targets for Ingress

---

CHANGELOG.md
docs/faq.md
source/ingress.go
source/ingress_test.go

If the user has specified a target for the ingress, treat that as
overriding any endpoints already set on the ingress, even if that list
is not empty.  This allows overriding the IP address or hostname set
when using a service like kube-keepalived-vip.
This is related to #312

Ingress target annotation should set, not append

---

endpoint/endpoint.go
internal/testutils/endpoint_test.go
plan/plan_test.go
provider/aws.go
provider/aws_test.go
provider/azure.go
provider/azure_test.go
provider/cloudflare.go
provider/cloudflare_test.go
provider/digital_ocean.go
provider/digital_ocean_test.go
provider/google.go
provider/google_test.go
provider/inmemory.go
provider/inmemory_test.go
provider/provider.go
provider/provider_test.go
registry/noop_test.go
registry/txt.go
registry/txt_test.go
source/compatibility.go
source/fake.go
source/ingress.go
source/service.go

- Use constants for RecordType's
- Set RecordType in the sources
- Remove ALIAS type (This is only used to determine if we should create an AliasTarget for the AWS provider and should be internal to the AWS provider. Also when we add multiple-target support we will group records by DNSName/RecordType, so we need to convert the RecordType back to a CNAME in order to properly compare current vs desired. Additionally AliasTarget only supports single targets, so when we switch to multiple-targets we will need to determine based on the target count as well.)

Kops Compatibility #1: Set RecordType at source

---

main.go
pkg/apis/externaldns/types.go
pkg/apis/externaldns/types_test.go

Adds a new `--log-level` flag which sets the appropriate logrus log-level. Valid values are `debug`, `info`, `warn`, `error`, and `fatal`.
Removed the `--debug` flag in favor of the new, more flexible, `--log-level` flag.

add flag to override log-level

---

provider/inmemory.go
provider/inmemory_test.go

if zoneid does not match, we get empty string from im.filter.EndpointZoneID(ep, zones)

fix nil ptr dereference in inmemroy provider

---

.travis.yml
CHANGELOG.md
provider/aws.go
provider/aws_test.go

All relevent changes are in aws.go

Fix for #368

---

docs/tutorials/infoblox.md
pkg/apis/externaldns/types.go

Trim variable names so commands fit in viewable range, switch from environment variables to command line arguments, and explicitly mention that `--no-infoblox-ssl-verify` disables server certificate verification.
https://github.com/kubernetes-incubator/external-dns/issues/378

address #378 (disable infoblox-ssl-verify)

---

docs/tutorials/azure.md

If the cluster is not Azure Container Service (or acs-engine) the configuration file/secret for Azure DNS provider needs to be created manually. Included a short tutorial on how to use Azure CLI to extract the necessary information for the configuration file. (Verified working from GKE)

Doc: how to use Azure DNS from non-Azure cluster

---

CHANGELOG.md
docs/ttl.md
provider/google.go
provider/google_test.go

Use `int64(ep.RecordTTL)` in `newRecord()`
Fallback to hardcoded 300s for backwards-compat
Add `TestNewRecords()`
Add notes in *ttl.md*

Google Provider Add Ttl from annotations

---

source/service.go
source/service_test.go
source/source.go

A simple implementation for #315 and based on #278.
The idea is, to assign a DNS address for every Pod running under a Headless service. This is a fairly important usecase in my mind, for exposing Stateful services, which have some kind of inbuilt discovery mechanism, like Apache Kafka. As these services can only really properly work with a HostPort(I did not find any other way), it makes sense to export their HostIP as a stable DNS record.
I thought about a number of approaches to parametrize this, but the simple approach was to add a subdomain annotation. Conceptually we would want  for each Pod appear with the hostname assigned to it by the StatefulSet, so we only  need to concerned with the subdomain where the Pods are registered.
So I added a new annotation …

Add support for Headless hostPort services

---

provider/aws.go
provider/google.go

This prints the dns zones the provider considers for placing dns records. It hopefully helps us to quickly figure out why ExternalDNS refuses to place records, e.g. due to wrong IAM configuration, wrong domain filter or bugs in the zone detection.
```console
time="2017-11-28T11:27:24+01:00" level=debug msg="Considering zone: /hostedzone/Z3...P7 (domain: zone-1.teapot.zalan.do.)"
time="2017-11-28T11:27:24+01:00" level=debug msg="Considering zone: /hostedzone/ZH...5OE (domain: zone-4.teapot.zalan.do.)"
```
/cc @ideahitme

Print matched dns zones (only gcp, aws)

---

.travis.yml
Dockerfile

Removes 1.8 from travis and builds the image using 1.9

Switch to go v1.9

---

docs/tutorials/aws.md

Added a name value to make Kubernetes 1.8.5 work.
Had this error before:
```
The Service "nginx" is invalid:
* spec.ports[0].name: Required value
```

Adding required `name` values

---

main.go

Fix for https://github.com/kubernetes-incubator/external-dns/issues/428.
On `SIGTERM` `Controller` already finishes a current sync cycle and then returns which causes the entire program to terminate gracefully.
/cc @ideahitme @mikkeloscar

Remove stale wait time on shutdown

---

provider/aws.go
provider/aws_test.go

Addresses #447 by adding the new AWS Paris region to the list of `canonicalHostedZones`.

add paris region

---

source/service.go
source/service_test.go

Avoid missing pod hostname for headless service

---

CHANGELOG.md
main.go
pkg/apis/externaldns/types.go

The two passwords configurable as flags (for infoblox and dyn) are
masked now and not logged.

Don't log passwords on start

---

CHANGELOG.md
main.go
pkg/apis/externaldns/types.go
pkg/apis/externaldns/types_test.go
pkg/apis/externaldns/validation/validation.go
pkg/apis/externaldns/validation/validation_test.go
provider/dyn.go
provider/dyn_test.go

If a bad password is given for provider "dyn" then the next
login attempt is at least 30minutes apart. This prevents an
account from being suspended.
Add validation of flags for dyn provider.
Also add --dyn-min-ttl option which sets the lower limit
of a record's TTL. Ignored if 0 (the default).
Removed a stale fmt.Println() statement.

Graceful handling of misconfigure password for dyn

---

CHANGELOG.md
provider/dnsimple.go
provider/dnsimple_test.go

The DNSimple API is paginated. Retrive all pages when requesting zones
and records, so that none are skipped.
When querying for a single record, ask for it by name. That way, there
will be fewer pages to iterate through.

Retrive all DNSimple response pages

---

CHANGELOG.md
provider/digital_ocean.go
provider/digital_ocean_test.go

DigitalOcean creates entries with host in them twice

---

docs/tutorials/public-private-route53.md

This PR adds a tutorial how to setup ExternalDNS for the same domain used in public/private Route53 zone. Additionally, it shows how to leverage cert-manager to issue SSL certificates from Let's Encrypt for both public and private records.

Setting up ExternalDNS using same domain for public/private Route53 zones

---

docs/tutorials/public-private-route53.md

there was a small typo in the yaml definition of the external-dns deployments.

fixing image tag typo in public-private-route53.md tutorial

---

docs/tutorials/aws.md
docs/tutorials/azure.md
docs/tutorials/cloudflare.md
docs/tutorials/digitalocean.md
docs/tutorials/gke.md
docs/tutorials/hostport.md
docs/tutorials/infoblox.md
docs/tutorials/nginx-ingress.md

This PR addresses #233. I have updated the example YAML's to have the appropriate RBAC permissions for K8s clusters running with RBAC (now enabled by default on new clusters.)

update RBAC rules in docs

---

provider/zonefinder.go
provider/zonefinder_test.go

Fix for https://github.com/kubernetes-incubator/external-dns/issues/446
As suggested by @dhawal55 including a preceding dot in the zone suffix match avoids a wrongly detected zone.
The suffix match used to be true when the strings where exact matches as well which the Azure provider depends on, hence the additional check in the if statement. Added some tests with comments as well.
/cc @dhawal55 @gustav-b @ideahitme

Correctly detect zones if names overlap with subdomain

---

docs/tutorials/gke.md

serviceAccountName was transposed onto the non-RBAC example

Fix typo for serviceAccountName in RBAC example

---

.travis.yml
Dockerfile

I believe we should always build against the latest stable version of golang instead of lacking behind when we forget to update the version.

Always build against latest stable version of golang

---

docs/tutorials/nginx-ingress.md

The nginx-ingress guide lists RBAC roles & bindings, but doesn't tie the Deployment to the specific ServiceAccount.
Links the Deployment to the ServiceAccount.

Adds `serviceAccountName` field to pod spec

---

provider/digital_ocean.go
provider/digital_ocean_test.go

The DomainRecord response from the Digital Ocean API does not contain
the zone as part of the name and thus we must append the zone name when
converting it to an endpoint for the plan calculation.
Furthermore the root domain is identified by `@` and must be converted
to the zone name for the endpoint, and converted back to `@` when the
record is submitted to the DO API.
https://developers.digitalocean.com/documentation/v2/#retrieve-an-existing-domain-record
Fix #487
Fix #503

digitalocean: Fix handling of domain record names

---

CHANGELOG.md
main.go
pkg/apis/externaldns/types.go
source/ingress.go
source/ingress_test.go
source/service.go
source/service_test.go
source/store.go

The old behaviour is kept by default, a new flag is introduced to combine instead of overwriting
Fixes #218
Depends on #512

Add a flag that allows FQDN and Annotations to combine

---

endpoint/endpoint.go
endpoint/endpoint_test.go
provider/aws.go
provider/aws_test.go
provider/azure.go
provider/azure_test.go
provider/cloudflare.go
provider/digital_ocean.go
provider/dnsimple.go
provider/dyn_test.go
provider/google_test.go
provider/infoblox.go
provider/infoblox_test.go
provider/inmemory.go
registry/txt.go
registry/txt_test.go
source/compatibility.go
source/fake.go
source/service.go

This PR is to add support for multiple targets per #239 .  I changed the signature of `endpoint.NewEndpoint` and `endpoint.NewEndpointWithTTL` moving `target` to the end of as a variadic parameter.  This caused the size of the PR to balloon, but I figured making is variadic was better than littering the code with `[]string{"1.2.3.4"}` everywhere by changing the `target` parameter to a string slice.
I only added tests for AWS right now, but it should be relatively straight forward to add the tests to other providers.

Inititial support for multiple targets per record

---

provider/pdns.go
provider/pdns_test.go

* Fixed PowerDNS provider bug affecting endpoint conversion to
zone in a particular case
* Added a regressive test case, covered an additional case
PowerDNS provider bug: In the function `ConvertEndpointsToZones`, the endpoints are sorted lexicographically increasing (and by record type in case of match). The zones are sorted by decreasing order of length. There's a loop through of zones under which the code loops through endpoints. In the case the first endpoint does not match with the first zone, the complete zone won't get populated with any endpoints. This small change fixes that.

Fixed Bug in PowerDNS provider and added testcases

---

CHANGELOG.md
provider/google.go
provider/google_test.go

Fixes https://github.com/kubernetes-incubator/external-dns/issues/530

Correctly filter records that don't match all filters

---

pkg/apis/externaldns/types.go

Designate is misspelled, and deployment fails because of it.
`time="2018-05-03T07:29:04Z" level=fatal msg="flag parsing error: enum value must be one of aws,google,azure,cloudflare,digitalocean,dnsimple,infoblox,dyn,desginate,inmemory,pdns, got 'designate'"`

Designate - Fixing typo

---

source/ingress.go
source/ingress_test.go
source/service.go
source/source.go

This PR fixes #402 
We ran into similar issue where we had ingress rule hostname set to 'website.company.com' whereas the externaldns name we wanted was 'website.extdomain.company.com'
and website.company.com is a static cname to website.extdomain.company.com

add support for hostname annotation in ingress resource

---

controller/controller.go

Rather than create a new `timer.After()` instance for each loop, this uses a single ticker to accomplish the same goal.

use ticker

---

docs/tutorials/cloudflare.md
provider/cloudflare.go
provider/cloudflare_test.go

Custom record TTL annotation should be noted by Cloudflare provider 
TTL min value is 120 everything below will take the default TTL which is 1 (automatic which means 300)

[Cloudflare] Custom record TTL

---

Gopkg.lock
Gopkg.toml
README.md
docs/tutorials/aws-sd.md
endpoint/labels.go
main.go
pkg/apis/externaldns/types.go
provider/aws_sd.go
provider/aws_sd_test.go
registry/aws_sd_registry.go
registry/aws_sd_registry_test.go

Hi guys,
AWS engineer here. First of all thank you for the successful integration with Route 53 API. Good job!
I would like to propose an alternative AWS provider to current one. It uses the recently published [Amazon Auto Naming API](https://docs.aws.amazon.com/Route53/latest/APIReference/API_Operations_Amazon_Route_53_Auto_Naming.html) that is more suitable for service discovery use case. You can read more about the service discovery in the [Amazon API Reference](https://docs.aws.amazon.com/Route53/latest/APIReference/overview-service-discovery.html)
I would like to emphasize a few important features of the provider:
* It natively supports recent addition of multiple targets per endpoint - in Auto Naming API terms you can have multiple *instances* per *service*.
* It is more safe to use …

Add AWS Service Discovery provider

---

provider/dnsimple.go
provider/dnsimple_test.go

Like other providers, the DNSimple provider should ignore any records
that belong to zones outside of its control.

Make DNSimple tolerant of unknown zones

---

docs/tutorials/azure.md

'tcp' is not a supported value whereas 'TCP' is.

Update azure.md to fix protocol value

---

endpoint/endpoint.go
provider/recordfilter.go
source/service.go
source/service_test.go

Initial work towards support for NodePort services for https://github.com/kubernetes-incubator/external-dns/issues/191.
I'm a little lost on how to get some fake nodes into the testing harness so any help would be appreciated.  I also haven't been able to test this yet as my dev cluster is in bad shape at the moment.
Any input would be greatly appreciated.  I went with a poll on update due to the rest of the application not using the event stream.  This poll is done once and passed through the update process.

Add support for NodePort services

---

docs/tutorials/aws.md
docs/tutorials/azure.md
docs/tutorials/cloudflare.md
docs/tutorials/digitalocean.md
docs/tutorials/gke.md
docs/tutorials/hostport.md
docs/tutorials/infoblox.md
docs/tutorials/nginx-ingress.md
docs/tutorials/pdns.md

(#559) Introducing support for NodePort services might not work in clusters which
using RBAC
```
time="2018-06-15T14:54:06Z" level=error msg="nodes is forbidden: User \"system:serviceaccount:default:external-dns\" cannot list nodes at the cluster scope"
time="2018-06-15T14:55:04Z" level=debug msg="Using cached records."
time="2018-06-15T14:55:04Z" level=error msg="nodes is forbidden: User \"system:serviceaccount:default:external-dns\" cannot list nodes at the cluster scope"
```
* Allow external-dns to list nodes
Signed-off-by: Nick Jüttner <nick@zalando.de>

Update RBAC for external-dns to list nodes

---

provider/aws.go
provider/aws_test.go

Similar to #478 , this will correctly detect zones when names overlap with subdomains.  I added a note to #446, but let me know if i should create a separate issue. 
Note:  I am not sure why *all* matching private zones are considered suitable, but did not modify that logic.

AWS provider: Properly check suitable domains

---

provider/aws_test.go

Addressing @linki's feedback from #594 and reorder tests

Reorder provider/aws suitable-zones tests

---

docs/initial-design.md
source/ingress.go
source/ingress_test.go

Fixes #610 
Not sure about check for empty "host" value, if it's needed, just copied from rules handling.
Also updated docs, to reflect annotations support on ingress (see #545 ) and this new hostsnames from tls feature.

Read hostnames from spec.tls.hosts on Ingress object

---

provider/digital_ocean.go
provider/digital_ocean_test.go

For some reason, the DO API requires the '.' at the end of "data" in case of CNAME request
Example: {"type":"CNAME","name":"hello","data":"www.example.com."}
otherwise gives this error:
422 - Data needs to end with a dot (.)

Update DO CNAME type API request to prevent error 422

---

source/ingress.go
source/ingress_test.go

If a user mistakenly enters a empty target annotation today, it causes any new records or updates to records to stop with the following error on AWS Route53:
`time="2018-07-26T06:20:16Z" level=error msg="InvalidChangeBatch: Invalid Resource Record: FATAL problem: DomainNameEmpty (Domain name is empty) encountered with ''\n\tstatus code: 400, request id: f6a2b9a4-909b-11e8-b1ae-fbaf69c94a56"`
This ensures that an empty target annotation is treaded the same way as an unset target annotation.

Fix for empty target annotation.

---

Gopkg.lock
Gopkg.toml
source/compatibility.go
source/ingress.go
source/ingress_test.go
source/service.go
source/service_test.go

XRef: https://github.com/kubernetes-incubator/external-dns/issues/555#issuecomment-409303747
client-go version used is pretty old and is blocking adding new features to source.
/cc @linki @munnerz @mtsr

Bump k8s.io/client-go version to latest stable (v8.0.0)

---

pkg/apis/externaldns/types.go

time="2018-08-06T20:45:08Z" level=fatal msg="flag parsing error: enum value must be one of panic,fatal,error,warning,info,debug, got 'warn'"
For reference: https://github.com/sirupsen/logrus/blob/2c677e6a5e5ae8e1b967f1efcf2c3dbaaf625b2d/logrus.go#L16

log level warning option

---

README.md

**Why:**
* Cloudflare link shouldn't have the langauge and should rely on the
browser
**This change addresses the need by:**
* closes #672
Signed-off-by: Christopher Hein <me@christopherhein.com>

Fixes #672 Cloudflare Link Language Specificity

---

main.go
pkg/apis/externaldns/types.go
pkg/apis/externaldns/types_test.go
provider/google.go
provider/google_test.go
source/store.go

When running in a pod sometimes the request to get ingreses/services
stalls indefinitely. A simple pod restart fixes this. Hard to reproduce
but I got lucky and did thread dump which revealed a gorouting blocked
on call to k8s.
What's new is a `--request-timeout` flag that makes requests to k8s
bounded in time. Leaving it empty preserves the original behavior.

Configure req timeout calling k8s APIs

---

main.go
pkg/apis/externaldns/types.go
source/service.go
source/service_test.go
source/store.go

This PR adds a flag allowing users to provide a list of service types to take care about. Non-listed service types are ignored by external-dns. If no list is provided, all service types are selected.

Add filter by service type feature

---

provider/pdns.go

The Host field of the HTTP request is set incorrectly when passing
the configured server.  The underlying HTTP library experts a hostname
to be passed.  When passing it a string of the form 'http://pdns.example.com'
this gets converted into 'http:' (stripping everything from the first
slash onward).  However setting the Host field in the pdnsClientConfig
object is not needed because the underlying library will then parse the
hostname from the URL.
Fixes #661
Signed-off-by: Bartel Sielski <bartel.sielski@gmail.com>

Fix Host field in HTTP request when using pdns provider

---

CHANGELOG.md

New Release v0.5.6 https://github.com/kubernetes-incubator/external-dns/releases/tag/v0.5.6

Updating CHANGELOG.md to v0.5.6

---

provider/google.go
provider/google_test.go

Currently, the Google DNS provider ignores the TTL returned from the ListRecordSets API call. As a result, the TTL is assumed to be the default value of 300. This causes problems when a record with a custom TTL value needs to be updated because the attempt to delete the old record uses the incorrect TTL value. The Google DNS API returns a "conditionNotMet" error in this case, which effectively prevents any further modifications to the DNS record. 
Fixes #467

Fix handling of custom TTL values with Google DNS.

---

Gopkg.lock
Gopkg.toml

This replaces `glog` with `github.com/kubermatic/glog-logrus` which allows to inject a `logrus` logger instead (the default is a noop logger). Replacing glog allows us to set `readOnlyRootFilesystem: true`.
It's a step towards running external-dns with the following security context:
```yaml
securityContext:
runAsNonRoot: true
runAsUser: 65534
readOnlyRootFilesystem: true
capabilities:
drop: ["ALL"]
```
Thanks to @kdomanski for `github.com/kubermatic/glog-logrus`.

Replace glog with a noop logger

---

main.go

Partial fix for https://github.com/kubernetes-incubator/external-dns/issues/718
This avoids spreading new records with a possible wrong value for `EvaluateTargetHealth`. For already affected clusters we would need to fix https://github.com/kubernetes-incubator/external-dns/issues/720.
/cc @muaazsaleem @njuettner @peterbale

Pass all relevant CLI flags to AWS provider

---

docs/tutorials/security-context.md

Document how to run ExternalDNS with reduced privileges.
related https://github.com/kubernetes-incubator/external-dns/issues/595 https://github.com/kubernetes-incubator/external-dns/pull/684

Document how to use a different security context

---

endpoint/endpoint.go
internal/testutils/endpoint.go
internal/testutils/endpoint_test.go
provider/aws.go
provider/aws_test.go

This is a fix for https://github.com/kubernetes-incubator/external-dns/issues/720.
It uses the `ProviderSpecific` field of `Endpoint` to capture the value of `EvaluateTargetHealth` on existing ALIAS records in `provider.Records()`. It allows it to correctly delete those records in a later stage (`provider.ApplyChanges`).
For new records it uses the value of the `--aws-evaluate-target-health` flag.

Correctly populate target health check on existing records

---

registry/txt.go

We are seeing crash in latest code as below
```
panic: assignment to entry in nil map
goroutine 1 [running]:
github.com/kubernetes-incubator/external-dns/registry.(*TXTRegistry).Records(0xc0001025b0, 0xc000000300, 0xc0006ed828, 0xc0004ca8a0, 0xc0004ca8a0, 0xc0006ed828)
/go/src/github.com/kubernetes-incubator/external-dns/registry/txt.go:103 +0x49a
github.com/kubernetes-incubator/external-dns/controller.(*Controller).RunOnce(0xc0004c0b80, 0xc0006ed7f8, 0x2)
/go/src/github.com/kubernetes-incubator/external-dns/controller/controller.go:67 +0x49
github.com/kubernetes-incubator/external-dns/controller.(*Controller).Run(0xc0004c0b80, 0xc000086960)
/go/src/github.com/kubernetes-incubator/external-dns/controller/controller.go:100 +0x84
main.main() …
```

Fix nil map access of endpoint labels

---

provider/designate.go
provider/designate_test.go

It appears as though the certificate options for OpenStack were only being configured for requests to Designate, and not for the initial authentication requests to Keystone. This change resolves that issue.

Fix TLS issue with OpenStack auth (Designate)

---

provider/domain_filter.go
provider/domain_filter_test.go

While working on PowerDNS domain filter integration and writing test cases, I ran into an issue where domain filters were being applied to non-related zones.
During testing, anexample.org was being matched to a Domain Filter of example.org specified by the user. These are distinct domain names and the expectation is that they should not be considered the same.
Providers that manipulate DNS entries based off of zones rely on this expectation/assumption to make the right decision on which zone to manipulate.
As well, I added additional test coverage around domain filters with "." prefixes to capture what I've seen other provider (eg. Linode) integrations test for, and also how people use domain filters in the field.

Fix domain-filter matching logic to not match similar domain names

---

Dockerfile

https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

MAINTAINER is deprecated - using LABEL instead

---

provider/dyn.go

Line 567: commiting->committing
Line 600: does not exists->does not exist

Fix some typos in  returned messages in dyn.go

---

pkg/apis/externaldns/types.go
provider/azure_test.go
provider/pdns.go

Fix typos: 
1. sychronized->synchronized
2. resouce->resource
3. sepecified-specified

Fix typos: sychronized->synchronized, resouce->resource

---

provider/aws.go
provider/aws_test.go

Fix for https://github.com/kubernetes-incubator/external-dns/issues/726

Matching entire string for wildcard in txt records with prefixes

---

scripts/update_route53_k8s_txt_owner.py

This is a script that we wrote to try to help the migration over to using external-dns.  This script looks at kubernetes ingresses and services (which are the two things we have external-dns looking at) and compares them to existing TXT and A records in route53 to find out where there are gaps.  It then assigns the heritage and owner TXT records where needed so external-dns can take over managing those resources.

Add helper script to update route53 txt owner entries

---

Gopkg.lock
Gopkg.toml
provider/coredns.go
provider/coredns_test.go

This PR is for migrating CoreDNS provider which is based on etcd client v2 to etcd client v3. (Fixes https://github.com/kubernetes-incubator/external-dns/issues/659 )
Also fixed ~~couple of~~ below issue:
- https://github.com/kubernetes-incubator/external-dns/issues/669 external-dns CoreDNS provider is not deleting records in sync mode.
- ~~Endpoint Labels are getting lost in TXT registry. https://github.com/kubernetes-incubator/external-dns/commit/8424d40c5cbdab5cf0c5cd8f3d6ffd2c0071a93e~~
/cc @njuettner @linki @ideahitme

Migrate to use etcd client v3 for CoreDNS provider

---

.travis.yml
Gopkg.lock
Gopkg.toml

new PR's are currently failing due to gometalinter timeouts,
this is now fixed by merging PR https://github.com/kubernetes/repo-infra/pull/90
by setting `GOMETALINTER_DEADLINE` as an env var in travis to increase the timeout

adjust gometalinter timeout by setting env var

---

provider/google.go

Fix for https://github.com/kubernetes-incubator/external-dns/issues/729

panic: assignment to entry in nil map

---

README.md
docs/tutorials/coredns.md

There is no coredns tutorial for externalDNS. This pull request makes
coredns based on minikube for working with externalDNS.

add tutorial for coredns

---

docs/tutorials/azure.md

This PR relates to #500, so I did not think it was that great to write a new ticket (sorry for PRing out of the blue!). The main issue discribed in 500 was that /etc/kubernetes/azure.json is no longer accessible using hostPath in the external-dns container, and this makes the tutorial confusing.
Also, I made some other changes in the tutorial after having had some problems follwing it when setting up external-dns myself. These changes are mainly to make the text more readible, but changes are minor.

Updating Azure tutorial

---

controller/controller.go

Exposes the number of managed Endpoints and DNS records as metrics. /cc @njuettner 
Example:
```console
external_dns_registry_endpoints_total 218
external_dns_source_endpoints_total 176
```
This gives an estimate of how much DNS records ExternalDNS manages for you.
`external_dns_registry_endpoints_total`: all supported records fetched from provider (merged with TXT ownership record)
`external_dns_source_endpoints_total`: all desired Endpoints generated by all Sources

Expose managed resources and records as metrics

---

docs/faq.md

I compared this list to the list in the README.md and left out the service providers.  
I don't know if RFC2136 should be included here.

update the FAQ list of supported DNS providers

---

provider/rfc2136.go

In dry-run mode we need to return early to avoid sending messages.
Fixes #816.

Fix dry-run mode in rfc2136 provider

---

provider/rfc2136.go
provider/rfc2136_test.go

The rfc2136Actions interface was misspelled.
Signed-off-by: Lachlan Cooper <lachlancooper@gmail.com>

Fix typos in rfc2136 provider

---

docs/faq.md

Update FAQ to include information about `source` and `registry` errors exposed by ExternalDNS

Add metrics info to FAQ

---

pkg/apis/externaldns/types.go
pkg/apis/externaldns/types_test.go

AWS API ChangeResourceRecordSets method only allows 1000 ResourceRecord
elements in one call, so the previous value was not very useful.
See the AWS API docs here:
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html#limits-api-requests-changeresourcerecordsets

Change default AWSBatchChangeSize to 1000

---

Gopkg.lock
Gopkg.toml
provider/dyn.go
provider/dyn_test.go

When reconciling DNS zones with thousands of records, the current version of the DYN provider will fetch each and every one of these records one at a time. 
If the zone has 4000 records it would need 13 minutes to retrieve all these records if we don't want to be rate limited by DYN (max 300 requests per minute). This is assuming this instance of external-dns is the only one updating the domain. 
As soon as you add multiple instances of external-dns (different kubernetes clusters updating the same domain), you'll start getting rate limited, so the reconcile loop can easily take hours.
It doesn't seem like its possible to get the entire zone using the REST API, so this patch uses  DYN's SOAP API to retrieve the entire zone with 1 single API call. This will happen every time the serial …

Use SOAP API to improve DYN's providers performance

---

plan/plan.go
plan/plan_test.go

Ensure that we don't consider names with and without a trailing dot
differently at this stage.

Normalize DNS names during planning

---

source/service.go
source/service_test.go

Non statefulset pods associating to a headless service have different
IPs, but have a same hostname. In this case, external-dns registered
only one A records due to attempting to register multiple A records for
a same hostname for each IP.
This patch now registers one A record having multiple IPs.
fixes #549

Support A record for multile IPs for a headless services.

---

docs/tutorials/aws.md

This way the use of `jq`, and the output in this document would make sense.

Make awscli commands use JSON output

---

SECURITY_CONTACTS

As per [responsibilities of a security contact](https://github.com/kubernetes/sig-release/blob/master/security-release-process-documentation/security-release-process.md#responsibilities) i'm taking myself out of the security contacts list. @njuettner will be my replacement.

Remove linki from SECURITY_CONTACTS

---

Gopkg.lock
Gopkg.toml
plan/plan.go

Second try for https://github.com/kubernetes-incubator/external-dns/pull/877
The issue that triggered this: https://github.com/kubernetes-incubator/external-dns/issues/869#issuecomment-458291804
In https://github.com/kubernetes-incubator/external-dns/pull/650 we added that the planning phase is able to detect when provider-specific annotations have changed so that a record update can be triggered (`shouldUpdateProviderSpecific`).
This actually changes the behaviour and leads to `Plan` always thinking there's a change for AWS. The full fix [is more involved](https://github.com/kubernetes-incubator/external-dns/pull/877) and should be fixed at some point. This PR is merely for restoring the original behaviour and dealing with: https://github.com/kubernetes-incubator/external-dns/issues/869#i …

Ignore AWS EvaluateTargetHealth when detecting plan changes

---

plan/plan.go

I believe this will fix the "constant updating" issue introduced in 0.5.10 for all providers (#883, #879) except AWS, which will still require something like #880 to be applied, since that is a different comparison problem of properties that exist on one side only.
At issue is that providers not using the new ProviderSpecific mechanism will have endpoints where ProviderSpecific is `<nil>`, where the endpoints from sources with no ProviderSpecific elements is instead set to an empty list of that type.
This change simply adds a test for the specific test of "provider is nil, source is empty" and returns false.
There may be a better way to fix this impedance mismatch between the two interfaces, but this quick fix should address the majority of problems.
A built container combining this with …

fix test of ProviderSpecific comparison

---

provider/pdns.go
provider/pdns_test.go

* When using Domain Filters with PowerDNS provider and providing
no domain filter, the provider ignores all zones instead of
including all zones which is the default behaviour
* Fixes #826

Fixed PowerDNS Domain Filter Bug

---

docs/contributing/getting-started.md

This PR adds more information to the `Building` section of the getting started guide, by adding the required `make dep` step. 
Closed #908.

Document make dep step which may be needed to run make build

---

OWNERS

In favour of assigning people who are still actively reviewing PR's, I would like to drop people who don't have the time to review or are not active in this project anymore.
This is only a proposal and open for discussion.

Dropping owners

---

README.md

This PR is based on my experience as a total beginner with ExternalDNS: I looked at the documentation (didn't know how it works internally) and it wasn't clear for me if I use both methods (Deploying to a Cluster and Running locally) or just one of them. The PR clarifies this confusion.

Tiny clarification about two available deployment methods.

---

source/ingress.go
source/ingress_test.go
source/service.go
source/service_test.go
source/shared_test.go

This pull requests updates both `source/ingress.go` and `source/service.go` to use Kubernetes Informer data cache rather than making active API server calls. 
Currently, both `source/ingress.go` and `source/service.go` issue `GET` requests on the API server every sync loop to calculate endpoints. The latter actually issues `GET` requests for `Services`, `Pods`, _and) `Nodes` to calculate its endpoints. As @lbernail [pointed out](https://github.com/kubernetes-incubator/external-dns/pull/687#issuecomment-458547769) in a [related pull request](https://github.com/kubernetes-incubator/external-dns/pull/687), these types of active API calls can be expensive and introduce significant latency on large clusters.

Use k8s informer cache instead of making active API GET requests

---

Gopkg.lock
Gopkg.toml
source/gateway_test.go

- Adjusting dep to pull in istio 1.1.0 libraries.
- Updating fake GatewayConfigStore Get method to work with 1.1.0
Tested with `make test` and this worked correctly with my test cluster (while current external-dns could not work if istio 1.1.0-specific features were enabled (like Multicluster Gateways, etc.))
Should fix #933 ... without this patch I can't get external-dns to work on my istio-1.1.0 powered cluster... but I don't personally use SDS yet.  You can pull the compiled/built container image [here](http://quay.io/venezia/external-dns:latest)

Bumping istio to 1.1.0

---

README.md

This PR added more information on the stability matrix for the providers that we discussed in the maintainers meeting on Mar 12th 2019 (notes [here](https://docs.google.com/document/d/1xoo-K1YtJRb8YIkFgpUh371A3OwCeiBY7B8bdJXVipI)).
I did not add a list of names of maintainers, we can do in a later step when it's clear who can do what (I could only add people for the AWS provider right now).

Added stability matrix and minor improvements to README

---

pkg/apis/externaldns/types.go
pkg/apis/externaldns/types_test.go

Fix #941 
I added generic logic to mask config keys which have the tag `secure`.

Add generic logic to remove secrets from logs

---

provider/rfc2136.go

Remove unnecessary parameter in RFC2136 provider

---

docs/tutorials/aws.md

Tutorial specifies version >0.4 which also removed the requirement for a trailing period.  New users could misunderstand the trailing dot as a significant syntax.  Removing the dot simplifies the configuration of the annotation.

Remove superfluous trailing period from hostname

---

docs/tutorials/nginx-ingress.md

[The option isn't part of the the create cluster command](https://cloud.google.com/sdk/gcloud/reference/container/clusters/create).

Remove disable-addon argument from gke + nginx tutorial

---

docs/tutorials/alibabacloud.md

Without this flag, it will be error log below 
```
time="2019-04-14T07:04:52Z" level=fatal msg="Failed to read Alibaba Cloud config file '/etc/kubernetes/alibaba-cloud.json': open /etc/kubernetes/alibaba-cloud.json: no such file or directory"
```
For docs, the roles will enable sts token function , so add this flag.
Pls @njuettner  take a look.

Fix alibaba cloud config file missing by enable sts token

---

provider/aws.go
provider/aws_test.go

When the planner compares the current and desired, Alias records always appear as an update because the TTLs never match. An Alias record has no TTL and the conversion from TXT to Endpoint, assumes the default value.
By setting the ttl when constructing endpoints for Aliases, the planner no longer updates these entries on every interval.
Fixes #974

Set a default TTL for AWS Alias records

---

provider/cloudflare.go
provider/cloudflare_test.go

This is an attempt to fix #887.
I took a bit of a lazy route to implement this, instead of trying to manage equivalence state for record updates and/or refactoring most the provider, I simply took the same solution rancher/external-dns's CloudFlare provider took, and implemented updates as a sequence of delete + create for all records matching the combination of name and type.
CloudFlare does not seem to support records with real 'sets' of targets in basic DNS - it seems to do so in the additional-cost 'load balancing' product - though this should work well in theory.

Add support for multiple target addresses in CloudFlare provider

---

Dockerfile
provider/azure.go
provider/azure_test.go

This PR implements multiple A-record targets, which solves #979.
Tests are added, and I verified it works for me.

Azure: Support multiple A targets.

---

main.go
pkg/apis/externaldns/types.go
pkg/apis/externaldns/types_test.go
provider/ns1.go

This PR adds a flag to customize the API endpoint that the NS1 provider sends updates to (`--ns1-endpoint`).  This enables the NS1 provider to be used with on-prem or otherwise custom instances of NS1.
This PR also adds a flag to enable ignoring SSL verification on traffic sent and received by the NS1 provider (`--ns1-ignoressl`).  This is used for testing the provider against NS1 endpoints that are configured to use self-signed, or otherwise insecure, SSL certificates.

Add --ns1-endpoint and --ns1-ignoressl flags

---

docs/contributing/sources-and-providers.md
pkg/apis/externaldns/types.go
source/empty.go
source/empty_test.go

Add `EmptySource` as a way to help clean up resources in cases where you lose a cluster. 
Our use case:
We spin up many Kubernetes clusters in our test environment with a set of domains that follow the pattern (stable-1, stable-2, stable-3, ...etc). However, since this is our test environment we kill forcefully delete clusters (accidentally or on purpose) without cleaning up services properly. I would like to have an empty source so when we do delete a cluster, we can clean up old DNS entries by using the same params just a different source (empty) without having to bring up the cluster again. 
The alternative to this was updating the `FakeSource` to include another param called `fake-count` or similar which told `FakeSource` to return `n` entries (would set `0` in this case). 
I chose to …

add empty source

---

Dockerfile
Dockerfile.mini

This PR uses the latest base image and final image. The custom alpine image hasn't been updated in 2 years and it probably contains the recently reported CVE.

sanitize dockerfiles for external-dns

---

provider/cloudflare.go
provider/cloudflare_test.go

#970 adds support for multiple target addresses to the CloudFlare provider. However, CloudFlare does not support "sets" of targets for each DNS name/type pair but instead returns a single entry for each name/type/target. This confuses the planner when calculating the set of changes, leading to #992 - where external-dns recreates the same entries over and over.
This pull request changes the CloudFlare provider's Records() method to group all supported records by name and type, and to return a single endpoint with all the targets for each name/type, allowing the planner to compute the correct set of changes.

Fix CloudFlare provider to return a single endpoint for each name/type.

---

docs/tutorials/cloudflare.md

#992 - External-DNS delete and recreate constantly all DNS record
Proposed Changes
* Add documentation about TTL annotation with Cloudflare proxied entries.

docs(cloudflare): set ttl annotation for cloudflare proxied entries to 1

---

go.mod
go.sum

Updates the aws-go-sdk dependency to latest release (`v1.19.41`) to be compatible with [kube-aws-iam-controller](https://github.com/mikkeloscar/kube-aws-iam-controller) (requires `>=v1.16.2`)
Ref: https://github.com/mikkeloscar/kube-aws-iam-controller/blob/master/docs/sdk-configuration.md#golang-aws-sdk

Update aws-go-sdk to be compatible with kube-aws-iam-controller

---

provider/google.go
provider/google_test.go

Before we only filter by the zone ID, which is an integer value, that is
not exposed in the GCP Console and by the related terraform resource.
This allows to filter by either ID or Name whatever is matching.
I also have added some testing for both cases. Wdyt?
This is quite important for using GCP private managed zones, which often have an overlapping name

Google zones should be filter by their ID and Name

---

go.mod
provider/rfc2136.go

fix issue #1081 when merging multiple targets

---

docs/tutorials/alb-ingress.md
endpoint/labels.go
provider/aws.go
provider/aws_test.go
provider/cloudflare_test.go
source/ingress.go
source/ingress_test.go

This PR adds dualstack support for ALB ingress, and fixes issue #520.

add dualstack support for AWS provider with ALB ingress controllers

---

Dockerfile
Dockerfile.mini
Makefile

* Update to the build image to the latest version of Go 1.12.x.
* Ensures all build commands must execute successfully.
* Removes APK index cache from final image, which reduces the final image size by ~2MB.
* Uses UID for `nobody` in order to work with the Kubernetes Pod securityContext runAsNonRoot as it cannot resolve the user ID.
* Adds "mini" to the mini Dockerfile image tag.
* Formatting and style changes.

Update Dockerfiles to follow best practices

---

provider/oci.go
provider/oci_test.go

When more than one oci dns zone exists as a candidate zone for the new/updated records, the zone map was incorrectly built that results in having a map with all keys as zone names while the value will be the same object (the last one in the list). This has caused as the map is copying address of a loop var. This fix addresses that issue.

fixed an issue with handling multiple oci zones

---

README.md

Adds a note about where e2e tests are currently located in the
zalando-incubator/kubernetes-on-aws repository and fixes up a broken
link in README.

Add note about where e2e tests currently located

---

source/source.go

In its current state, `ttlMaximum` causes make to fail build with error:
```sh
source/source.go:71:39: constant 4294967295 overflows int
```
Because `math.MaxUint32` is an untyped integer constant it is converted
to type `int` when used as an interface param, type `int` is signed,
`MaxUint32` is larger than `MaxInt32` and causes the type int to overflow.
Converting `ttlMaximum` to `MaxInt32` stops this overflow.

Changed ttlMaximum to MaxInt32 to allow compilation on 32bit machines

---

docs/20190708-external-dns-incubator.md

I added the initial KEP for the external DNS migration. My goal is to get a review here and then create a more solid KEP into https://github.com/kubernetes/enhancements/tree/master/keps/sig-network. 
I'm looking forward for your feedback @njuettner @linki @hjacobs

Add initial KEP for external DNS.

---

docs/faq.md

As discussed in https://github.com/kubernetes-incubator/external-dns/pull/1103 this PR adds a FAQ for the new `--aws-prefer-cname` flag.

Add FAQ for the new aws-prefer-cname flag

---

provider/aws.go

Useful when the private/public zones are named the same but a problem happens in one of them
Additionally adds info about which Hosted Zone AWS Batch errors are happening in
```
level=error msg="InvalidChangeBatch: [Tried to create resource record set [name=woof.service.example.com., type=CNAME, set-identifier=legacy] but it already exists, Tried to create resource record set [name=best.service.example.com., type=CNAME, set-identifier=legacy] but it already exists, Tried to create resource record set [name=better.service.example.com., type=CNAME, set-identifier=legacy] but it already exists, Tried to create resource record set [name=my.service.example.com., type=CNAME, set-identifier=legacy] but it already exists]\n\tstatus code: 400, request id: XXX-XXX-XXX-XX"
```

Add the AWS Hosted Zone ID to log info

---

source/gateway.go
source/gateway_test.go

One feature that's supported for the Istio Gateway resource is the ability to
restrict what namespace may provide a VirtualService for a given hostname/domain
by specifying it in the form `my-namespace/my-domain.com` which restricts the
availability of `my-domain.com` to the `my-namespace` namespace.
When creating the associated DNS records, the namespace should not be included.
Fixes #1095

fix: support namespaces on the hostnames in istio gateway

---

go.mod
go.sum

Rewriting the timestamp for this import fixes the build for go tip.

Fix build for Go v1.13

---

provider/rdns_test.go

This unit test relies of the iteration order of the map. This is unreliable and prone to flakes as Go randomizes the iteration of maps.

fix flaky unit test in external-dns/provider

---

main.go

This appears to be a regression caused by the accidental removal of this one line in #1080. The result is that `APIRetries` is never set, it defaults to 0 (i.e. "don't retry"), and we end up with intermittent `... level=error msg="Throttling: Rate exceeded\n\tstatus code: 400 ..."` errors.

Fix --aws-api-retries

---

CHANGELOG.md

changelog entry for https://github.com/kubernetes-incubator/external-dns/pull/1158

Update changelog with fix for retries flag

---

provider/aws_sd.go
provider/aws_sd_test.go

This PR is similar to the change made in AWS Route53 provider some time ago (https://github.com/kubernetes-incubator/external-dns/pull/531).
It adds correct handling for AWS NLBs that are having different hostname from ELBs.

AWS-SD: Add support for AWS Network Load Balancers

---

source/ingressroute.go
source/ingressroute_test.go

This PR addresses #1143 by properly checking if an IngressRoute's `Spec.VirtualHost` field is defined (non-`nil`) during endpoint computation.

Support delegate Contour IngressRoutes

---

docs/tutorials/rfc2136.md

Clean up the tutorial and update it to clarify usage with non-BIND DNS servers.
This clarifies the documentation related to issues brought up in #882, but it may or may not fix the issue OP was having.

Update rfc2136 tutorial for use with Microsoft DNS

---

internal/testutils/endpoint.go
provider/inmemory.go
registry/txt.go
registry/txt_test.go

This modifies TXTRegistry.Records() so it won't overwrite any endpoint labels returned by the provider's Records() implementation. This is currently needed to get the designate provider half working because it stores internal recordset IDs in labels and expects them to still be there when ApplyChanges() is called. The change should should be harmless though and not affect other providers.

TXTRegistry: do not overwrite labels of records returned by the provider

---

source/crd.go

Fixes #1106
Added "external-dns/resource=..." field to TXT record when a CRD is used as source.
Added warning when a CR has a target with a "." in the end, which would make external-dns constantly add and remove the record.
Signed-off-by: João Marçal <joao.marcal12@gmail.com>

Improvements to the source CRD

---

docs/tutorials/aws.md

Amazon EKS supports IAM Roles for Service Accounts. It mounts tokens files to `/var/run/secrets/eks.amazonaws.com/serviceaccount/token`. Unfortunately, external-dns runs as 'nobody' so it cannot access this file. External DNS is then unable to make any AWS API calls to work:
```
time="2019-09-11T07:31:53Z" level=error msg="WebIdentityErr: unable to read file at /var/run/secrets/eks.amazonaws.com/serviceaccount/token\ncaused by: open /var/run/secrets/eks.amazonaws.com/serviceaccount/token: permission denied"
```
See: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html
Below are the file permissions mounted on External DNS pod:
```
~ $ ls -al /var/run/secrets/eks.amazonaws.com/serviceaccount/
total 0
drwxrwxrwt    3 root     root …
```

Fix AWS IAM Roles for Service Accounts permission problem.

---

docs/tutorials/cloudflare.md
go.mod
go.sum
provider/cloudflare.go
provider/cloudflare_test.go

Adds support for Cloudflare authentication via [API Token](https://blog.cloudflare.com/api-tokens-general-availability/)
By default prefers using API token auth if both auth methods are set
Ref https://github.com/kubernetes-incubator/external-dns/issues/1127
Tested against Cloudflare with different configuration options & test suite passes

Support Cloudflare API Token Auth

---

provider/rfc2136.go
provider/rfc2136_test.go

This changes the `ApplyChanges` in the RFC2136 provider to issue a batch update to the DNS server instead of issueing an update for each updated record. An update is not sent to the server if there are no changes to send.
Also the `RemoveRecord` function only issues a RR removal instead of an RRset removal so external-dns is now able to remove distinct records.
Some tests for the RFC2136 provider are fixed and added.

Change ApplyChanges in RFC2136 to batch update

---

README.md
docs/faq.md
docs/tutorials/aws.md

A few documentation updates to attempt to make the use of namespace more clear. Specifically around issues that arise when using the wrong namespace.
I got stuck for a few days when first trying out external-dns when I didn't quite understand where the namespace came into play. Specifically I was seeing an error like below which I added to the FAQ. Might be helpful for folks we get stuck to be able to find this and a (potential) solution.
```
FATA[0060] failed to sync cache: timed out waiting for the condition
```
Open to making tweaks as necessary for this to fit in with existing docs.
Fixes #1216

Propose a few doc changes to make the use of namespace more clear

---

docs/tutorials/externalname.md
docs/tutorials/hostport.md

* arg --debug is now --log-level=debug
* flag --log-level was merged 2017 with
PR https://github.com/kubernetes-sigs/external-dns/pull/339

docs: fix log-level param in tutorials

---

provider/aws.go

At the bottom of https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-endpoints.html it says:
> Amazon Route 53 hosted Zone ID for the regional endpoint in the AWS GovCloud (US) region is Z1K6XKP9SAGWDV.

Add gov LB hosted zone

---

docs/tutorials/aws.md

`Deployment` has been removed from `apiVersion: extensions/v1beta1`
See https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

Fix tutorial for kubernetes 1.16+

---

provider/google.go

Implements https://github.com/kubernetes-sigs/external-dns/issues/1264

Use non-deprecated initializer with context

---

docs/tutorials/digitalocean.md

The Digital Ocean guide is using old `extensions/v1beta1` API version and cannot be copypasted on Kubernets 1.16. This PR changes it to `apps/v1`.

Use apps/v1 for the deployment to be compatible with Kubernetes 1.16

---

internal/testutils/endpoint.go
provider/azure_test.go
provider/transip.go
source/ingress.go
source/ingressroute.go

* comment on exported type/function/method should be of the form "XXX ..."
* if block ends with a return statement, so drop this else and outdent its block

Normalize function return and comments on exported type

---

docs/tutorials/aws.md
endpoint/endpoint.go
internal/testutils/endpoint.go
internal/testutils/endpoint_test.go
plan/plan.go
plan/plan_test.go
provider/aws.go
provider/aws_test.go
provider/inmemory.go
provider/inmemory_test.go
registry/txt.go
registry/txt_test.go
source/dedup_source.go
source/gateway.go
source/ingress.go
source/ingressroute.go
source/service.go
source/source.go

This adds support for all AWS Route53 routing policies, namely:
* simple (default)
* weighted
* latency
* failover
* geolocation
* multi value answer
These routing policies allow to create multiple records with the same
name, but different "SetIdentifiers". Therefor, as a prerequisite for
implementing support for above routing policies, there is a new
"abstraction layer" added that handles this SetIdentifier by adding a
new attribute in the Endpoint struct and adding another level in the
plan table.
This closes #196, #469, #571.
ToDo:

[RFC] Add support for all AWS Route53 routing policies; add additional Setldentifier abstraction layer

---

.travis.yml
Makefile
provider/azure_private_dns.go
provider/azure_privatedns_test.go
provider/azure_test.go
provider/designate.go
source/node_test.go

Update golangci-lint to the latest version:
https://github.com/golangci/golangci-lint/releases/tag/v1.21.0

Bump the version of golangci-lint

---

docs/tutorials/dnsimple.md

Sets the ServiceAccount so it picks up the correct rbac rules as pointed out here: https://github.com/kubernetes-sigs/external-dns/issues/1303

Add missing service account to spec

---

docs/tutorials/azure.md

Switched the direction of the arrows in the documentation, they should indicate where the value comes from and where it goes.

Fix confusing arrow direction

---

docs/tutorials/azure-private-dns.md

First use showed the tutorial for _Azure DNS & Azure Private DNS_ to be not practically usable for all users.
In particular, it required some special knowledge about the required configuration of the employeed _nginx-ingress-controller_.
This PR refines the tutorial to make endusers be able to work through it completely.

Reworked tutorial for Azure Private DNS

---

docs/contributing/crd-source.md
docs/contributing/crd-source/crd-manifest.yaml

* Describe RBAC configuration for CRD source type
* Remove unneeded `status` section from sample crd manifest and avoid validation failure

CRD documentation and sample fixes

---

README.md

This removes some old information on incubation. By looking at other projects, I think we don't need to add any specific new info.
/cc @njuettner

Remove incubator references in README

---

go.mod
go.sum

**Motivation:**
Through the recent upgrade of various libraries (primarily originating from k8s.io/*), we see an increased usage of `klog` in upstream libraries used by externaldns.
Because the configuration of `klog` is not (fully) aligned with the one of `logrus`, and because it seems that klog cannot be replaced by logrus in a drop-in fashion, we currently face a slightly flawed logging behaviour of external-dns.
In particular, we see these messages. They are on error-level.
```
E0107 10:38:02.210151    6814 round_trippers.go:324] CancelRequest not implemented by *instrumented_http.Transport
E0107 10:38:02.210345    6814 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
```
So far, external-dns …

Suppress noisy logging of klog

---

README.md
docs/tutorials/aws-sd.md
main.go
provider/aws_sd.go

Amazon Route 53 `Auto Naming` (aka `Service Discovery`) has been released as a separate service, `AWS Cloud Map`. The goal of this change is to update the documentation to avoid confusion about the service name.

AWS-SD: Rebrand AWS Auto Naming to Cloud Map

---

cloudbuild.yaml

ERROR: (gcloud.builds.submit) INVALID_ARGUMENT: invalid build: key "_PULL_BASE_REF" in the substitution data is not matched in the template

Fix invalid build: key "_PULL_BASE_REF" in cloudbuild.yaml

---

Dockerfile
Makefile
cloudbuild.yaml

The new build process lead to losing the LDFLAGS for the version, so `--version` wouldn't correctly print the version anymore. This fixes it.

Add version to binary for --version flag

---

docs/tutorials/aws-sd.md

Updating tutorial with aws-sd to include guide for adding AWS_REGION env. Missing this env will cause region error message and external-dns won't work.
> level=error msg="MissingRegion: could not find region configuration"
ref: https://github.com/kubernetes-sigs/external-dns/issues/584

docs: add REgion for aws-sd external-dns deployment

---

docs/tutorials/aws.md

Using EC2 Instance Roles to provide Route 53 permissions is overly
permissive and dangerous.  Emphasize using alternatives such
as EKS IAM Roles for Service Accounts, kiam, or kube2iam that
limit access to the ExternalDNS pod.

Update AWS documentation

---

docs/tutorials/istio.md

* Add instructions to existing Istio users to update `external-dns` settings
* Also including clusters with `clusterrole` setup.
* Added a section to show users what command is to use to update an existing `Deployment`
* For Clusters with `RBAC`, the extra command to update the `ClusterRole` with the `istio-gateway` params
https://github.com/marcellodesales/external-dns/blob/patch-1/docs/tutorials/istio.md#update-existing-existing-dns-deployment
* The section is to help users to debug and results while making changes.
* The successful execution of the creation of `dns` entries for a module will show the successful execution.
* On the other hand, it will show errors that can be related to the lack of role permissions.
https://github.com/marcellodesales/external-dns/blob/patch-1/docs/tutoria …

istio.md: update existing external-dns to enable Istio Gateway DNS for customers 

---

docs/tutorials/azure-private-dns.md
provider/azure_private_dns.go

**Issue**
The function detecting the Azure Private DNS Zones to manage has an endless loop because the iterator on the underlying collection is not moved properly in case zones _not matching_ zone-filters are found.
**Fix**
Change the loop by moving the iterator in all cases.

Azure Private DNS: Fix endless loop in zone-detection

---

provider/azure_private_dns.go
provider/azure_privatedns_test.go

Due to the missing `/` the record type of existing records had `/` as a prefix (i.e. `/A`). Condition in https://github.com/kubernetes-sigs/external-dns/blob/f400ded46cd1bd0a2ed133a68b2e084f7cb40119/plan/plan.go#L236-L238 was therefore never true.
Fixes #1373

Fix updates of unchanged records for Azure Private DNS

---

.github/ISSUE_TEMPLATE/---bug-report.md
.github/ISSUE_TEMPLATE/--enhancement-request.md
.github/ISSUE_TEMPLATE/-support-request.md

I think there's a lack of quality when it comes to external-dns issues. I'd like to improve it by providing templates which help user to fill out issues properly.

Adding issue templates

---

provider/azure.go
provider/azure_test.go

Due to some historical reason, for clusters using managed identity, they will use "msi" as placeholder in azure.json. In this case, we shouldn't try to use SPN to authenticate.

fix(azure): not use SPN to authenticate when clientid or secret is 'msi'

---

source/service.go
source/service_test.go

Fixes #1015 
PR #645 introduced an issue where endpoints for headless services could return duplicate target IP addresses, which the Route53 API does not allow. This PR ensures that an endpoint can only point to a unique set of target IP addresses.

Remove duplicate targets from endpoints for headless services

---

main.go
pkg/apis/externaldns/types.go
pkg/apis/externaldns/validation/validation.go
pkg/apis/externaldns/validation/validation_test.go
provider/rfc2136.go
provider/rfc2136_test.go

This pr also fulfills #1249 by allowing a minimum TTL to RFC which can also be used as a default TTL value.

Add option to define minimum TTL for rfc2136 provider

---

source/service_test.go

This somehow slipped in during the last merge.

Use correct fields for test to allow compilation again

---

source/routegroup.go

Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

fix: return early if tokenfile could not be read

---

pkg/apis/externaldns/types.go

Adds the new source to the docs for the source flag as well.

Add skipper routegroups to source flag documentation

---

provider/ovh.go
provider/ovh_test.go

Otherwise build fails with
```
provider/ovh.go:50:15: undefined: DomainFilter
make: *** [Makefile:57: build/external-dns] Error 2
```

Fix DomainFilter type in OVH provider

---

CHANGELOG.md
controller/controller.go

* Prometheus metric to see when external-dns had the last successful sync with the DNS provider

Prometheus metric: timestamp of last successful sync with the DNS provider

---

source/crd.go
source/crd_test.go
source/store.go

* Ability to use `--annotation-filter` for CRD source
* Use case is similar to https://github.com/kubernetes-sigs/external-dns/blob/master/docs/faq.md#running-an-internal-and-external-dns-service
but for CRD source, effectively DNSEndpoints instead of Ingresses

Implement annotation filter for CRD source

---

Dockerfile
go.mod

external dns crashed with some linux kernel-versions.
https://go-review.googlesource.com/c/go/+/223121/
with go 1.14.1 it is fixed.

update to go 1.14

---

provider/coredns.go

Formatting is wrong, currently breaks our CI 😞

Fix: file coredns.go is not `goimports`-ed

---

go.mod
go.sum

This removes one more unnecessary `go.mod` `replace`.
cc @njuettner

update akamai openapi dependency

---

provider/coredns.go
provider/coredns_test.go

* Fixes https://github.com/kubernetes-sigs/external-dns/issues/1313
* Logic is to have unique key for every of multiple `ep.Targets` and keep
them around in `ep.Labels` for further consistency
* Unit test is not very strict as testing functions are not ready for
multiple Services with the same key but is imho good enough

Multiple A records support for the same FQDN

---

docs/tutorials/openshift.md
go.mod
go.sum
pkg/apis/externaldns/types.go
source/ocproute.go
source/store.go
source/store_test.go

This implements a new source type "openshift-route" and adds support for openshift routes #706
I've taken the mentioned ocproute implementation from https://github.com/KohlsTechnology/external-dns/blob/timcurless-feature/source/ocproute.go and rebased it to master.
Tested against OpenShift 3.11 and Infoblox as provider.

Support for openshift routes

---

docs/tutorials/rfc2136.md

Added documentation to show the use of the `--rfc2136-insecure` flag when integrating with Windows DNS when using insecure zone updates.

Fix RFC2316 Windows Documentation

---

go.mod
go.sum
provider/cloudflare_test.go
provider/provider_test.go

This PR is first stepping stone to implement fix for #1514. It improves test suite in a way that documents current behavior in tests and will allow to change it in the future. Changes are:
1. Merge 3 separate mock clients into single, configurable one
2. Allow to introspect actions performed by provider on client and set expectations on them
3. Make sure each cloudflare test starts with "TestCloudflare" for easy targeting with `-run` flag
4. Improve ApplyChanges test so it shows that indeed Create is performed instead of Update
5. Disable logrus logging in tests in `provider/provider_test.go` so it's easier to see test errors
6. Rewrites existing tests in a way that is agnostic to implementation details (i.e. now tests don't use methods like `newCloudFlareChanges`)
6. Adds extra test that …

Improve Cloudflare tests in preparation to fix other issues

---

endpoint/endpoint.go
provider/aws_test.go
provider/cloudflare_test.go
provider/ovh_test.go
provider/vultr.go
source/routegroup.go

This PR fixes the golint and gofmt warnings shown on goreportcard https://goreportcard.com/report/github.com/kubernetes-sigs/external-dns#golint

Fix goreportcard warnings

---

docs/ttl.md

This fixes a typo `docs/ttl.md`

Fix typo in ttl.md

---

.travis.yml
Makefile
internal/config/config.go
internal/testutils/init.go
source/gateway.go
source/ingress.go
source/ingress_test.go
source/ingressroute.go
source/node.go
source/ocproute.go
source/routegroup_test.go
source/service.go
source/service_test.go
source/source.go

Reduces test time on travis to 4 minutes by:
- making polling for changes faster in test environment (1 second -> 10 milliseconds)
- preserving go mod cache directory between builds
- disabling logs in test by default (can be overridden with DEBUG=info env variable)
- paralleliziling linting and coverage runs on travis

Make tests faster

---

provider/cloudflare/OWNERS
provider/coredns/OWNERS

Part of https://github.com/kubernetes-sigs/external-dns/issues/1558 
This is at the moment only for the providers part. I will do the sources later as they are less critical right now. 
/cc @njuettner @ytsarev @sheerun

Add owners for cloudflare and coredns providers

---

provider/rfc2136/rfc2136.go

This is an import of the fix for issue 10135 in the rancher fork of this
project ( rancher/rancher#10135 ).
This is a duplicate to PR #1589 but made against master.

Fix issue with too large DNS messages

---

main.go
pkg/apis/externaldns/types.go
pkg/apis/externaldns/validation/validation.go
registry/txt.go
registry/txt_test.go

This PR solves #1482 
It adds a new --txt-suffix feature which creates TXT-records where the suffix is appended to the host portion of the DNSName.
Example:
DNSName test.example.com
txt-suffix: "-txt"
TXT-record generated: test-txt.example.com
This gives a cleaner overview in alphabetically sorted DNS management GUIs.

add --txt-suffix feature

---

provider/aws/aws.go

Fixes https://github.com/kubernetes-sigs/external-dns/issues/1550;
https://docs.aws.amazon.com/general/latest/gr/elb.html now has documentation for the Govcloud regions as well

Update Govcloud provider hosted zones

---

provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_test.go

This PR is a rebased and cleaned up #1307
> This commit _should_ help #1127. While users in the past were able to
define ZoneIDFilter for this provider, it did not actually do anything
under the hood.
> 
> In this case, we're changing Zones() to iterate over the provided
zoneIDs and return only those zones.
> 
> I would have also done this for domainFilter, but unfortunately the
CloudFlare API requires that in order to list zones (and find them by
name) that you have "all" permissions, which seems silly. After talking
to their support, this is probably the best way to do this.

Allow ZoneIDFilter for Cloudflare

---

docs/tutorials/hostport.md

Fix a typo and update the headless service name to be consistent.

Use consistent headless service name in example

---

source/gateway.go
source/gateway_test.go

This cleans the istio gateway logic up a bit. Trying to remove duplication where I can. Hopefully this code is more readable :)

remove some code duplication in gateway source

---

provider/awssd/aws_sd_test.go

This fixes the test failures observed in the Travis `Go tip` job.
This change follows best practices and allows for forward compatibility with future versions of Go.
`string(int)` is problematic as it interprets the `int` as a rune constant as opposed to formatting it as a string which is our actual intent.
For more details, go [here](https://github.com/golang/go/issues/3939).

fix convert int to string bug

---

.golangci.yml
Makefile
controller/controller.go
controller/controller_test.go
internal/config/config.go
internal/testutils/endpoint.go
internal/testutils/init.go
provider/akamai/akamai.go
provider/alibabacloud/alibaba_cloud.go
provider/aws/aws.go
provider/coredns/coredns.go
provider/digitalocean/digital_ocean.go
provider/dnsimple/dnsimple.go
provider/dyn/dyn.go
provider/linode/linode.go
provider/ns1/ns1.go
provider/oci/oci.go
provider/oci/oci_test.go
provider/ovh/ovh.go
provider/pdns/pdns.go
provider/rcode0/rcode0.go
provider/rfc2136/rfc2136.go
provider/vinyldns/vinyldns.go
provider/vultr/vultr.go
source/gateway.go
source/source.go

Towards https://github.com/kubernetes-sigs/external-dns/pull/1555
It seems me missed quite a lot of good linters. I added more and there were also a lot of minor nits inside the code which I've fixed.
The goal here would be to improve in general our code quality. It make sense for the future to even add more linters but I think this is a good starting point.

improve linter quality for external-dns

---

docs/tutorials/digitalocean.md
main.go
pkg/apis/externaldns/types.go
pkg/apis/externaldns/types_test.go
provider/digitalocean/digital_ocean.go
provider/digitalocean/digital_ocean_test.go

The default API page size for the DigitalOcean API [is 20 objects](https://developers.digitalocean.com/documentation/v2/#links). Increase to 200 to reduce the number of API calls required to enumerate domains and records. Should fix https://github.com/kubernetes-sigs/external-dns/issues/1429.

digitalocean: increase API page size

---

provider/rfc2136/rfc2136.go
provider/rfc2136/rfc2136_test.go

When receiving an update, we should be removing the old record and
adding the new.  Previously, we were removing and readding the new
record, which would cause the old DNS record to be left lying around.

Fix handling of DNS updates for RFC2136 provider.

---

source/ingress_test.go

Various tests in `testIngressEndpoints` in `source/ingress_test.go` consistently fail for me when I run `make build.push` to publish a custom `external-dns` image (with `IMAGE_REGISTRY` overridden). The specific sub-test changes each time. Increasing the 3 second wait for Ingress resources to 6 seconds fixes the issue by giving the tests more time to see the relevant Ingress resources appear in the informer cache.
A better solution would be to not poll and actually attach a watcher to wait for the API object additions to stabilize.

increase test timeout to fix intermittent failures of ingress tests

---

go.mod
go.sum
provider/vultr/vultr.go

Bumping the govultr client to the latest version and making some minor changes. In the DNSRecord struct priority is now a pointer so I adjusted the code to handle this appropriately.

Vultr : Version bump + changes

---

kustomize/external-dns-clusterrole.yaml

With the latest release, we need endpoints permission in the ClusterRole. I'm adding this to the kustomize base to not reduce friction for the user. Of course, kustomize allows for full customization of the YAML so that isn't strictly necessary.

Add endpoints to kustomize base

---

docs/tutorials/istio.md

so I've tried to deploy it with 1.0 version:
```
service/httpbin created
error: unable to recognize "https://raw.githubusercontent.com/istio/istio/release-1.0/samples/httpbin/httpbin.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
```

Upgrade istio httpbin from 1.0 to 1.6 version

---

main.go
pkg/apis/externaldns/types.go
source/store.go
source/store_test.go

This flag is no longer used as we use the gatewaySelectors to retrieve the IngressGateway services. So we don't need to specify the gateway service names explicitly anymore

rm unused flag param istio-ingressgateways

---

docs/ttl.md

This is a small documentation update. TTL support in the DNSimple provider was added in #477.

Update TTL docs to confirm DNSimple support

---

docs/tutorials/istio.md
internal/testutils/mock_source.go
pkg/apis/externaldns/types.go
source/gateway.go
source/gateway_test.go
source/source_test.go
source/store.go
source/virtualservice.go
source/virtualservice_test.go

Raising this PR since we would really love to test this feature out in our Istio setup. I have seen that there is a lot of request for this PR to be merged.
This is a dup of #1358. Thanks to @devkid and @elsesiy for their efforts in creating this
Closes #1340 
Closes #1358

add new source for istio virtual services

---

CHANGELOG.md
kustomize/external-dns-deployment.yaml

The serviceaccount created by Kustomize is not referenced in the deployment, leading to crash looping pod due to insufficient permissions.

fix: add serviceaccount name in kustomize deployment

---

CHANGELOG.md
go.mod
go.sum

This PR updates the Oracle OCI SDK to the latest released version.  The version currently used in master is over two years old, and will probably not support some of the additional changes (in subsequent PRs) I'd like to make.
- [ x] Update changelog in CHANGELOG.md, use section "Unreleased".

Upgrade Oracle OCI SDK

---

docs/tutorials/rfc2136.md

Now that `--rfc2136-min-ttl` is an option, show how to set it and also how to override it using an annotation.

Improve documentation about rfc2136 TTLs

---

CHANGELOG.md
provider/aws/aws.go

When faced with errors from cloud providers (like "Throttling: Rate exceeded"), it's not always easy to find what operation caused the failure, and what action was aborted, if any.
Let's make it easier to identify an error source (and affected object when possible) on AWS by providing more context (and by using easy to find error messages).

aws: errors with context

---

kustomize/external-dns-deployment.yaml

Updating the kustomization was missing during the release process.
However, I can't seem to see an image for 0.7.3 up at https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/US/external-dns/external-dns?gcrImageListsize=30 yet. When/how are they uploaded?

Update kustomization for 0.7.3 release

---

source/gateway.go
source/gateway_test.go

Fixes #1518
Fixes #1624 
Istio allows `*` or `namespace/*` as `Gateway` hosts, meaning that it selects all `VirtualService` hosts from the specified namespace (or all namespaces if none is specified).
This PR skips such hosts to avoid attempting to create DNS records for `*` (as described in the linked issue this currently causes external-dns to crash).

Ignore wildcard hosts in Istio gateways

---

.github/workflows/ci.yml
.golangci.yml
internal/testutils/init.go
main.go
pkg/apis/externaldns/types.go
provider/akamai/akamai.go
provider/hetzner/hetzner.go
provider/scaleway/scaleway.go
provider/ultradns/ultradns.go
provider/vultr/vultr.go
source/routegroup.go
source/source.go

I was wondering why the linting never pointed out the import order issues only to find out we were using the old import prefix in the golang-ci config YAML :/

fix goimports local import order and update golangci-lint

---

README.md

v0.5 is no longer the latest version of ExternalDNS, and there is a
separate header for the current latest version (v0.7).

docs: cleanup version roadmap docs

---

provider/aws/aws.go

External DNS should use ALIAS for AWS Global Accelerator instead of CNAME.
ZoneId defined there: https://docs.aws.amazon.com/Route53/latest/APIReference/API_AliasTarget.html
DNS name defined there:
https://docs.aws.amazon.com/global-accelerator/latest/dg/introduction-components.html

External DNS should uses ALIAS for AWS Global Accelerator

---

docs/tutorials/gke.md

when using `registry=txt` option, make sure to also use the `txt-prefix` and `txt-owner-id` options as well. If you try to create a `TXT` record without a prefix, it will try to create a `TXT` record with the same name as your actual DNS record and fail (creating a stranded record `external-dns` cannot manage).

added --txt-prefix to google deployment

---

provider/aws/aws.go

utilize the errors package for error handling

---

pkg/apis/externaldns/types.go

This field was added by mistake, I believe, in https://github.com/kubernetes-sigs/external-dns/pull/1636/files

remove unused field IstioIngressGatewayServices

---

CHANGELOG.md
provider/alibabacloud/alibaba_cloud.go
provider/alibabacloud/alibaba_cloud_test.go

no sure why set ttl to `0` when ttl act actually is `600`
this will get the controller keep update A record when use crd source
because `shouldUpdateTTL` will always be `true`

fix alibaba cloud ducp create record

---

CHANGELOG.md
docs/faq.md

A table of the available metrics is provided so end users do not have to
dig through the code to determine what metrics they have available to
them at runtime.

provide documentation of available prometheus metrics

---

.github/pull_request_template.md
CHANGELOG.md

* Added unit tests to the checklist
* Added end user docs to the checklist
* Added link to the contributing docs
* Added section for description and issue links

docs: enhance pull request template

---

CHANGELOG.md
registry/txt.go
registry/txt_test.go

Fixes https://github.com/kubernetes-sigs/external-dns/issues/1668

Fix index out of range when hostname has no dots

---

docs/faq.md

I added an abstract in the FAQ to point out that --annotation-filter will always apply for each given source.
Fixes #1606 
**Checklist**

Updated FAQ for usage of annotation-filter

---

OWNERS

The goal of this pull requests it to make it easier for contributors to identify the active project maintainers, so that there is not confusion around pull requests reviews.
Is related to #1558.
**Checklist**

Move Inactive Maintainers To Emeritus Approvers

---

CHANGELOG.md
provider/azure/azure_private_dns.go
provider/azure/azure_privatedns_test.go

The PrivateZoneClient by default communicates to the AzurePublicCloud resource manager endpoint.
To make the `azure_private_dns` work with other clouds like
* AzureUSGovernmentCloud 
* AzureChinaCloud
* AzureGermanCloud
it should use the endpoint specific to the selected cloud.
This change makes it behave like the `NewAzureProvider` from `azure.go`

Enable azure_private_dns to work with non "AzurePublicCloud" clouds

---

CHANGELOG.md
README.md
docs/tutorials/gke.md
docs/tutorials/nginx-ingress.md

Add instructions for using GKE workload identity to allow ExternalDNS
to authenticate against Google Cloud DNS APIs. Use modern Docker
images.  Add blog link to README.
Signed-off-by: David Dooling <dooling@gmail.com>
**Checklist**

Add tutorial for GKE with workload identity

---

.github/workflows/ci.yml
CHANGELOG.md
Makefile

**Fixes test coverage with coveralls **
This PR fixes the github CI action to generate a coverprofile.
Fixes #1755 
**Checklist**

Fixes coverall, #1755

---

.github/pull_request_template.md

This PR removes the changelog requirement from the new PR template. We figured that this was causing a lot of unfair conflicts for users. https://github.com/kubernetes-sigs/external-dns/issues/1754 will address the issue of generating the final changelog.

Remove changelog from PR template

---

CHANGELOG.md
README.md
docs/contributing/getting-started.md

Added a quick start section to the contributing documentation. The purpose of this documentation is to help new contributors get started working with the external-dns project.
Updated `docs/contributing/getting-started.md` with recommend local development workflow. Removed documentation from `README.md` for compiling from source.
Is related to #1558 
**Checklist**

Add quick start section to contributor docs

---

CHANGELOG.md
CONTRIBUTING.md
README.md

The goal of this change is to improve the external-dns contributor experience and encourage more community members to participate. This is the first of two pull requests to improve the contributor experience. The next pull request will update the files under `docs/contributing`.
Is related to #1558.
**Checklist**

Update Contributing Documentation

---

docs/faq.md
source/service.go
source/service_test.go
source/source.go

Scenario: in AWS with a private hosted zone, and instances with both public and private IPs, I would like some NodePort services to be registered in DNS with the node's _private_ IP so that they're only resolvable within my VPC.
This is my reattempt at https://github.com/kubernetes-sigs/external-dns/pull/898 since it appears abandoned, and I think that having the public/private interface selection should happen on a per-service basis rather than globally.
I'm open to suggestions on what the annotation should be renamed to, consider "access" a placeholder...
Finally, this change should be backwards compatible - if the annotation is not present we fall through to the previous behavior.

add service annotation to set public/private iface for NodePort

---

README.md
source/service.go
source/service_test.go

Add feature to publish ExternalIPs for LoadBalancer services.
Use case:
* Running K8s cluster on Bare-metal behind NAT (1:1)
* [MetalLB](https://github.com/metallb/metallb) implements on-premises LoadBalancer and assigns `loadBalancerIP` from the given pool (internal network IP).
* Running Services of type 'LoadBalancer';
* By adding external IP address we can propagate a DNS entry with publicly available external IP address instead of the internal one.
Currently, ExternalIPs in LoadBalancer services are not processed at all, so there are no breaking changes as far as I can tell.
Note: ExternalIP value is defined separately, so it's out of the scope of ExternalDNS. The only thing needed is to prefer `externalIP` to `loadBalancerIP` and let ExternalDNS do the job.

Publish ExternalIPs for LoadBalancer services

---

main.go
pkg/apis/externaldns/types.go
source/crd.go
source/crd_test.go
source/store.go

Fixes #1450
Added labelFilter flag for source CRD and added tests to test new behaviour.
Signed-off-by: João Marçal joao.marcal12@gmail.com

Added labelFilter for source CRD

---

docs/tutorials/scaleway.md

Scaleway provider doesn't work with `0.7.3`. Documentation needs to be updated as followed.

fix: scaleway doc bump version to 0.7.4

---

.github/workflows/ci.yml
docs/contributing/getting-started.md

This PR adds support for nektos/act to run github actions locally.
**Checklist**

Add support for nektos/act

---

docs/tutorials/aws.md
provider/aws/aws.go
provider/aws/aws_test.go

This PR allows to associate the DNS records with health checks. This helps in auto fail over in case one of the record is having issues.

allow to associate aws dns records with health checks

---

.github/ISSUE_TEMPLATE/-support-request.md

The label triage/support has been reclassified as kind/support. The
kind/* family of labels makes more logical sense, as they describe the
"kind" of thing an issue or PR is.
For more information, see the announcement email:
https://groups.google.com/g/kubernetes-dev/c/YcaJpsjjLKw/m/i15cLLx5CAAJ

Update triage/support label references to kind/support

---

docs/release.md
releaser.sh
scripts/kustomize-version-udapter.sh
scripts/releaser.sh

Closes #1754 .
This is largely the same script from https://github.com/cli/cli/blob/trunk/script/changelog, requires `gh` to be run as well. It generates a release note compliant to what we have been using in ExternalDNS till today.
The scripts must be run manually by whoever has permissions to create releases. My initial idea was to use GitHub actions today by leveraging a manually triggered workflow, but actions does not support limiting who can run workflows to specific users or groups. This means that any user with write access could potentially make a release and that's clearly not ideal. I'll wait building the automation for that for when actions will support any functionality that will allow us to limit who can do releases.
This PR also updates the documentation for the release …

Adds release script

---

provider/infoblox/infoblox.go
provider/infoblox/infoblox_test.go

Just fetch zones matching a given view from Infoblox. This reduces the load on Infoblox and the resultset received.
**Checklist**

Infoblox skip zones not matching a given view

---

Makefile

TL;DR: @justinsb saves the day.
At the time of writing this issue, all the docker builds for the staging images fail. This is due to the fact that cloud builder fails to pull some valid images. I think this is the same issue mentioned in https://github.com/kubernetes-sigs/cluster-addons/pull/84 , so I will try to pre-pull the images that we will use.
/cc @njuettner

Pre pull of images to make builds pass

---

cloudbuild.yaml

Builds are still not passing, this time due to a timeout. Follow up of https://github.com/kubernetes-sigs/external-dns/pull/1821 
This should give us enough time to build 2 architectures, but it's mostly trial and error at this point.

Bump cloudbuild timeout for new release process

---

provider/aws/aws.go
provider/aws/aws_test.go

This addresses external-dns running in af-south-1 whereby only CNAME entries are created when A records are intended
Adding Africa (Cape Town) ELB endpoint and hosted zone id's
Fixes #1830 
**Checklist**

aws-r53 adding Africa (Cape Town) ELB endpoints and hosted zone id's

---

docs/tutorials/cloudflare.md

This change adds the `"watch"` configuration for the `"nodes"` resource under the example RBAC configuration for Cloudflare.
The two stable providers contain this configuration. [AWS Route 53 documentation](https://github.com/kubernetes-sigs/external-dns/blame/master/docs/tutorials/aws.md#L182) has this permission, and so does the [GKE documentation](https://github.com/kubernetes-sigs/external-dns/blame/master/docs/tutorials/gke.md#L86).
This resolved a problem for me where the pod would timeout and crash with the following error `"failed to sync cache: timed out waiting for the condition"`
**Checklist**

cloudflare: readme update for RBAC config

---

.gitignore
README.md
docs/tutorials/ns-record.md
endpoint/endpoint.go
go.sum
plan/plan.go
provider/cloudflare/cloudflare_test.go
provider/ovh/ovh_test.go
provider/rcode0/rcode0_test.go
provider/recordfilter.go
source/crd_test.go

Add `NS` record support.
End-to-end tested with `crd` source and `aws` provider.
Partially fixes #1647 
**Checklist**

Add NS record support

---

Makefile

Add arm32v7 arch for images

---

Makefile

Follow up to https://github.com/kubernetes-sigs/external-dns/pull/1838.
/cc @njuettner @xUnholy

Add GOARM for arm32v7 images

---

docs/faq.md

This PR adds two FAQ entries to help users understand what architectures and operating systems are supported.
Closes https://github.com/kubernetes-sigs/external-dns/issues/1443.
/cc @njuettner

Add FAQ for multiarch images

---

docs/tutorials/ovh.md

External DNS now require permissions on endpoints resource. Adding it in the OVH tutorial manifest following this comment https://github.com/kubernetes-sigs/external-dns/issues/961#issuecomment-664849509 for making it continue to work out of the box.
**Checklist**

Fix OVH tutorial to match new permissions

---

provider/infoblox/infoblox.go
provider/infoblox/infoblox_test.go

Proper PR for this one:
https://github.com/kubernetes-sigs/external-dns/pull/1445

Infoblox multiple A records support

---

docs/tutorials/coredns.md

This PR fixes the syntax highlighting of the diff block in the CoreDNS tutorial.

Fix diff highlighting in CoreDNS tutorial

---

provider/aws/aws.go
provider/aws/aws_test.go

Currently the AWS provider cannot handle record type changes. It always
attempts to UPSERT such updates, which will fail the entire zone batch
of changes. As a result, a single resource change can break all the
updates for the entire zone.
This change modifies the AWS behavior to correctly identify when the
record type changes and perform a batched DELETE and CREATE to update
the record successfully.
Special logic is required to handle ALIAS records which are not directly
encoded by the generic external-dns code, and relies on
convention (using a CNAME record type internally). I'm not sure this is
ideal as it's fairly error prone, and would prefer to see direct support
for such ALIAS types, but I've left it alone in this change.
Fixes …

Allow AWS provider to change record types

---

README.md

Looks like Vultr is missing in the `Latest release v0.7` section of the readme
I can create a ticket for this if need be
Fixes N/A 
**Checklist**

Add Vultr to Readme

---

kustomize/kustomization.yaml

This makes ExternalDNS 0.7.5 available via the kustomize base.
/cc @njuettner

Bump kustomize version to 0.7.5

---

docs/tutorials/aws.md

As https://github.com/kubernetes-sigs/external-dns/pull/1288#issuecomment-567119199
The correct annotation is `external-dns.alpha.kubernetes.io/aws-health-check-id: {my-health-check-identifier}`.
I also test with release 0.7.5 on my AWS environment, it worked with annotation `external-dns.alpha.kubernetes.io/aws-health-check-id`.
**Checklist**

fix doc: Correct document for aws.md about route53 health check association

---

provider/digitalocean/digital_ocean.go

Adds a custom user-agent for the godo client in the DigitalOcean provider.
**Checklist**

digitalocean: Set a custom user-agent string.

---

docs/tutorials/aws.md

This adds a section of documentation specific to changes needed to run in Govcloud.
Fixes #1917 
**Checklist**

Documentation on Route53 and Govcloud.

---

kustomize/kustomization.yaml

Before we change the way we do the kustomize release management, one more PR with the old workflow. 
/cc @njuettner

Bump kustomize version to 0.7.6

---

docs/tutorials/kube-ingress-aws.md

Signed-off-by: timyinshi <shiguangyin@inspur.com>
/kind bug
/sig docs
the error url is: https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/manifests/external-dns/rbac.yaml
the right url is: https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/manifests/external-dns/01-rbac.yaml

modify the error url of external-dns rbac

---

source/service.go
source/service_test.go

Currently, the NodePort extraction results in an SRV record with the DNS name in the following format:
```
_31569._tcp.nginx.my-external-dns-test.com 0 IN SRV  0 50 31569 nginx.my-external-dns-test.com
```
Please note that the first part of the DNS name is the **port**. That defeats the purpose of the SRV record since the client needs to know the port number upfront to query for the record to "learn" the port again from the DNS server.
DNS RFC specifies that the SRV record should be in the following format (see https://en.wikipedia.org/wiki/SRV_record):
```
_service._proto.name. TTL class SRV priority weight port target.
```
For that reason I replaced the port in the DNS name with the K8s Service name resulting in records with this format:
``` …
```

Correct format of SRV record for NodePort

---

CHANGELOG.md
provider/scaleway/scaleway.go
provider/scaleway/scaleway_test.go

Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>
Scaleway DNS allow "relative" CNAME without a trailing dot, this PR ensures we only uses absolute CNAMEs
**Checklist**
- [NA] End user documentation updated

fix(scaleway): only use absolute CNAMEs

---

docs/tutorials/alb-ingress.md

Fixes https://github.com/kubernetes-sigs/external-dns/issues/1936

Corrects broken links in alb-ingress tutorial

---

.dockerignore
Dockerfile
Dockerfile.mini

This is based off the work found in #1307 that was never merged. It
moves around the install and copy of certain conponents to take better
advantage of the Docker cache ad well as drops running tests during the
build of the image.
The reason for dropping tests is to improve build time and as running
tests within the build while they're already being run in CI seems like
an unnecessary added tax.
Signed-off-by: Danny Grove <danny@drgrovellc.com>

Cleanup Docker context and decrease build time

---

provider/scaleway/scaleway.go

Replaces https://github.com/kubernetes-sigs/external-dns/pull/1947 
/cc @njuettner

Fix typo in scaleway provider

---

provider/pdns/pdns.go
provider/pdns/pdns_test.go

Hey!
I'm not sure if I've overlooked something here but I've written in in #1967 about the problem I saw where external-dns would continually update a zone even when it was already in the correct state.
From my debugging it appears this is down to the way it fetches its Endpoints from the pdns API. I can't see *why* it's written as it is but I think my change is legit.
I've tweaked the pdns provider so that when it encounters an rrset with multiple records, instead of building one Endpoint per record, it builds a single Endpoint with multiple targets. This stops it from making the same update over and over. 
I will add this is my first time writing any Go so please shout at me if I've done something dumb -- even in this small PR!
Fixes #1967 
**Checklist**

Make Powerdns support rrsets with multiple records more smartly

---

source/virtualservice.go
source/virtualservice_test.go

Remove duplicates when collecting endpoints for Istio VirtualServices. Rather than always appending endpoints, check that it's not already in the list first.
Fixes #1949 
**Checklist**
- [ *] Unit tests updated

remove duplicate endpoints when processing VirtualService

---

docs/tutorials/akamai-edgedns.md
docs/tutorials/alb-ingress.md

Updated external-dns image version and ingress api version
Fixes #ISSUE
**Checklist**

update external-dns image versiona nd ingress api version

---

CHANGELOG.md
go.mod
go.sum
provider/scaleway/interface.go
provider/scaleway/scaleway.go
provider/scaleway/scaleway_test.go

Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>
Bump the API version of the Scaleway DNS to v2beta1
**Checklist**
- [x ] Unit tests updated
~Waiting for #1859 to rebase on it~ 
/hold

Bump Scaleway DNS API to v2beta1

---

docs/tutorials/rfc2136.md

removed **--rfc2136-gss-tsig** flat form configuration section as its not available in external-dns
Fixes #1987 
**Checklist**
- [x ] End user documentation updated

external-dns configuration update

---

docs/faq.md

This PR removes the outdated list of supported providers from the FAQ and links to the list in the README instead. This makes the supported providers list the „single source of documentation truth“.
**Checklist**

remove outdated provider list from FAQ, link to list in README

---

docs/contributing/crd-source/crd-manifest.yaml

All CRDs under k8s.io and kubernetes.io API groups should go through API
approval.
Signed-off-by: Dinar Valeev <dinar.valeev@absa.africa>
CRD must be approved
**Checklist**

Approve crd v1

---

docs/tutorials/alibabacloud.md
docs/tutorials/aws.md
docs/tutorials/azure-private-dns.md
docs/tutorials/azure.md
docs/tutorials/coredns.md
docs/tutorials/dyn.md
docs/tutorials/exoscale.md
docs/tutorials/gke.md
docs/tutorials/kube-ingress-aws.md
docs/tutorials/nginx-ingress.md
docs/tutorials/public-private-route53.md
docs/tutorials/rdns.md
docs/tutorials/rfc2136.md

Updated Ingress apiVersion from v1beta1 to v1
Fixes #ISSUE
**Checklist**
- [x ] End user documentation updated

updated ingress apiVersion

---

docs/tutorials/rfc2136.md
main.go
pkg/apis/externaldns/types.go
provider/rfc2136/rfc2136.go
provider/rfc2136/rfc2136_test.go

This adds a new optional cli flag `--rfc2136-kerberos-realm` for the rfc2136 provider.
It also updates the rfc2136 tutorial to mention this flag and adds some other tips based on my own experience with setting up external-dns.
**Checklist**

rfc2136: Add cli flag for Kerberos realm and improve tutorial

---

provider/azure/azure.go

The only thing present in the external-dns when running with the Azure provider is:
```
time="2021-03-19T21:11:37Z" level=error msg="Failed to extract targets for 'example.com' with type 'NS'."
time="2021-03-19T21:12:37Z" level=error msg="Failed to extract targets for 'example.com' with type 'NS'."
time="2021-03-19T21:13:38Z" level=error msg="Failed to extract targets for 'example.com' with type 'NS'."
time="2021-03-19T21:14:38Z" level=error msg="Failed to extract targets for 'example.com' with type 'NS'."
time="2021-03-19T21:15:39Z" level=error msg="Failed to extract targets for 'example.com' with type 'NS'."
time="2021-03-19T21:16:39Z" level=error msg="Failed to extract targets for 'example.com' with type 'NS'."
time="2021-03-19T21:17:40Z" level=error msg="Failed to extract targets for …
```

Downgrade Azure provider "Failed to extract" log message to debug

---

provider/aws/aws.go
provider/aws/aws_test.go

From measurements, AWS by default has pagination of 100 items per
page when listing hosted zone resources.
This increases the number of requests required to list all our zones,
and pushes a hard constraint on the rate limits.
From the experiments, it seems that on the server-side, there is a hard
limit of 300 elements per page, as per AWS documentation:
https://docs.aws.amazon.com/Route53/latest/APIReference/API_ListResourceRecordSets.html
> ListResourceRecordSets returns up to 300 resource record sets at a time in ASCII order,
> beginning at a position specified by the name and type elements
Hence raising the page size from 100 to 300 items would decrease by 3
the number of requests posted to Route53
We even set a higher limit so we can benefit from a lower number of
requests if ever AWS …

Increase AWS pagination size

---

.github/workflows/ci.yml
Dockerfile
Dockerfile.mini
docs/contributing/getting-started.md
go.mod

Updates the go version to 1.16 along with the documentation.
**Checklist**
- [n/a] Unit tests updated

Update to Go 1.16

---

source/service.go
source/service_test.go

Avoid a nil pointer deference in extractHeadlessEndpoints when TargetRef is nil. This was observed for an endpoint created by `kube-prometheus-stack`.
Fixes #2029
**Checklist**

Avoid nil pointer deference in extractHeadlessEndpoints

---

internal/testutils/endpoint.go
provider/aws/aws.go
provider/aws/aws_test.go

This PR supersedes #1356. It's rebased against master, has some commits squashed and I will keep rebasing until it's merged.
The management of Route 53 alias records is utterly broken in its current state, see issues #1105 and #1175.
This PR introduces a new way to handle alias records.
* A new `ModifyEndpoint` methods is introduced in a new (optional) `EndpointModifyingProvider` interface that providers can implement. It allows the AWS provider to convert CNAME endpoints (generated from various sources) to alias A records before a change plan is calculated. This allows proper deletion and update handling of alias records. Due to this change, the provider-specific check for the `aws/evaluate-target-health` provider-specific property can be removed from the plan …

AWS Route 53 provider: fix various problems with handling of alias records

---

docs/tutorials/scaleway.md
provider/scaleway/scaleway.go
provider/scaleway/scaleway_test.go

Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>
This PR drop the need to specify the Scaleway Organization ID as it's not needed.
I'll update the documentation once the new release is cut.
**Checklist**

fix(scaleway): drop support for organization ID as it's not needed

---

provider/bluecat/bluecat.go

Allow users of the Bluecat provider to enable and disable TLS Verify
Fixes #2023
**Checklist**

bluecat: allow setting tls verify and TTL

---

provider/bluecat/bluecat.go
provider/bluecat/bluecat_test.go

The TTL can now be set for CName and Host records for the Bluecat
provider. You can not set the TTL of TXT records because that is not
currently implemented in the Bluecat Gateway
Fixes #2022 
**Checklist**

bluecat: allow setting TTL on cname and host records

---

Makefile

This PR is an attempt at fixing the build to allow us to release the new ExternalDNS images with prow. 
Error is in: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-external-dns-push-images/1387323143240028160 
The idea is to force the pull from the makefile to see if the error will resolve itself. 
/cc @njuettner

Force pull golang to fix prow build

---

cloudbuild.yaml

Our last release build failed with a timeout. This PR gives much more time. We should look into having shorter jobs in the future, but for now we try this. 
/cc @njuettner

Bump CI timeout

---

go.mod
go.sum
provider/transip/transip.go
provider/transip/transip_test.go

TransIP API has switched to a REST-ful system (as opposed to the old SOAP API) some time ago and the available Go client was updated along with it, bumping it from v5 to v6. This patch replaces the old client with the new client.
**Checklist**

update TransIP's Go client to v6

---

provider/bluecat/bluecat.go

Adds support for getting BlueCat API credentials from environment
variables BLUECAT_USERNAME and BLUECAT_PASSWORD. Providing credentails
using the BlueCat JSON configuration file is still supported.
Credentials from environment variables take precedence over credentials
provided in the JSON configuration file.
Using environment variables avoids having to store credentials as k8s
secrets.
**Checklist**

bluecat: support getting credentials from environment variables

---

go.mod
go.sum
main.go
provider/vultr/vultr.go
provider/vultr/vultr_test.go

Hey there,
Last year Vultr released API v2 and API V1 was deprecated. Finally getting around to update the vultr deps to run on API v2
**Checklist**

Vultr : Update vultr provider to use API v2

---

docs/tutorials/azure-private-dns.md

#1912 introduced `azure.json` auth for the `azure-private-dns` provider. This change was released with `v0.8.0`.
The current tutorial includes this new `azure.json` syntax, but uses the `v0.7.6` image (which relies on values from environment variables).
When trying to run the tutorial template as-is today, the container started, but I received the somewhat cryptic error:
```
azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/<resource-group>/providers/Microsoft.Network/privateDnsZones?api-version=2018-09-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: …
```

Update azure-private-dns tutorial image tag to v0.8.0

---

controller/controller.go
controller/controller_test.go
endpoint/domain_filter.go
plan/plan.go
provider/aws/aws.go
provider/aws/aws_test.go
provider/provider.go
registry/aws_sd_registry.go
registry/noop.go
registry/registry.go
registry/txt.go

Currently, planning instructs to create all records even
those which does not match any zone.
Later, those records will be checked towards the existing
records and filtered whether they match or not a hosted zone.
This causes a problem, at least in the specific case of the Route53
implementation as it always calls the ApplyChanges method, which in its
turn always retrieves all records in all zones.
This causes high pressure on Route53 APIs, for non-necessary actions.
By being able to filter all unmanaged records from the plan, we can
prevent from calling ApplyChanges when nothing has to be done and hence
prevent an unnecessary listing of records.
By doing so, the rate of API calls to AWS Route53 is expected to be
reduced by 2
To do this change, providers now export, through registries, a …

Reduce AWS Route53 API calls

---

provider/hetzner/hetzner.go
provider/hetzner/hetzner_test.go

The name conditioning was applied twice which caused CNAMES to be suffixed by a double '.'. This leads to the value being rejected by the Hetzner API with error-code 422 which is not being checked at the moment.
We should probably check the error-code to be 0 so this doesn't fail silently, I can do that in another PR.
Fixes #1869
**Checklist**
/assign @21h

Fix CNAME update for hetzner provider

---

docs/tutorials/pdns.md
endpoint/domain_filter.go
endpoint/domain_filter_test.go
provider/pdns/pdns.go
provider/pdns/pdns_test.go

This change introduces a `MatchParent` DomainFilter method that can be utilised by providers to enhance `--domain-filter` to also match "parent" zones. This change then further enhances the `pdns` provider in such a way.
Fixes #2040 
**Checklist**

Feature matchparent

---

docs/tutorials/infoblox.md
main.go
pkg/apis/externaldns/types.go
provider/infoblox/infoblox.go
provider/infoblox/infoblox_test.go

Signed-off-by: mmerrill3 <jjpaacks@gmail.com>
This PR gives the ability for using a regular expression in the fqdn attribute when invoking the zone_auth API from Infoblox.
Fixes #2102 
**Checklist**

Adding ability to query Infoblox API using regex for fqdn (#2102)

---

main.go
pkg/apis/externaldns/types.go
source/multi_source.go
source/multi_source_test.go
source/store.go

This is a useful feature in environments with public global WAN addresses.
In our case we're using AKS which is Dnat'ed by Azure Firewall, hence ingress/services addresses are private. Only Azure Firewall public IP is exposed.
Fixes #1394 
Fixes #1495
Basically, you can set the `--default-targets` flag which will override the source addresses, e.g.:
```bash
external-dns  --source=ingress  --provider azure-dns --default-targets 8.8.8.8
```
**Checklist**

Add the --default-targets flag

---

source/ocproute.go
source/ocproute_test.go

This PR contains the following commits:
**source: Clean up OpenShift Route source**
source/ocproute.go:
Add/clean up godocs and general in-line comments.
Change `routeapi` named import to `routev1`.
Update `routev1` calling sites accordingly.
Signed-off-by: Stephen Greene <sgreene@redhat.com>
**source: Add ocproute source unit tests**
source/ocproute_test.go:
New file for source/ocproute.go unit tests.
Inspired by the service source unit tests,
this commit adds basic unit tests to verify
basic functionality of the OCP route source.
Signed-off-by: Stephen Greene <sgreene@redhat.com>
**Checklist**

Clean up OpenShift Route source implementation

---

registry/aws_sd_registry.go
source/node.go
source/node_test.go
source/shared_test.go

Running external-dns for node source with aws-sd registry will crash on initial loop due to labels being nil map.
IDK what would be more suitable fix here:
* to add a simple check to init a map if Endpoint Labels are nil in aws-sd registry
* to init Labels map with NewLabels() when creating Endpoints for node source.
Fixes #2094
**Checklist**

Fixed AWSSDRegistry nil labels map

---

main.go
pkg/apis/externaldns/types.go
pkg/apis/externaldns/types_test.go
pkg/apis/externaldns/validation/validation.go
pkg/apis/externaldns/validation/validation_test.go
provider/rfc2136/rfc2136.go
provider/rfc2136/rfc2136_test.go

This PR adds a new `--rfc2136-batch-change-size` option, which follows the AWS and Google providers, which already support controlling the batch size.  I defaulted the batch size to 50, which seems like a sane default to prevent large updates, while at the same time keeping most transactions atomic, as was the intent with the batching support in the first place.
Savvy users who want to revert to the `0.5` behavior without batching support can set their batch size to 1 with this patch to achieve that, which would help address https://github.com/kubernetes-sigs/external-dns/issues/1517.
When the rfc2136 provider gained batching support (https://github.com/kubernetes-sigs/external-dns/pull/1164), it introduced a couple of regressions for us in behavior compared to the `0.5` …

rfc2136: add batch size support

---

README.md

On clicking the `copy to clipboard` icon on README rendered markdown, additional `$` is being copied as well which results in `command not found` errors. This breaks seamless experience for users.

Remove  extra `$` when clicked on `copy to clipboard`

---

provider/bluecat/bluecat.go
provider/bluecat/bluecat_test.go

Added the ability to delete records for the Bluecat provider
Fixes #2143
**Checklist**

bluecat: add delete functionality

---

docs/tutorials/azure.md

As detailed in #2082, following the tutorial does not work because the default TXT register is not configured with a prefix and therefore CNAME records can not be updated / deleted once added.
Fixes #ISSUE
**Checklist**

Updated k8s manifest for Azure DNS provider #2082

---

provider/bluecat/bluecat.go
provider/bluecat/bluecat_test.go

Removed return statements for error from BluecatRecords function. 
Added two new tests and test cases to improve test coverage
**Checklist**

bluecat: improve test coverage

---

source/connector_test.go
source/crd_test.go
source/gateway_test.go
source/gloo_test.go
source/httpproxy_test.go
source/ingress_test.go
source/ingressroute_test.go
source/kong_tcpingress_test.go
source/multi_source_test.go
source/node_test.go
source/ocproute_test.go
source/pod_test.go
source/routegroup_test.go
source/service_test.go
source/shared_test.go
source/store_test.go
source/virtualservice_test.go

This makes Source tests run much faster and deterministically:
- When comparing lists of endpoints, those with the same DNS name but different targets are sorted consistently.
- When validating endpoints, compare ProviderSpecific and SetIdentifier fields.
- Test resources (services, ingresses, etc.) are created before the Source, which eliminates informer timing issues.
- Connector Source tests, which run a TCP server, pick any open port instead of using fixed ports which may be taken. Also close the listener.
- All Source tests that rely on informer synchronization have been parallelized. Locally, this drops the running time from 30s+ to ~5s.
Prelude to #2045
**Checklist**

Source: Deflake and Parallelize Tests

---

controller/controller.go
controller/controller_test.go

Use config option instead of passing just A and CNAME
Signed-off-by: Dinar Valeev <dinar.valeev@absa.africa>
Fixes #2081
**Checklist**

Fix managed-record-types option

---

controller/controller_test.go

8d6f29b8a09ddc245a712c370f1ed9de97426198 commit breaks
TestWhenNoFilterControllerConsidersAllComain and
TestWhenMultipleControllerConsidersAllFilteredComain tests,
lets fix them
Signed-off-by: Dinar Valeev <dinar.valeev@absa.africa>
Fixes https://github.com/kubernetes-sigs/external-dns/issues/2196
**Checklist**

Fix controller tests

---

Dockerfile

This PR fixes CVE-2021-36159 by bumping to the next version of alpine.
Related to https://github.com/kubernetes-sigs/external-dns/issues/2211 
/cc @njuettner

Fix alpine vulnerabilities

---

provider/scaleway/scaleway.go

This PR fixes the incorrect parsing on integer that lead to a security vulnerability as reported in https://github.com/kubernetes-sigs/external-dns/security/code-scanning/1?query=ref%3Arefs%2Fheads%2Fmaster

Fix Scaleway provider uint parsing

---

docs/tutorials/ultradns.md
scripts/update_route53_k8s_txt_owner.py
source/ingress.go
source/ingress_test.go

This PR should fix the problem of external-dns not running in v1.22. It does not provide backwards compatibility for extensions/v1beta1 ingresses as this should still be backwards compatible going back to v1.19 without any other code; I don't know the typical policy for this SIG, but given that v1beta1 Ingress has been removed, this seems safe enough (and much simpler).
Fixes #2168
**Checklist**

kubernetes v1.22: Update controller to use networking.k8s.io/v1 Ingress.

---

.github/workflows/trivy.yml
scripts/run-trivy.sh

This PR adds trivy for image scanning. It closes #2211 
/cc @njuettner

Add trivy for image scanning

---

provider/aws/aws.go
provider/aws/aws_test.go

This PR removes unused parameter is the `newChange` logic. Using these unused parameters has led to the provider calling ListResourceRecords unnecessarily. This refactor should lead to some performance improvements
Fixes #ISSUE
**Checklist**

remove unused parameters in aws change submit method

---

charts/external-dns/Chart.yaml

This updates the Helm chart to use version 0.10.0.

Bump appVersion in chart

---

kustomize/external-dns-clusterrole.yaml

Getting `Failed to watch *v1.Node: unknown (get nodes)` before, fixed with this change.
Same as Helm:
https://github.com/kubernetes-sigs/external-dns/blob/79de6b590f321343cb1298c847ec059a973d84a3/charts/external-dns/templates/clusterrole.yaml#L15-L17
**Checklist**

kustomize: Grant watch nodes instead of get

---

Dockerfile

This PR installs the tzdata Alpine package in the final external-dns container, so that timezone data is available for external-dns and its dependencies.
Fixes #2284 
**Checklist**

Install tzdata, so that time zone information is available.

---

source/service.go
source/service_test.go

Updates `source/service.go` to also check the endpoint's `SetIdentifier` before merging endpoints with the same `hostname`. Currently, services with the same hostname annotation but different set identifiers get merged, so not all the DNS records specified using annotations get created, i.e. when specifying weighted Route53 DNS records.
Fixes #2245
**Checklist**

service: fix merging of endpoints - same hostname different set-identifier

---

charts/external-dns/Chart.yaml
charts/external-dns/templates/clusterrole.yaml

Add the permissions shown [here](https://github.com/kubernetes-sigs/external-dns/blob/2f1aff4fe46c68cd0bceb2b6b7498f0c678c0ede/docs/tutorials/istio.md#manifest-for-clusters-with-rbac-enabled) to the cluster role created by the Helm chart, so that it can work with Istio.
**Checklist**

Add Istio permissions to cluster role

---

charts/external-dns/Chart.yaml
charts/external-dns/templates/clusterrole.yaml

Following up on [a previous discussion](https://github.com/kubernetes-sigs/external-dns/pull/2248#issuecomment-951773993), this PR changes the cluster role permissions to only include permissions for enabled sources. This doesn't require any additional configuration by the end user, because we know which permissions need to be added based on the sources selected in `.Values.sources`.
We run external-dns with only one source (`istio-gateway`), so we don't need to grant it permission to access endpoints, ingresses, nodes, pods, or services; the existing setup in the chart grants these permissions regardless.
I think it's beneficial to follow principle of least privilege here, and to be consistent with the setup for the Istio sources.

Only add cluster role permissions for enabled sources

---

docs/tutorials/aws.md

Expand docs for avoiding rate limiting on AWS
Relates to https://github.com/kubernetes-sigs/external-dns/issues/1293 and tries to put those ideas + PRs together into something besides `types.go`
**Checklist**
- n/a Unit tests updated

[DOCS only] Expand the AWS tutorial with common args to mitigate rate limiting

---

.github/workflows/lint-test-chart.yaml
.github/workflows/release-chart.yaml
docs/contributing/chart.md
docs/release.md

This PR achieves the following:
- Only run chart CI on this repo and not on forks
- Allow chart validation to run without changing the version in _Chart.yaml_
- Allow chart changes to be merged to master without releasing the chart
- Document the chart release process
- Document contributing to the chart 
**Checklist**

feat(chart): update chart process

---

.github/workflows/lint-test-chart.yaml
.github/workflows/release-chart.yaml

This PR fixes the chart GH actions repo filter.
See https://github.com/kubernetes-sigs/external-dns/actions/runs/1452859429 for the error.
**Checklist**

chore(chart): fix actions reop filter

---

.github/workflows/lint-test-chart.yaml
charts/external-dns/Chart.yaml

This PR re-triggers a chart release that failed due to bad CI.
This PR also fixes https://github.com/helm/chart-testing/issues/363.
**Checklist**

chore(chart): trigger release action

---

provider/azure/config.go

For some reason, code was added to set the MSI_ENDPOINT environment to a dummy value, which prevents the retrieval of an access token when using managed identities. This PR removes this code.

[azure] remove dummy MSI_ENDPOINT

---

docs/tutorials/openshift.md
main.go
pkg/apis/externaldns/types.go
pkg/apis/externaldns/types_test.go
source/openshift_route.go
source/openshift_route_test.go
source/store.go

In OCP when you have multiple ingress controllers the route's status'es Ingress object get populated with multiple router canonical names. So in this case, the external dns tries to add multiple CNAME records for same host in the same hosted zone which is a violation of RFC 1912  and therefore is rejected by standards-compliant DNS services.
This feature adds a router field to the OCP Route Source so that a user can add an ingress controller name in flag --openshift-router-name which will be used to pick up the respective router canonical name from Route's Status Ingress Object.

Fix CNAME record when multiple router canonical name are defined in Route Status.

---

docs/release.md

Currently we require using a script for release that needs to be run locally with a fresh copy of the default branch. That works well enough, but the autogeneration of release notes that GitHub added is enough for us to stop doing that and just use the UI for that part. This PR adds additional information to offer both options.
/cc @njuettner

Small change to release notes tutorial

---

README.md
charts/external-dns/Chart.yaml

With the changes made in #2281, It breaks the backward compatibility to k8s 1.18. I think this field could be used to indicates that the chart now with default `appVersion: 0.10.0` only works with k8s version >= 1.19.0.
Fixes #ISSUE
**Checklist**

doc: add Kubernetes compatibility table

---

docs/tutorials/aws.md

We run multiple Kubernetes clusters in our production AWS account, when a configuration change is made to external-dns simultaneously we see a lot of throttling from the AWS Route53 API. 
This mitigates the issue by introducing a randomised wait on startup. This mitigates rather than solves folks' issues with AWS Route63 rate limits, but might alleviate the pain when running multiple external-dns instances in the same account as we do.
Fixes #ISSUE
**Checklist**

feat: randomise startup

---

provider/azure/azure_test.go

Closes #2456.
The test is currently reaching out to azure even in a test setup. I don't think we need this test as it isn't adding much value so I opted for removing it to proceed with important fixes for azure that we need to ship in the next release.
**Checklist**

Remove broken Azure config test

---

controller/controller.go
controller/controller_test.go
docs/faq.md

Changes to count of add A records of registry and source as gauge metric 
`external_dns_registry_a_records, external_dns_source_a_records`
The existing metrics -
`external_dns_registry_endpoints_total & external_dns_source_endpoints_total` gives a cumulative count of records all records (A, SRV, CNAME, TXT).
We have a metric - external_dns_controller_verified_records which gives the intersection of A records between source & regsitry. However, in order to determined how many records are yet to be synced to registry, we need count of total A records in registry & source.
Testing - Tested the changes.
[](url)
**Checklist**

Changes to add count of A records of source and registry as metrics

---

charts/external-dns/templates/clusterrole.yaml

I totally forgot to check whether the Istio sources relied on any of the core APIs in #2413 😳 
Turns out that they need to have read permissions on services as well as the Istio custom resources.

Restore cluster role permissions to read services when Istio sources are enabled

---

charts/external-dns/Chart.yaml

This PR will update the Helm chart to use the latest [v0.10.2](https://github.com/kubernetes-sigs/external-dns/releases/tag/v0.10.2) version of ExternalDNS. It will also include the changes in #2468 & #2415.
Fixes #2475.
**Checklist**

feat(chart): Update chart to use v0.10.2

---

docs/tutorials/aws.md

Document the working method of using environment variables on the external-dns deployment to avoid the overhead of kiam or kube2iam when not using EKS
Fixes undocumented feature
**Checklist**

Document usage of AWS env vars

---

provider/rfc2136/rfc2136.go
provider/rfc2136/rfc2136_test.go

Signed-off-by: Dinar Valeev <dinar.valeev@absa.africa>
This adds NS record support to rfc2136 provider
Fixes #ISSUE
**Checklist**

RFC2136: add NS record support

---

go.mod
go.sum
provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_test.go

In order for us to use some new features provided by cloudflare-go for
the cloudflare provider (mainly around Cloudflare Access, etc.) we need
to bump the version of cloudflare-go used.
The only real change that needed to be done was that the `Proxied` field
on `cloudflare.DNSRecord` structs changed from `bool` -> `*bool`.
Upstream did this because in certain cases, a user could not flip from
proxied -> DNS only (the library omitted sending `proxied = false` to
the API)
Other decent change was that most methods exported by the library now
require `context.Context` to be passed in. Was rather trivial to get up.
https://github.com/cloudflare/cloudflare-go/pull/595
Signed-off-by: Devon Mizelle <devon.mizelle@onepeloton.com>
**Checklist**
- [N/A] End user documentation updated

Bump Cloudflare-Go

---

provider/cloudflare/cloudflare.go

I don't understand the reasoning behind this log message, we had to disable the logging inside the external-dns container due to the extensive logging.
The `endpoint.Targets` can contain multiple targets, which should be fine.
We could probably remove this logging, or refactor the logic around `newCloudFlareChange` inside `ApplyChanges`.

Cloudflare provider - Removed incorrect log message

---

docs/tutorials/alb-ingress.md
docs/tutorials/kube-ingress-aws.md
docs/tutorials/nginx-ingress.md

A previous PR (#1978) updated the ingress API version but the spec needed an update as well. I tested this locally by applying the yaml with a valid DNS hostname.
Fixes #ISSUE
**Checklist**

Fix ingress spec in given examples

---

docs/tutorials/bluecat.md
provider/bluecat/bluecat.go

Add the support of the de-facto standard HTTP proxy environment variables for BlueCat provider.
**Checklist**

BlueCat: use proxy env variables

---

.github/workflows/trivy.yml
scripts/run-trivy.sh

The trivy workflow was still broken, the last fix didn't really fix it. This is an attempt at fixing the script for good to restore the image scanning functionality.
This also makes the workflow run all the time so that we can spot vulnerabilities before merging to the default branch.

Fix trivy workflow

---

docs/proposal/registry.md

Fixes https://github.com/kubernetes-sigs/external-dns/issues/2316 
This was pointing to a google resource that does not exist anymore. As it does not add much, I'm going to just remove the link.
/cc @njuettner

Remove broken link

---

main.go
pkg/apis/externaldns/types.go
provider/infoblox/infoblox.go

Configuration to set TTL of the Endpoint of the Kubernetes side.
The kubernetes side TTL is always something and the Infoblox side is kept at 0 because of the default.
* https://github.com/kubernetes-sigs/external-dns/blob/375a5645c25975d08ef630fc1bd293cbfc6b7236/endpoint/endpoint.go#L147
This will always trigger `shouldUpdateTTL` and return `False`
We want it to trigger `targetChanged` if needed and do nothing if there are no changes.
* https://github.com/kubernetes-sigs/external-dns/blob/375a5645c25975d08ef630fc1bd293cbfc6b7236/plan/plan.go#L160
* https://github.com/kubernetes-sigs/external-dns/blob/375a5645c25975d08ef630fc1bd293cbfc6b7236/plan/plan.go#L197-L199   
In preference of #1521 (ordered):
1. #2500
1. #2496
1. #2502
1. #2501
**Checklist**

[Infoblox] Disable always changed by defaulting TTL to 0

---

provider/infoblox/infoblox.go

This adds logging per target type to give better insight in the inner workings of the records being created in Infoblox.
In preference of #1521 (ordered):
1. #2500
1. #2496
1. #2502
1. #2501
**Checklist**

[Infoblox] Granular level of logging

---

docs/tutorials/aws.md

Annotation values may not be an integer, they must be handled as a
string.  The current example tested on k8s 1.20.13 generates this error
message:
json: cannot unmarshal number into Go struct field ObjectMeta.metadata.annotations of type string
Fixes #ISSUE
**Checklist**

add quotes to ttl example to force string context

---

pkg/apis/externaldns/types_test.go

Very little change that adds the test case that verifies that overriding the config works also for `managed-record-types` (env vars and cli params). The test file works as a good source of documentation for newcomers and it helped me to realise what's the env var name of the cli param and vice-versa. The `EXTERNAL_DNS_MANAGED_RECORD_TYPES` was missing here though so I was puzzled what to use..
**Checklist**
Signed-off-by: Jirka Kremser <jiri.kremser@gmail.com>

Add missing test for overriding managed-record-types

---

provider/aws/aws.go

allows the use of cloudfront aliases with the alias annotation the same way it was done for global Accelerator.
code changes made by @georgebuckerfield
The value for the canonical hosted zone was taken from the AWS docs [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html).
Fixes #2426

Add the canonical hosted zone for Cloudfront

---

provider/aws/aws.go

This is a very small PR.
While trying to understand how AAAA records are handled, I stumbled upon this comment, because I believed that it refers to the if statement below:
```
if !provider.SupportedRecordType(aws.StringValue(r.Type))
```
However, it turns out that the comment is unrelated. It was introduced in https://github.com/kubernetes-sigs/external-dns/commit/b0f437a43833c325a0fdd2ce3288c900538562b3 and references a switch statement that has been removed (I guess the ownership system is in place now).

Remove an obsolete TODO comment

---

go.mod
go.sum
provider/azure/azure_privatedns_test.go
provider/azure/azure_test.go

Contour dependency update requires `cert-manager 1.6.x` which requires 
`github.com/Azure/azure-sdk-for-go v56.0.0+incompatible` which also forces external-dns to update to this version in our CI build.
This requires some adjustments in azure tests otherwise it will break. 
I adjusted the smallest change possible to make CI build work again.
**Checklist**

fix azure dep

---

go.mod
go.sum

Bumps UKFast SDK version, which fixes an issue with a missing package license
Fixes https://github.com/kubernetes-sigs/external-dns/issues/2665
**Checklist**

bump ukfast sdk version

---

.github/workflows/lint-test-chart.yaml
.github/workflows/release-chart.yaml
charts/external-dns/CHANGELOG.md
charts/external-dns/Chart.yaml
docs/contributing/chart.md

This PR will release the merged chart changes from #2477, #2564 & #2626 that haven't been released yet. It will also add a CHANGELOG and update the chart contribution guide to refer to this. I've updated the CI tooling and added the functionality to add release notes to the GH chart release which should make chart change discovery better.
Closes #2570
**Checklist**

feat[chart]: Release v1.8.0

---

.github/workflows/ci.yml

Running golangci-lint v1.30.0 at commit 6d7f4650 produces the below
error when running "make lint" via GitHub Actions. Not sure exactly
when this error started happening, but it is broken now.
```
Run curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0
make lint
shell: /usr/bin/bash -e {0}
env:
GOROOT: /opt/hostedtoolcache/go/1.18.0/x64
golangci/golangci-lint info checking GitHub for tag 'v1.30.0'
golangci/golangci-lint info found version: 1.30.0 for v1.30.0/linux/amd64
golangci/golangci-lint info installed /home/runner/go/bin/golangci-lint
>> checking license header
golangci-lint run …
```

Update to golangci-lint v1.45.2

---

docs/tutorials/bluecat.md

Based on feedback having both the configuration file and command line
flags for the BlueCat provider will be used. Therefore update the
documentaiton to reflect that the JSON configuration file for the
BlueCat provider is not deprecated.
Fixes N/A
**Checklist**

bluecat docs: JSON configuration file is not deprecated

---

docs/tutorials/openshift.md
source/openshift_route.go
source/openshift_route_test.go

- Use only those ingresses (`status.ingress`) which admitted the route
- Use host from `status.ingress.host` because it's
- right place for the route's host
- part of the preparation for the implementation of Route API's `spec.subdomain` field
**Checklist**

OpenShift route source: better use of route status

---

charts/external-dns/README.md

the release name was missing in the helm chart installation command line
Fixes N/A
**Checklist**
- [ N/A] Unit tests updated
- [ N/A] End user documentation updated

fix the helm chart installation command line

---

main.go
provider/bluecat/bluecat.go
provider/bluecat/bluecat_test.go
provider/bluecat/gateway/api.go
provider/bluecat/gateway/api_test.go

This was a pretty significant overhaul to the Bluecat provider codebase including:
- Cleaning up the Bluecat provider code by extracting the code that interacts with the Bluecat Gateway API into its own package
- Fixing bugs around txt record prefix and suffix that prevented CName records from being created, as well as cname and host records from being deleted if a prefix or suffix was used
- Do not execute DNS deployments if running in `dry-run` mode
- Improves some code quality issues including:
- Some unit tests for the Gateway API code
- Consistency when making HTTP request
- Better error handle HTTP requests (check for errors and verify status codes)
Fixes #2187 
**Checklist**

extract bluecat api code into its own package

---

.github/workflows/ci.yml

This PR fixes CI which was forcing to use Go version 1.17 or above. Our codebase is not compatible yet with Go 1.18 and our CI is failing since that was released.

Use Go 1.17 in CI

---

docs/proposal/registry.md
docs/registry.md
pkg/apis/externaldns/types.go
registry/txt.go
registry/txt_test.go

Add additional txt record with record type marker
In order to track multiple record types with the same name, lets migrate
to new format, were record name contains record type in it.
For migration purposes old and new format will be kept for a while.
Fixes https://github.com/kubernetes-sigs/external-dns/issues/1923
**Checklist**
- [] End user documentation updated

Registry record type

---

pkg/apis/externaldns/types.go

This PR simply changes the string output of a config such that the Kerberos RFC2136 sensitive values do not get logged on controller startup.
Signed-off-by: Dustin Scott <sdustin@vmware.com>
This PR simply changes the string output of a config such that the Kerberos RFC2136 sensitive values do not get logged on controller startup.
Fixes #2702 
**Checklist**
Unit tests and documentation update not required for this change.
- [ X ] Unit tests updated
- [ X ] End user documentation updated

feat: restrict rfc2136 kerberos password from being exposed in logs

---

charts/external-dns/CHANGELOG.md
charts/external-dns/Chart.yaml

This PR updates the Helm chart to use the latest v0.11.0 version of ExternalDNS.
Fixes #2664.
Depends on #2689 being merged first.
**Checklist**

Update to ExternalDNS v0.11.0

---

provider/bluecat/bluecat.go

For consistency and clarity as to what is being returned, named returns
are being removed from the recordSet method.
**Checklist**

provider/bluecat: remove named returns

---

source/istio_gateway.go

Add debug logging to `istio-gateway` for when an endpoint is missing, this adds logging parity to [`istio-virtualservice`](https://github.com/kubernetes-sigs/external-dns/blob/master/source/istio_virtualservice.go#L169-L172).

istio-gateway: Add debug logging when endpoints missing

---

docs/tutorials/hostport.md
source/service.go
source/service_test.go
source/source.go

If external-dns.alpha.kubernetes.io/target annotation is present on a
pod, it's value will be used as the target for the headless service.
If annotation external-dns.alpha.kubernetes.io/access=public is present,
NodeExternalIP of the node running the pod is used as the target for the
headless service.
**Checklist**

Headless service: allow to specify target as NodeExternalIP or by annotation

---

docs/tutorials/azure.md

This is an update of Azure to align it to current AKS (Kubernetes v1.22+) and document current features, such as support for AAD Pod Identities.
Updated sections with changes for consistency and readibility, such as:
* use long --form for options in documentation, rather than short -f form, as self documenting flags are preferred for documentation.
* document `default` namespace in case users may want to put ExternalDNS into a separate namespace like `external-dns` or `kube-addons`
* Azure DNS group is now consistently called `MyDnsResourceGroup`
* Update Azure doc links to multilingual URLs, not just US English (`en-us`) links 
Fixes #2743 
Fixes #2744 
Fixes #2742
**Checklist**

Azure provider doc refresh

---

docs/faq.md

The current wording of the FAQ implies that the registry option is enabled by default, which can lead to users losing data. This change updates the registry description to make obvious that this is a supported configuration option, but not a default one.
**Checklist**

[Docs] Clarify registry feature description in FAQ

---

go.mod
go.sum

Fixes dependabot alert for "Unhandled exception in gopkg.in/yaml.v3". It's a moderate level vulnerability.
/cc @njuettner

Bump yaml.v3 to fix vulnerabilit

---

.github/workflows/ci.yml
Dockerfile
Dockerfile.mini
Makefile
docs/contributing/getting-started.md
endpoint/endpoint.go
endpoint/endpoint_test.go
go.mod
go.sum
plan/conflict_test.go

This PR attempts to handle comparison between the targets of two endpoints more robustly by checking if they are IP addresses before falling back to the original string comparison behavior.
IP addresses are already _typically_ preferred over a hostname, but there is an edge case (like the one linked in the issue below) in which a hostname could be preferred over an IP address. This occurs when the hostname sorts lexicographically before the IP address during string comparison. For example, `1password.com` would be preferred over `8.8.8.8` but `8.8.8.8` would be preferred over `onepassword.com`.
Because I chose to use to the new `net/netip` package, I bumped to Go 1.18. I hope that's alright. If not, I can rewrite to use the old `net.IP` type.
Fixes …

fix: prefer IP addresses as "less" when comparing endpoints

---

docs/tutorials/gke.md

This is an update to support cross project access to Cloud DNS zones.  Before the documentation had limited utility as it documented steps that would only work in non-secure environments. 
* organize the tutorial into single project access, cross project access, deployment, and example (nginx).
* fold workload identity under cross project access, remove duplicated content
* change fictional domain to `example.com` for consistency
* remove self-promotion blog links
* expand on warnings and best-practices, add explanations, google doc links where appropriate
Fixes #509
Fixes #2747
Fixes #1597
Fixes #2751 
**Checklist**

GKE doc tutorial refresh

---

charts/external-dns/values.yaml

Signed-off-by: Tamal Saha <tamal@appscode.com>
`additionalPermissions` is an array of PolicyRule not object 
Fixes #ISSUE
**Checklist**

fix: additionalPermissions is an array not object

---

charts/external-dns/CHANGELOG.md
charts/external-dns/templates/_helpers.tpl
charts/external-dns/templates/clusterrole.yaml
charts/external-dns/templates/clusterrolebinding.yaml
charts/external-dns/templates/deployment.yaml
charts/external-dns/templates/service.yaml
charts/external-dns/templates/serviceaccount.yaml
charts/external-dns/templates/servicemonitor.yaml
charts/external-dns/values.yaml

This PR changes the chart behaviour to explicitly set the resource namespace instead of inferring it at apply time and adds support for setting common labels on all resources. I've also tidied up the chart CHANGELOG which can hopefully be kept up to date.
Fixes #2672.
**Checklist**

Explicitly set Helm chart resource namespaces & support common labels

---

provider/cloudflare/cloudflare.go
provider/cloudflare/cloudflare_test.go

Supersedes #2354
Cloudflare provider doesn't allow proxied DNS records if the records contains wildcard (*) as part of the hostname, irrespective of the zone's plan. A while ago, [Cloudflare announced](https://blog.cloudflare.com/wildcard-proxy-for-everyone/) availability of wildcard proxy in all tiers
This PR updates the `shouldBeProxied` validation, so that it no longer skips wildcard record when checking for proxied status
Other Changes
Fixes https://github.com/kubernetes-sigs/external-dns/issues/1810
Relates https://github.com/kubernetes-sigs/external-dns/pull/1542
Fixes #ISSUE
**Checklist**

Support proxying wildcard records

---

provider/rfc2136/rfc2136.go

This commit removes the need to split the host and port as the
dns client configuration was refactored in v0.12.0 to no longer
require this.
Signed-off-by: Dustin Scott <sdustin@vmware.com>
This removes the need to split the host and port.  The refactor that went into v0.12.0 changed the methodology that was used to create the handle and now no longer requires the hostname separated from the port.
Fixes #2778
**Checklist**
**NOTE:** docs not required to be updated.  Unit tests are sufficiently complex that it would not make sense to put it in this PR (unit tests require a functional KDC server to interact with) - opened issue https://github.com/kubernetes-sigs/external-dns/issues/2784 to address this.

fix: remove split of host/port

---

docs/tutorials/aws.md

This is an update of AWS that has not been refreshed since Kubernetes 1.13 (before 2019).  This adds IRSA section and brings content with verified steps on par with similar guides for AKS and GKE.  This guide is oriented around EKS, as 95% of clusters are likely on this platform, the managed K8S solution for AWS.
Some of the changes include:
* orient documentation around EKS clusters, with eksctl (officially supported by AWS) as method to bring up a reference cluster for docs and testing.
* added snippets to create cluster with `eksctl` (officially support) for consistency with GKE guide.
* put kiam (project no longer supported) and kube2iam as a note under IRSA.
* folded "Create IAM Role" and "EC2 Instance Role" into sections under "Permissions to modify DNS zone".  This …

AWS refresh, added IRSA section

---

charts/external-dns/CHANGELOG.md
charts/external-dns/Chart.yaml

Updating Helm chart to ExternalDNS v0.12.0
I've inspired myself with last commit updating the helm chart from v0.10.2 to v0.11.0 (https://github.com/kubernetes-sigs/external-dns/commit/a26ac538664e766cf3ba15b9db4e442aaed1c9d0)
Closes #2776

feat[chart]: Update to ExternalDNS v0.12.0

---

charts/external-dns/CHANGELOG.md
charts/external-dns/Chart.yaml

This PR fixes the [broken chart release](https://github.com/kubernetes-sigs/external-dns/runs/7049733823?check_suite_focus=true) for `v1.10.0` caused by a missing CHANGELOG entry in #2777.
**Checklist**

Fix Helm chart CHANGELOG for v1.10.0

---

charts/external-dns/CHANGELOG.md
charts/external-dns/Chart.yaml
charts/external-dns/templates/clusterrole.yaml
charts/external-dns/templates/clusterrolebinding.yaml

This PR removes the incorrectly added `namespace` field from the cluster scoped `ClusterRole` & `ClusterRoleBinding` resources and releases a chart patch.
**Checklist**

Remove namespace from cluster scoped resources

---

README.md
docs/tutorials/ANS_Group_SafeDNS.md
go.mod
go.sum
provider/safedns/safedns.go
provider/safedns/safedns_test.go

Following the UKFast merge with ANS group, the URL for GitHub repositories has been changed. While GitHub will redirect to the correct place, it makes sense to update references to avoid confusion going forward.
**Checklist**

Update references to UK Fast after merge with ANS group

---

controller/controller.go
docs/registry.md
main.go
plan/plan.go
plan/plan_test.go
registry/aws_sd_registry.go
registry/noop.go
registry/registry.go
registry/txt.go
registry/txt_test.go

Handle the migration to the new TXT record format automatically by ExternalDNS.
Should help fixing issue https://github.com/kubernetes-sigs/external-dns/issues/2793.
**Checklist**

Handle the migration to the new TXT format: create missing records

---

controller/controller.go
controller/controller_test.go

Follow-up of https://github.com/kubernetes-sigs/external-dns/pull/2811. Aims at addressing the following error when the missing new format TXT record gets created and deleted in the same batch:
```
Applying provider record filter for domains: [external.dns. .external.dns.]"
time="2022-07-26T07:17:45Z" level=info msg="Desired change: UPSERT cname-externaldns-e2e.external.dns TXT [Id: /hostedzone/]"
time="2022-07-26T07:17:45Z" level=info msg="Desired change: UPSERT externaldns-e2e.external.dns A [Id: /hostedzone/]"
time="2022-07-26T07:17:45Z" level=info msg="Desired change: UPSERT externaldns-e2e.external.dns TXT [Id: /hostedzone/]"
time="2022-07-26T07:17:45Z" level=info msg="Desired change: CREATE cname-externaldns-e2e.external.dns TXT [Id: /hostedzone/]" …
```

Handle the migration to the new TXT format: missing records to be created separately

---

controller/controller.go
controller/controller_test.go

When cfg.UpdateEvents is true, any service or ingress change in the Source, is invoking ctrl.ScheduleRunOnce, allowing a reconciliation to be eventually scheduled earlier than cfg.Interval, but not more often than cfg.MinEventSyncInterval.
The **problem** happens in a scenario where services or ingresses changes happen more often than cfg.MinEventSyncInterval, because the Controller.nextRunAt is **recalculated** as now + cfg.MinEventSyncInterval, allowing the next reconciliation to be pushed forward, even if it is already planned to happen, eventually even further than cfg.Interval and virtually forever.
For the sake of the example, in a very busy K8s cluster, in which one service is updated once every second, while the cfg.MinEventSyncInterval set to something bigger than …

Do not reschedule, if already scheduled in the next MinInterval

---

.github/workflows/codeql-analysis.yml
.github/workflows/docs.yml

All GitHub actions that use actions/setup-go are being updated to use Go
1.18. Now all CI tasks should be using hte same version of Go, 1.18.
Fixes N/A
**Checklist**

Update All GitHub Actions to use Go 1.18

---

charts/external-dns/CHANGELOG.md
charts/external-dns/templates/deployment.yaml
charts/external-dns/values.yaml

Add support to configure dnsPolicy on the Helm chart deployment.
This allows us to set the `dnsPolicy` to `Default` and skip in-cluster DNS to improve performance.

feat: Add support to configure dnsPolicy on the Helm chart deployment
